### ISSUE TITLE
Sugar/desugar host interop forms

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clj-refactor.el#102]
It will be nice if there was a way to toggle between:

```clojure
(. (class obj) getDeclaredFields)
```

and

```clojure
(.getDeclaredFields (class obj))
```

Some old code still uses the first style...

**Comment by expez** [comment]
Hitting `C-c C-m di` or whatever doesn't save many key presses compared to refactoring this manually.

`gxa(fggxw` is how my fingers solved this
(`exchange around (` `forward to g` `exchange word`)

 If there were more lying around the rest would fall to a macro.

The solution above has a ton of things going for it: it isn't subject to any bugs, doesn't require any development or maintenance, doesn't require the user to memorize any keybindings and isn't dependent on feature discovery :)
