### ISSUE TITLE
Add missing libspec - add to existing :refer

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#106]
I love this feature :-) Here's one issue with it tho:

```clj
(ns example)

(replace-first)
(split-lines)
```

Press `am` on `replace-first` then `split-lines`, result:

```clj
(ns example
  (:require [clojure.string :refer [replace-first]]
            [clojure.string :refer [split-lines]]))

(replace-first)
(split-lines)
```

**Comment by expez** [comment]
Usually we would do `cljr--auto-sort-ns` after manipulating the ns, but `clean-ns` is a bit different because it actually has to build an AST to clean up the ns form.  I just run `clean-ns` prior to committing now and don't worry about the ns form in the meanwhile.  

Fixing this should be pretty easy, but it's not very high on my list.

**Comment by magnars** [comment]
Good point. I haven't started using clean-ns regularly yet. I should do that. #107 is in the way right now tho.

**Comment by expez** [comment]
The original is 7 lines, here's the new version prior to any refactoring to increase readability:

```elisp
(defun cljr--insert-missing-require (symbol missing)
  (save-excursion
    (cljr--goto-ns)
    (let* ((alias? (s-contains? "/" symbol))
           (found? (re-search-forward missing
                                      (cljr--point-after 'paredit-forward)
                                      :noerror))
           (prefix (when alias? (first (s-split "/" symbol)))))
      (if (not found?)
          ;; create new entry in ns
          (progn
            (cljr--insert-in-ns ":require")
            (if alias?
                (cljr--insert-libspec-verbosely (format "[%s :as %s]" missing prefix))
              (cljr--insert-libspec-verbosely (format "[%s :refer [%s]]"
                                                      missing symbol))))
        ;; append to existing entry in ns
        (if
            ;; refer already exists
            (save-excursion
              (and (paredit-backward-up) (looking-at "\\[")
                   (re-search-forward ":refer"
                                      (cljr--point-after 'paredit-forward-up)
                                      :noerror)))
            (progn
              (paredit-forward)
              (paredit-backward-down)
              (if (not (> (+ (point) (length symbol))
                          (+ (point-at-bol) fill-column)))
                  (insert " " symbol)
                (newline-and-indent)
                (insert symbol)))

          ;; refer doesn't already exist
          ;; not already wrapped in vector
          (unless (looking-at "\\]")
            (insert "]")
            (backward-char)
            (paredit-backward)
            (insert "[")
            (paredit-forward))
          (when (> (+ (point) (length (s-concat ":refer []" symbol)))
                   (+ (point-at-bol) fill-column))
            (newline-and-indent))
          (insert (format " :refer [%s]" symbol)))
        (message "Referred %s from %s" symbol missing)))))
```

Is it worth the hassle to include this?

**Comment by magnars** [comment]
Good question. At some point, we should be able to safely run clean-ns
after any such refactoring, making this extra complexity moot. Since you've
got the code right there tho, maybe it's worthwhile to include it for now -
and mark it for death not too far in the future?

**Comment by expez** [comment]
I think `clean-ns` is reaching the point where we can run it automatically.  Can we close this @magnars?

**Comment by magnars** [comment]
We need clean-ns to support the most common form first (non-nested) at
least.

**Comment by expez** [comment]
> We need clean-ns to support the most common form first (non-nested) at
least. 

Added this today when #108 got closed.  By toggling that setting you can now use `clj-refactor` to rewrite between prefix and non-prefix form.
