### ISSUE TITLE
Middleware features not working

### ISSUE THREAD

**Issue by thomasjm** [clojure-emacs/clj-refactor.el#109]
Okay, this is strange and I would appreciate any debugging suggestions...

I'm trying to get the middleware-based features like `cljr-rename-symbol` and `cljr-clean-ns` to work. I created a tiny project with "lein new" and verified that the former works and the latter doesn't. On a larger project I've been working on, neither of them work. `cljr-rename-symbol` times out, and `cljr-clean-ns` doesn't do anything.

My `~/.lein/profiles.clj` looks like this:

```
{:user {:plugins [[cider/cider-nrepl "0.8.2-SNAPSHOT"]
                  [refactor-nrepl "0.2.2"]
                  ]}}
```

Just for example, I put a print in `cljr-clean-ns` so it looks like this:

```
(defun cljr-clean-ns ()
  (interactive)
  (cljr--assert-leiningen-project)
  (cljr--assert-middleware)
  (save-buffer)
  (let ((result (nrepl-send-sync-request
                 (list "op" "clean-ns"
                       "path" (buffer-file-name)))))
    (message "result: %s" result)
    (-when-let (error-msg (nrepl-dict-get result "error"))
      (error error-msg))
    (-when-let (new-ns (nrepl-dict-get result "ns"))
      (cljr--replace-ns new-ns))))
```

And the output is

```
result: (dict id 13 op clean-ns session bbaa599c-b8c6-4e1f-8a7b-2ea922a7a52f status (unknown-op error done))
```

Not too sure what's going on here -- the "status" evidently contains a failure, and there is no "error" key in the dict (which `cljr-clean-ns` seems to expect). It almost seems like I have the wrong version of the middleware but 0.2.2 is the latest one on Clojars... Do you have any idea what could be going wrong?

Thanks!

**Comment by benedekfazekas** [comment]
we are working hard to get 1.0.0 of clj-refactor out at the moment. so would you mind to try latest and greatest out? unfortunately you need to update both clj-refactor (latest on melpa or just get it from git) and refactor-nrepl 0.3.0-SNAPSHOT (it is on clojars).

on a bigger project it might make sense to prewarm the cache for the refactor middleware: see https://github.com/clojure-emacs/clj-refactor.el#populate-ast-cache-on-startup

keeping an eye on the nrepl-server-log buffer in your emacs might make sense too if you experience some weird behaviour. hope this helps and any bugreport is very wlc

**Comment by thomasjm** [comment]
Hey, `cljr-rename-symbol` works with refactor-nrepl 0.3.0-SNAPSHOT! (On the bigger project. I already had the latest clj-refactor and didn't need to prewarm the cache.)

`cljr-clean-ns` works on most of my files, but on one of them it fails with the following output even though my file is well-formed:

```
up-list: Scan error: "Unbalanced parentheses", 1, 3378
Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.
```

Thanks for the help!

**Comment by expez** [comment]
That message is from `smartparens`. Can you `toggle-debug-on-error` and find out what's happening?

**Comment by expez** [comment]
Perhaps the file in question affected by [this](https://github.com/clojure-emacs/refactor-nrepl/issues/17) bug?  I fixed it in a hurry the other day, but didn't push a new snapshot.

**Comment by thomasjm** [comment]
Hi @expez , I think you're right--it's that bug.

Btw, `cljr-clean-ns` doesn't seem to behave as advertised... it says it eliminates ":use" clauses, but my (ns) still has several of them after running it (?)

Anyway, I think this current issue is good to close! Thanks again for your help

**Comment by expez** [comment]
@thomasjm if it doesn't remove `:use` clauses then I'd **really** appreciate a reproducible bug report.  It totally should.  `:use` clauses are offensive!

**Comment by expez** [comment]
I tried pushing a new version to clojars with the fix for the unbalanced `:gen-class` clause, but clojars is giving me shit:

```
Could not find artifact refactor-nrepl:refactor-nrepl:jar:0.3.0-20150108.215535-14 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Hopefully this is just a transient network issue.  I'll try again tomorrow morning--if I remember--unless someone else beats me to it.

**Comment by thomasjm** [comment]
Cool, I'll look into the `:use` clause thing later and try to find a good example

**Comment by expez** [comment]
aight, it was just a transient problem.  New snapshot available!

**Comment by Bost** [comment]
Hi. I use clj-refactor Version: 20150306.350 and I still get this bug.

**Comment by Bost** [comment]
The exact message in the *Messages* buffer is:
cljr--assert-middleware: nrepl-refactor middleware not available!

**Comment by expez** [comment]
Hi @Bost, sorry for the late reply.  Most likely you've already discovered [this](https://github.com/clojure-emacs/clj-refactor.el#refactor-nrepl-middleware) section of the `README`.

**Comment by Bost** [comment]
@expez yea I did :) indeed. BTW it would be better if you put this info to the error message. "... Check :plugins in project.clj - see the README."

**Comment by expez** [comment]
@Bost yeah, you're right: the error message was kind of bad. I changed it this morning: https://github.com/clojure-emacs/clj-refactor.el/commit/e891e8018a83de0032e306ee3c6426134ec6924a
