### ISSUE TITLE
Fully setup clojure emacs configuration

### ISSUE THREAD

**Issue by hellofunk** [clojure-emacs/clj-refactor.el#110]
It would be enormously useful and helpful if there is a fully setup emacs config that includes the latest cider, the refactor tools, etc, that emacs newbies or those simply not used to extensive configuration of their editor can just clone and use directly. Does this exist? An emacs pre-built config with all the latest Clojure goodies that the clojure-emacs team has available. 

Every time I try to upgrade to the latest Cider, I get a wealth of errors. And I really want to use clj-refactor too (does it also work on cljs?) It's been enough for me to switch for now to using Cursive to see if I can improve my editing experience. The problem is that I really love emacs. But trying to get all of this going, all the different moving pieces so I can have nice refactoring tools, access to on-the-fly doc strings, arity hints for cljs files too, etc, is proving to be a major time investment.

**Comment by expez** [comment]
A well-commented example config for clojure sounds like a great idea to me.  cljs tooling is still evolving rapidly so keeping a working config up to date can sometimes feel like a chore if you want every bell and whistle activated (which I do!).   

Most of the ops in `clj-refactor` does work with cljs, but nobody on the team is currently doing a lot of cljs programming so this hasn't been a priority for the project.

**Comment by benedekfazekas** [comment]
i think those features **not** using the refactor-nrepl should work with cljs source in clj-refactor.

on an other note: :+1: for the idea! fancy creating/maintaining it @hellofunk? I am sure there would be no objection in the @clojure-emacs team to accept/endorse such a project as part of clojure-emacs.

**Comment by hellofunk** [comment]
I'd love to do it but I am a failure at emacs configs. I've tried so many times just to get the recent Cider working and can't. Hence why I'd love to see this done by someone who knows what they are doing. I could surely test it and report issues but I'd not be a good choice for actually setting it up.

**Comment by benedekfazekas** [comment]
fair enough: i had to try tho ;) let me see what i can do...

**Comment by hellofunk** [comment]
I could certainly give it a try but the number of questions I'd have along the way would probably eat up at least as much time from you all as someone else actually just doing it.

**Comment by hellofunk** [comment]
alternately, someone could do all the initial setup, i could inspect it, learn about it, see how it all fits together, then help on maintaining it.

**Comment by benedekfazekas** [comment]
well, exactly my plan ;). I put together a minimal config focused on clojure development only. you inspect/test/ask (i figure out how much a forgot/never knew about it) and then you help maintaining the minimalistic clojure dev config. and we happily live ever after...

**Comment by hellofunk** [comment]
sounds like a good idea... with emphasis on the word "minimal." just stuff that is necessary for clojure and then people can add other things as they see fit. some of the emacs configs available elsewhere are so full of bloat that it is hard to know what it is safe to strip out without losing important clojure editing features.

**Comment by benedekfazekas** [comment]
yeah minimal from emacs point of view but all bells and whistles from clojure development point of view. will be a bit biased towards my preferences obviously but then you, @expez whoever interested can comment it i guess

**Comment by hellofunk** [comment]
exactly. and a config that provides a straightforward way to upgrade to new versions of these libraries without introducing tons of breakage.

**Comment by arrdem** [comment]
I'm actually going to disagree with "minimal" here. I think that such a configuration should show off how to enable just about everything, but do so in a style ammenable to users picking and choosing what they actually want. I think that the Clojure emacs config I use is a reasonable example of such a pattern - https://www.refheap.com/95980

**Comment by hellofunk** [comment]
it would also be nice, if possible, to clarify where all the keyboard bindings are kept, and ideally have them centralized in one place, but maybe that is not possible. so users can easily know where conflicts are or easily change them without having to unearth the bowels of all the libraries.

**Comment by benedekfazekas** [comment]
@arrdem there are so many public .emacs.d configs floating around tho... only if you look at the ones on github you have a very wide source of cherry pick from. If I understood @hellofunk right the problem is not lack of info on the subject, on the contrary too much info in a way...

**Comment by expez** [comment]
An example config like this should really be maintained collectively by everyone working on clojure tooling.  Whenever the readme of some project is updated with new settings / features one would also update the example config to show it enabled.  

I think this approach is the only one that will scale. The authors of these tools will be far more motivated in keeping the example config up to date, because they want users to use their tool and benefit from all the latest development they've done.

**Comment by arrdem** [comment]
@bbatsov ping

**Comment by hellofunk** [comment]
I agree @expez and hope this happens.

**Comment by bbatsov** [comment]
I don't mind us keeping a small project with an example `init.el` featuring `cider`, `clj-refactor` and perhaps `flycheck-clojure`. Guess we should also provide a sample `profiles.clj`. I've always thought that the configuration is pretty simple, but I'm probably wrong about this... :-)

**Comment by hellofunk** [comment]
bbatsov there is nothing simple about emacs for people who are new to emacs, or those who have never done much extensive custom config.  is init.el enough? would that be enough to include in .emacs.d and have all the required packages automatically install? what about preferences for those packages, such as keybindings?

**Comment by benedekfazekas** [comment]
ok guys, I am creating one atm. as said above surely it will be biased towards my preferences (try to keep it minimal tho) but once created feel free to comment, argue etc...

**Comment by bbatsov** [comment]
OK, I'll create a repo add you to it.

**Comment by benedekfazekas** [comment]
:+1:

**Comment by arrdem** [comment]
:shipit:

**Comment by bbatsov** [comment]
The project is here - https://github.com/clojure-emacs/example-config

@benedekfazekas, @expez, @arrdem and @magnars have been granted full access.

**Comment by arrdem** [comment]
Sweet. Thanks @bbatsov

**Comment by benedekfazekas** [comment]
@bbatsov i think you need to add the created repo to the team (I tried to do it but could not).

**Comment by bbatsov** [comment]
@benedekfazekas Sorry about this. Should be OK now.

**Comment by benedekfazekas** [comment]
pushed first version with paredit (already biased I know), cider, and clj-refactor. @hellofunk feel free to give it a try.

**Comment by hellofunk** [comment]
I would not consider Paredit to be biased -- that is a required tool for any lisp, I think (who is seriously writing clojure without structural editing and navigation?).  I will give your new commit a try tomorrow. I am sure I will have questions, as the goal should be not just a working emacs config, but also one that has sufficient comments to explain how it is configured should someone wish to make changes.

**Comment by benedekfazekas** [comment]
:+1: I also added you to the example config team.

**Comment by hellofunk** [comment]
I will open an issue within the new repo for my questions on this. Looking at it now. Thanks for doing this, I'm excited to fill this big gap for the Clojure community, especially newbies.

**Comment by arrdem** [comment]
!voteclose
