### ISSUE TITLE
Mechanically create test files

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#113]
I'm not sure where this functionality belongs, it's not really a refactoring, but it's pretty handy:

```elisp
(defun cljr-create-test-file ()
  (interactive)
  (let* ((test-file (s-replace-all '(("/src/" . "/test/") (".clj" . "_test.clj"))
                                   (buffer-file-name)))
         (test-dir (file-name-directory test-file))
         (test-name (file-name-nondirectory test-file)))
    (make-directory test-dir :create-parents)
    (find-file-other-window test-file)
    (cljr--add-ns-if-blank-clj-file)
    (save-buffer))

(defun cljr--create-missing-test-file (oldfun &rest args)
  (condition-case nil
      (funcall oldfun)
    ('error (save-window-excursion (cljr-create-test-file)) (funcall oldfun))))

(advice-add 'projectile-toggle-between-implementation-and-test :around
            #'cljr--create-missing-test-file)
```

@bbatsov I looked for something like this in `projectile`.  Would you consider letting `project-toggle-between-implementation-and-test` actually create a test file if it doesn't exist?

Perhaps something like this already exists elsewhere?

**Comment by bbatsov** [comment]
The problem is that often it's not clear where exactly the test file should be (meaning it's name isn't clear either). But this can certainly be done in Projectile. 

P.S. I've removed all test-related code from clojure-mode for a reason (as it belongs to a package like projectile or perhaps cider). It will be a mistake to implement something like this in a refactoring package.

**Comment by expez** [comment]
I've updated the snippet above with some advice to `projectile` if anyone wants to give this a spin.  Right, I'll close this for now, then.

**Comment by arichiardi** [comment]
I agree with @bbatsov: one of the problems I faced in projectile was exactly this. One does not know where the test goes, it depends on the project. And I find really annoying when Projectile creates a buffer with a _test empty file that then I need to kill. I ended up not using that functionality at all.

**Comment by expez** [comment]
@arichiardi  I've updated the issue over at projectile to specify that this needs to depend on some variable.  I do, however, like that this subtly nudges people in the direction of sticking to the conventions or they'll have to generate test files and directories themselves.

**Comment by arichiardi** [comment]
@expez That's a good point, and thanks! The variable, in my case, would be just the folder root path. Then it would be nice if it created the file in the dir matching the namespace of the file and appended _test.clj at the end :)

**Comment by expez** [comment]
I think the code above does what you want.  For the file `/path/to/project/src/name/spaces/file.clj` it creates `/path/to/project/test/name/spaces/file_test.clj`.

**Comment by arichiardi** [comment]
Nice! I will try it out.

**Comment by expez** [comment]
Yes, poor copy-paste job.  Sorry!
