### ISSUE TITLE
cljr--finalize-find-symbol-buffer is never called

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#116]
When I use `find-usages` the final message, containing `syms-count`, is never received from the middleware.

**Comment by benedekfazekas** [comment]
did not really dig in. but quick check on mine has not shown this. I get the count and the grep buffer is finalised too... what version of the middleware are u using?

**Comment by expez** [comment]
snapshots all the way, but the code in `refactor.clj` hasn't changed in a while.

**Comment by benedekfazekas** [comment]
i would need a bit more debug info as i can't reproduce this locally...

**Comment by expez** [comment]
Yeah, I can tackle this one myself.  I see this on the windows machine at work too.

**Comment by expez** [comment]
This was getting called just fine when I tried to reproduce it today.
