### ISSUE TITLE
grep buffer is broken for find usages

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#119]
although the file references seem to be fine you can't open the referenced file in the grep buffer anymore. it asks you where the file is. I assume the reference is broken. It used to be absoulte path I assume...

**Comment by expez** [comment]
I'll figure out the right way to do this, but I'll just quickly revert the broken attempt for now.  Sorry about that.

**Comment by benedekfazekas** [comment]
no worries. thx
