### ISSUE TITLE
change move-form so it uses the middleware to figure out the right requires/imports for the changed namespaces

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#120]
kinda move form on steroids

1. ask for the new ns name
1. iterate through the top level forms and ask the user whether to move them or not (or alternatively get a list of top level form names to move in the minibuffer with completion)
1. create the new ns with
1. clean up both ns declarations
1. figure out which ns needs to require the other

**Comment by expez** [comment]
Move form is already capable of operating on everything selection by `region`.

For namespaces with more than a few toplevel forms it's going to be really annoying to answer `move?` over and over again.  Selecting with region is probably going to be much faster for all but the trivial cases.

Fixing `move-form` might be a better use of your time.  The previous limitation (leaving the ns we're moving into in an potentially bad state) is now something we can deal with.  By calling `find-unbound` in the new file we can get a list of symbols e.g. `str/split` and `read-string` which we can look up in the ns in the other file and find that `str` refers to `clojure.string` and `read-string` is from the `:refer` clause of `clojure.edn`.

**Comment by benedekfazekas** [comment]
yeah fair points.

**Comment by expez** [comment]
When recording the gif of this feature I realized this actually works as it should.  

All the required stuff in the previous ns is moved into the new ns and and `cljr-remove-unused-requires` is called to remove anything superfluous.  We might consider changing this to `clean-ns`, but otherwise we're good.
