### ISSUE TITLE
Some assistance for records and protocols

### ISSUE THREAD

**Issue by mtnygard** [clojure-emacs/clj-refactor.el#127]
This is a feature request for some actions that would be useful in working with types.

**Convert reify to record** This would extract a reify block out into a record, replacing the reify function with a call to construct the new record type.

**Reify a protocol or interface by name** This would add the protocol or interface name as well as stubs for the functions that are part of the named interface or protocol.

**Comment by expez** [comment]
Rebasing creates quite a bit of spam but both of these are currently fixed on master.  Let me know if this doesn't solve your problem.
