### ISSUE TITLE
Update readme with gifs

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#128]
These have been recorded so far:

- [x] cljr-add-declaration
- [x] cljr-add-import-to-ns
- [ ] cljr-add-project-dependency
- [ ] cljr-add-require-to-ns
- [ ] cljr-add-use-to-ns
- [x] cljr-cycle-coll
- [x] cljr-cycle-if
- [x] cljr-cycle-privacy
- [ ] cljr-cycle-stringlike
- [x] cljr-cycle-thread
- [x] cljr-destructure-keys
- [x] cljr-expand-let
- [x] cljr-introduce-let
- [ ] cljr-move-form
- [x] cljr-move-to-let
- [ ] cljr-project-clean
- [ ] cljr-rename-file
- [ ] cljr-remove-unused-requires
- [ ] cljr-replace-use
- [ ] cljr-sort-ns
- [ ] cljr-sort-project-dependencies
- [ ] cljr-stop-referring
- [x] cljr-thread-first-all
- [x] cljr-thread
- [x] cljr-thread-last-all
- [x] cljr-unwind-all
- [x] cljr-fully-unwind
- [x] cljr-thread-last
- [x] cljr-unwind-thread
- [x] cljr-promote-fn
- [x] cljr-unwind
- [ ] cljr-remove-debug-fns
- [x] cljr-find-usages
- [x] cljr-extract-fn
- [x] clj-magic-requires
- [x] cljr-rename-symbol
- [x] cljr-add-missing-libspec

**Comment by magnars** [comment]
I think the gifs are really great, but they do make for a busy readme. In particular when you see it half finished and before you get an idea what it's supposed to do. My suggestion is that we link to the gifs instead if inlining them, so that you can see them at your own pace and always from the start. :)

**Comment by benedekfazekas** [comment]
perhaps create a separate md file for them?

**Comment by magnars** [comment]
A separate md has the same issue of "when does this thing start?" - and it too would be very busy. So I hope we can just link straight to the gifs. Even cooler might be separate pages for each feature, with a title, the gif, and then an explanation, but that sounds like a lot of work.

**Comment by benedekfazekas** [comment]
and/or demo screencast video @rundins style? (not contradicting really just adding ideas)

**Comment by magnars** [comment]
I am planning on doing an emacsrocks episode once we've released 1.0.

**Comment by benedekfazekas** [comment]
sounds awesome!

**Comment by expez** [comment]
I also think we should link to the gifs instead of inlining them in the readme, but I was toying with the idea of turning the readme into a wiki.  It's getting pretty long.  On the other hand there's still so much to do, so not sure I want to spend a ton of time on a wiki lol

**Comment by expez** [comment]
The [wiki](https://github.com/clojure-emacs/clj-refactor.el/wiki) is now fully populated with examples.  The readme has been made significantly shorter.
