### ISSUE TITLE
clean-ns doesn't handle one-word namespaces

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#129]
For instance, the [expectations test framework](http://jayfields.com/expectations/index.html) uses only `expectations` as the namespace. This breaks clean-ns, since it sees it as a blank prefix. Due to the way clean-ns currently works, you only see bad results if there are several namespaces of this sort:

```clj
(ns example
  (:require [expectations :refer :all]
            [test-helper :refer :all]))
```

->

```clj
(ns link-gatekeeper.serve-jars-test
  (:require [
             [expectations :refer :all]
             [test-helper :refer :all]]))
```

**Comment by expez** [comment]
https://github.com/clojure-emacs/refactor-nrepl/commit/de44fffaaa7567807f1b628113922e62a824b664

Also pushed a new snapshot.

**Comment by magnars** [comment]
:+1:
