### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/clj-refactor.el#134]
I'm not sure if this should be filed here or over at Projectile.

**Comment by expez** [comment]
Once https://github.com/clojure-emacs/clj-refactor.el/issues/35 is done we can solve the clojure part of this one (updating all the source files).  

What remains after that is 

* Move the root dir 
* Run `projectile-replace-in-project` or something similar to update the readme etc with references to old name.

As this is something that's done so rarely I'm not sure if we should provide an op for this.  

Does anyone else have a thought?

**Comment by benedekfazekas** [comment]
i will need something similar in mranderson although not in project.clj level...

**Comment by expez** [comment]
Moving the root dir and doing find and replace in the project should be good enough for this rare situation.
