### ISSUE TITLE
Problem with cljr-promote-function

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/clj-refactor.el#137]
Hello guys,
on this sexp ```(sort-by #(bb/value-over-weight (second %1)) > indexed-items)```, I get the following error:

    cljr--append-fn-parameter: Wrong number of arguments: (lambda nil "Move forward an S-expression, or up an S-expression forward.
    If there are no more S-expressions in this one before the closing delimiter, move past that closing delimiter; otherwise, move forward past the S-expression following the point." (interactive) (condition-case nil (forward-sexp) (scan-error (if (paredit-in-string-p) (forward-char) (up-list))))), 1

I tried to remove ```second``` but it does the same...

**Comment by expez** [comment]
Let `|` indicate the cursor:

```clj
(sort-by #(bb/value-|over-weight (second %1)) > indexed-items)
```

and I do `cljr-promote-function` and I type `foo` and I press `RET` then I get:

```clj
(sort-by (fn [foo] (bb/value-over-weight (second foo))) > indexed-items)
```

**Comment by arichiardi** [comment]
No, in my case it changes the function to (fn [] ...) asks for the input and then throws the error when I press RET.

**Comment by expez** [comment]
Try grabbing the latest version from `melpa`.  `git show 04ef8c9` yields nothing so it's hard to say how old that version is.

**Comment by arichiardi** [comment]
Mmm...no but it should be HEAD...
```commit 04ef8c95626ba3891848043bdc348a4e2a90a35c```

**Comment by expez** [comment]
You might try starting emacs without your config, just loading in `clj-refactor` and `cider` and see if it's some of your custom stuff (or interactions with other packages) which breaks this.  `emacs -Q` gives you nothing but plain emacs.

Otherwise you can step through the function using `edebug`.  Edebug is very simple to use, and if you write any elisp at all it's well worth taking 5 minutes to learn about this tool.

You can read more about edebug [here](http://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html)

Nic Ferrier also made a pretty cool video showcasing edebug, if you need further [motivation](https://www.youtube.com/watch?v=odkYXXYOxpo) :)

**Comment by arichiardi** [comment]
Updated to nRepl 0.2.10, same error, I did not have time to debug it..

**Comment by arichiardi** [comment]
It looks like I end up in the following situation right before entering the fn parameter (notice the position of ```| right before the closing parens):

    (sort-by #(bb/value-over-weight (second %1|)) > indexed-items)

At this point ```(paredit-forward-down) is called, the first one in cljr-refactor code, and of we cannot go down I think (I have not debugged paredit yet).

How to proceed?

**Comment by arichiardi** [comment]
I am not elisp expert, and I know I should maybe ask there, but the paredit fns are:

    (eval-and-compile
      (defmacro defun-saving-mark (name bvl doc &rest body)
        `(defun ,name ,bvl
           ,doc
           ,(xcond ((paredit-xemacs-p)
                    '(interactive "_"))
                   ((paredit-gnu-emacs-p)
                    '(interactive)))
           ,@body)))

    (defun-saving-mark paredit-forward ()
      "Move forward an S-expression, or up an S-expression forward.
       If there are no more S-expressions in this one before the closing
       delimiter, move past that closing delimiter; otherwise, move forward
       past the S-expression following the point."
    (paredit-handle-sexp-errors
      (forward-sexp)
    ;++ Is it necessary to use UP-LIST and not just FORWARD-CHAR?
    (if (paredit-in-string-p) (forward-char) (up-list))))

**Comment by expez** [comment]
`M-x find-library paredit <RET>`

`;; Version: 20150217.713`

```elisp
(defun-motion paredit-forward-down (&optional argument)
  "Move forward down into a list.
With a positive argument, move forward down that many levels.
With a negative argument, move backward down that many levels."
  (paredit-up/down (or argument +1) -1))
```

Seems we found the difference.  If you also grab `paredit` from `melpa` I'm guessing this problem will disappear.

**Comment by arichiardi** [comment]
And indeed I had:

    ;; Author: Taylor R. Campbell
    ;; Version: 22

**Comment by expez** [comment]
So upgrading paredit solved this?

**Comment by arichiardi** [comment]
A sec, I am using emacs live and I am doing it :D

**Comment by arichiardi** [comment]
Ok, I went [here](http://www.emacswiki.org/emacs/ParEdit) and downloaded [24 Beta](http://mumble.net/~campbell/emacs/paredit.el) and it works.

**Comment by expez** [comment]
Thanks for your help, @arichiardi!

**Comment by arichiardi** [comment]
Thanks to yours, wonderful library!

**Comment by martintrojer** [comment]
:-1: 

stable cli-refactor now has a dependency to a non-stable library. Makes not possible to install from stable.melpa.org

**Comment by benedekfazekas** [comment]
good shout. we will very likely release 1.0.5 of both clj-refactor and nrepl-refactor soon

**Comment by timvisher** [comment]
:+1: @martintrojer I don't even enable melpa-edge by default.

**Comment by benedekfazekas** [comment]
`1.0.5` with paredit 24 is released. sry for the inconvenience guys cc @martintrojer @timvisher

**Comment by martintrojer** [comment]
thx!

**Comment by timvisher** [comment]
\( ﾟ◡ﾟ)/
