### ISSUE TITLE
clean-project wants to save the world

### ISSUE THREAD

**Issue by philjackson** [clojure-emacs/clj-refactor.el#139]
Running `cljr-project-clean` seems to prompt continuously for a save file location (without it being clear what file needs to be written).

On latest release in Melpa (20150421.529).

**Comment by magnars** [comment]
Nice issue title!

I fixed this problem in https://github.com/clojure-emacs/clj-refactor.el/commit/da2d02d030adaf6dab0e59f925d0490574ccd49a

**Comment by benedekfazekas** [comment]
thx @magnars!

**Comment by philjackson** [comment]
:thumbsup:

**Comment by ccann** [comment]
I have this issue with:

clj-refactor 20170126.118
clojure-mode 5.6.1
cider 0.14.0
refactor-nrpl 2.3.0-SNAPSHOT
tools.nrepl 0.2.12
cider-nrepl 0.14.0

it just prompts me for a place to save some mystery file without specifying which file is being saved or why

**Comment by vemv** [comment]
Same!

Using:

cider-20170525.255
clj-refactor-20170520.323
clojure-mode-20170527.1442

**Comment by vemv** [comment]
Any clue? I can reproduce the issue with a pristine spacemacs, for example.

**Comment by yogsototh** [comment]
Same issue with current `doom-emacs`.

**Comment by vemv** [comment]
It looks like a bad interaction with undo-tree: https://grep.app/search?q=File%20to%20save%20in&filter[lang][0]=Emacs%20Lisp

**Comment by vemv** [comment]
Looks like it would be a matter of temporarily removing `'undo-tree-save-history-from-hook` / `'undo-tree-save-history-hook` from `write-file-functions`. (The name of the hook will depend on your undo-tree version)

Seems simple enough but it someone wants to be a hero and QA this himself + PR it, so much the better 🍻 personally I use this refactor-nrepl feature  from a repl, not from clj-refactor.el so I have it slightly more difficult to try this out.

**Comment by vemv** [comment]
Fix available in 3.1.0
