### ISSUE TITLE
rename-symbol only works on referred symbols

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#140]
If I have `ns-alias/my-symbol` and enter `ns-alias/my-new-symbol` when prompted for a name `find-symbol` renames everything to `my-ns-alias/my-ns/alias/my-new-symbol`

If i instead enter `my-new-symbol` when prompted for a name, only the file in which the query was made is changed (but it is changed in a correct manner).

**Comment by benedekfazekas** [comment]
so this is genuinely a client problem not a middleware problem. do i understand this right?

**Comment by expez** [comment]
Not sure.

**Comment by benedekfazekas** [comment]
I can only partly reproduce. if I rename the symbol and enter only `my-new-symbol` the rename happens OK across files
