### ISSUE TITLE
1.0.4 depends on paredit beta

### ISSUE THREAD

**Issue by phillord** [clojure-emacs/clj-refactor.el#142]
Which unfortunately makes it it uninstallable from melpa stable. Partly a bug with melpa stable I guess, and partly because paredit has had a lot of changes since the last release.

**Comment by expez** [comment]
`1.0.5` coming out later today to remedy this situation.  Sorry about the oversight!

**Comment by benedekfazekas** [comment]
indeed as @expez said with paredit 24 (latest stable)

**Comment by phillord** [comment]
Thanks for the very rapid response!

I run my cask file on "melpa-stable" and only switch to melpa when I really need to depend on a pre-release version which. Works for me.

**Comment by benedekfazekas** [comment]
`1.0.5` has been released with paredit 24. thanks for the report
