### ISSUE TITLE
rename-symbol doesn't update the :refer clause

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#144]
I just renamed a referred symbol and it got all occurrences except the one in the refer clause of the ns in which I called the op.

**Comment by benedekfazekas** [comment]
seems to be the case when you searching/renaming a 3rd party symbol. acc to my tests if the referred symbol is from the same project the refer line is also in the occurrence list.

so not saying it is not a bug but not too damaging as not likely you want to rename a 3rd party symbol

**Comment by expez** [comment]
I was renaming a function defined in the project. Might have been a fluke off-by-one error or something.

**Comment by benedekfazekas** [comment]
hm.. i was able to reproduce the problem when searching for a 3rd party symbol... but perhaps something else triggers the bug then...

**Comment by expez** [comment]
I can't no longer reproduce this issue either.
