### ISSUE TITLE
cljr-change-function-signature

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#149]
from a conversation with @jonpither

```
Jon Pither: optimise function args
Jon Pither: if I have a a (defn foo [x y] (println x)) that fn is only using x
Jon Pither: if your magic could remove y from the args list, BUT also fix callers
```

or a simpler version:
```
or delete a param and fix callers
```

**Comment by expez** [comment]
I needed something similar yesterday where I thought the order of function parameters was stupid.  So `cljr-change-signature` should probably be able to:

* Reorder parameters
* Drop one or more parameters
* Rename parameters? (This is really just `cljr-rename-symbol` on one or more of the function parameters)

**Comment by benedekfazekas** [comment]
perhaps 
- add parameter and go through all callers adding implementations of new param

**Comment by expez** [comment]
That sounds like something that is easier to do manually relying only on `find-usages`.
