### ISSUE TITLE
Extraneous whitespace after project clean.

### ISSUE THREAD

**Issue by philjackson** [clojure-emacs/clj-refactor.el#155]
Sometimes, when running project clean, the libspecs have whitespace appended to them, even if the libspecs themselves haven't changed:

![extranious-whitespace](https://cloud.githubusercontent.com/assets/43794/7880052/ef7fb0b0-05ed-11e5-9ae6-f83cd2dc4285.png)

**Comment by benedekfazekas** [comment]
what is in your project clean: remove requires or clean ns?

**Comment by philjackson** [comment]
I'd just come back to mention that I only have `cljr-remove-unused-requires` in there. Presumably sort would clean out that WS?

**Comment by philjackson** [comment]
Looking at the code (I probably should have done first) it's an easy enough fix to call `delete-trailing-whitespace` on the region that's already defined. Shall I patch?

**Comment by expez** [comment]
That would be great :+1:
