### ISSUE TITLE
Minor issue when using cljr-add-stubs

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/clj-refactor.el#158]
A gif says it all:

![cljr-add-stubs-bug](https://cloud.githubusercontent.com/assets/1724788/7931216/0012d37a-090f-11e5-8982-e6ae47ffcfcd.gif)

Note that if point is exactly on ```Fetch```, the position of the stub is correctly placed inside the outer form (in my case ```defrecord```).

/cc @expez

**Comment by expez** [comment]
I'm not going to fix this, just put your cursor on the name like the docstring says :) 

I'm actually surprised this works, I'd expect `cider-symbol-at-point` to fail when there's only whitespace below point.

**Comment by arichiardi** [comment]
Ah Ah Ah yes of course :smiley: Well at least now we know something more about ```cider-symbol-at-point```.
