### ISSUE TITLE
Add conditional :lighter value to the minor-mode to indicate if AST is in a bad state

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/clj-refactor.el#164]
Something like:

```emacs-lisp
(define-minor-mode clj-refactor-mode
  "A mode to keep the clj-refactor keybindings."
  :init-value nil
  :lighter (if cljr--ast-ok-p " cljr" " cljr!")
  :keymap clj-refactor-map)
```
So one would probably add an after-save hook that asks `refactor-nrepl` for the state of the AST and updates the value of `cljr--ast-ok-p` accordingly. Thoughts?

**Comment by benedekfazekas** [comment]
generally I like the idea. is this the 'standard' mode to do something like this? btw I would add the after save hook in clj-refactor itself (perhaps give a config to opt out). I don't get the name `:lighter`

**Comment by luxbock** [comment]
I think it's just a different syntax for `define-minor-mode`. It would be the same as:

```
(define-minor-mode clj-refactor-mode
  "A mode to keep the clj-refactor keybindings."
  nil (if cljr--ast-ok-p " cljr" " cljr!") clj-refactor-map)
```

And yeah, I was thinking about adding the hook to `clj-refactor` itself. Making it optional seems sound too, though I think default might as well be on? I don't see much harm in it.

**Comment by benedekfazekas** [comment]
yeah i meant *on* by default. but a nice config to opt out if you don't like it for some reason.

**Comment by expez** [comment]
This is a cool idea but outside the scope of clj-refactor, as it's not a refactoring.  

This should be a checker for flycheck.  If I were doing this I would extend [squiggly-clojure](https://github.com/clojure-emacs/squiggly-clojure) with another checker (it already supports `eastwood`, `kibit` and `core.typed`).

**Comment by benedekfazekas** [comment]
disagree here. you are right saying that this is essentially a flychecker thing. it is still better ux if we warn the user that his ns is broken therefore he wont be able to use nrepl supported refactorings. this is deffo clj-refactor scope i think

**Comment by expez** [comment]
Aight, guess it does make some sense because the ast building is more of a status for the entire project whereas flycheck provides information local to the current buffer.

**Comment by benedekfazekas** [comment]
@luxbock i guess this has passed 'team screening' if u wanna have a stab at it ;)

**Comment by luxbock** [comment]
Sure!

**Comment by expez** [comment]
After thinking some more on this I still think this should be a flycheck checker, because flycheck already has facilities to answer the user's next questions: what is the problem? Where is it?  How do I jump there?

I also still think this is something that belongs in squiggly-clojure because you might be interested in this functionality even if you don't give a hoot about clj-refactor.  Furthermore, extending squiggly-clojure would mean an order of magnitude less work because it already has all facilities in place to do this.

**Comment by benedekfazekas** [comment]
@luxbock this is kinda enabled by https://github.com/clojure-emacs/refactor-nrepl/commit/9f135d589a7d3db03b89ca8e6c887bc61db6e178 also see `cljr--maybe-nses-in-bad-state` let me know what you think and feel free to improve
