### ISSUE TITLE
global rename symbol fails to update definition of symbol (defn)

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#167]
however find symbol finds the defn form

**Comment by benedekfazekas** [comment]
:+1: thx

**Comment by expez** [comment]
Do you think we should treat this as a bug in `find-symbol`?  It's a bit weird that it isn't returning the position of the symbol but of the defining form.

**Comment by benedekfazekas** [comment]
hm... interesting. I think it kinda makes sense as the symbol is defined there so in a sense the definition stands for the symbol (rather than just the name which will be used to bind the construct to)

this may not be handy here but might be useful elsewhere...

**Comment by expez** [comment]
This was actually annoying elsewhere too, now that I think about it.  When re-using `find-symbol` to write extract-definition I had to increment the column so `extract-enclosing-sexp` extracted the `def` form.

**Comment by benedekfazekas** [comment]
and we also could mark this occurrence in the list

**Comment by expez** [comment]
>  I think it kinda makes sense as the symbol is defined there so in a sense the definition stands for the symbol 

A view that makes as much sense is that the symbol is just an argument like any other to `def`, `defn` etc :)

**Comment by benedekfazekas** [comment]
back to your `extract-definition` example: would not it be easier if that occurrence is marked. you anyway have to handle the def occurrence differently for this feature, right? so at the end of the day you need this information that this element in the list is special...

**Comment by expez** [comment]
Yeah it would be easier.
