### ISSUE TITLE
Parameter order for extract function is reversed

### ISSUE THREAD

**Issue by stathissideris** [clojure-emacs/clj-refactor.el#168]
If from the position below I run extract-function...

```clojure
(defn foo [x y z]
  (* | x y z))
```

... you get this:

```clojure
(defn- multiply
  [z y x]
  (* x y z))

(defn foo [x y z]
  (multiply z y x))
```

Which is the reverse parameter order of what you would expect. Consider changing the behaviour to maintain order of the parameters.

**Comment by stathissideris** [comment]
Thanks!

**Comment by benedekfazekas** [comment]
np. although travis build failed. it seems that behaviour is different based on the clojure version you use (bit of a wtf...)

**Comment by benedekfazekas** [comment]
that said the case you quote in the issue passes for all clj versions

**Comment by stathissideris** [comment]
Hm, you're doing the filtering using the result of (keys) and a set.
Neither has guaranteed order. What happens with say 20 parameters?

**Comment by benedekfazekas** [comment]
hm.. i maybe wrong here but what really counts is the order `keys` which does return keys in order...

**Comment by expez** [comment]
> hm.. i may be wrong here but what really counts is the order keys uses. it does return keys in order...

Ordering is not part of the contract for `keys`.  The tests failing indicate as much :p

**Comment by stathissideris** [comment]
For small maps, clojure uses PersistentArrayMap which is backed by an array
so that's probably why you see some consistent ordering in some cases.

hm.. i maybe wrong here but what really counts is the order keys which does
return keys in order...

—
Reply to this email directly or view it on GitHub
<https://github.com/clojure-emacs/clj-refactor.el/issues/168#issuecomment-111700976>
.

**Comment by benedekfazekas** [comment]
> Returns a sequence of the map's keys, in the same order as (seq map).

i think the problem is rather that the underlying map's order is not really something i can build on...

**Comment by benedekfazekas** [comment]
i basically flipped around the solution: so params ordered in the order there are used in the extracted s-expression which makes much more sense. only caveat that macro expanded order counts (threading macros!)
