### ISSUE TITLE
Renaming a file messes up my namespace "style"

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/clj-refactor.el#172]
Maybe this is a very little caprice and I apologize in advance if it is.
I could start working on this in case. Let me explain.

I so like to write my ```require``` in the form:

```[my.namespace.core :as core]
    [my.namespace.text :as text]``

This gives me the flexibility to comment/uncomment/delete a line without flinching.
Now, ```clj-refactor``` is writing everything in the following form when renaming:

```[my.namespace
      core :as core
      text :as text]]```

@expez @magnars Could you point me to the right location in ```clj-refactor``` or ```refactor-nrepl``` I can look at?

**Comment by expez** [comment]
The prefix rewriting can be turned off by tweaking `cljr-favor-prefix-notation`.

**Comment by arichiardi** [comment]
Great! Closing :+1:

**Comment by expez** [comment]
if you're changing this after starting the repl (and the middleware) you have to call `cljr-reload-config`.

**Comment by arichiardi** [comment]
Thanks, will do :smile:
