### ISSUE TITLE
move referred symbol in ns to aliased and the other way around

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#173]
find all referred symbols of a namespace in the namespace and change them to be aliased/prefixed.

makes sense to do the other way around: remove the alias and refer all used symbols from ns we are requiring

**Comment by expez** [comment]
this is called `cljr-stop-referring` :)

**Comment by benedekfazekas** [comment]
haha sry. should know cljr better u mean?! ;) and :( close then? or can u turn all aliased into referred?

**Comment by expez** [comment]
> or can u turn all aliased into referred?

This you cannot do.  But you shouldn't either.  The clojure community has been (gradually) moving away from referring symbols.  We first saw this when `:use` basically became deprecated.  Then people started saying you shouldn't use `:require` with `:all` and (finally) now there seems to be an agreement that even `:refer` should be used quite sparingly.

I think this is the right way to do things and I'm glad we have refactorings in place to help people get rid of all their referred symbols :)

**Comment by benedekfazekas** [comment]
fair enough. i could argue here a bit but i prefer aliased as well... /me going back to holiday mode ashamed..

**Comment by expez** [comment]
if you're looking something to work on, other than the outstanding issues in refactor-nrepl, then I do think `cljr-stop-referring` could use some love.  It's somewhat annoying to have to move the cursor to the libspec you want to operate on.  The last time I used this refactoring I felt like it would've been cooler with just a completing read of the namespaces with referred symbols.

**Comment by benedekfazekas** [comment]
will add it to my list. still on holidays
