### ISSUE TITLE
Use message or user-error, not error, if in a bad state

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#178]
A source file being in a bad state is a pretty routine situation, whereas throwing errors is for unexpected stuff.
As it is now, it will unnecessarily popup a backtrace if `debug-on-error` is non-nil.

I think a regular message would be more appropriate. Or maybe print something on the repl buffer.
If you must throw a signal, then I think `user-error` would be more appropriate.

**Comment by benedekfazekas** [comment]
interesting point. as for our AST backed features (most of them anyway) this is show stopping situation tho... (i lately implemented that you can still run find usages in the scenario if you want to) I still kinda agree as I experience the same; while refactoring/messing with your code some broken namespaces are pretty common

**Comment by Malabarba** [comment]
Still, if this is a big deal you should `user-error` instead of `error`. An error is saying "there's something wrong with Emacs or with the package". A user error is saying "the user did something wrong or something we don't support".

**Comment by benedekfazekas** [comment]
agreed. will fix this

**Comment by expez** [comment]
Messed up the issue reference, but I fixed a bunch of these in https://github.com/clojure-emacs/clj-refactor.el/commit/f4a8234b0717452f1de2a6c95ecec1cdf836378c
