### ISSUE TITLE
Automatic insertion of namespace declaration does not work for boot projects

### ISSUE THREAD

**Issue by timothypratley** [clojure-emacs/clj-refactor.el#180]
boot users https://github.com/boot-clj/boot do not benefit from this feature as they do not have a project.clj file.

Also, Clojurescript projects often structure their code in src/cljs directories, but do not include cljs in the namespace.

I think it would be reasonable to search for "src" "cljs" "src-cljs" "project.clj" "build.boot" as indicators of a project root.

```(defun clojure-expected-ns ()
  "Returns the namespace name that the file should have."
  (let* ((project-dir (file-truename
                       (locate-dominating-file default-directory
                                               "project.clj")))
         (relative (substring (file-truename (buffer-file-name)) (length project-dir) -4)))
    (replace-regexp-in-string
     "_" "-" (mapconcat 'identity (cdr (split-string relative "/")) "."))))```

**Comment by expez** [comment]
Hi

`clojure-expected-ns` isn't our function.  You'll have to file a bug over at [clojure-mode](https://github.com/clojure-emacs/clojure-mode)

**Comment by benedekfazekas** [comment]
we do have some functions (`cljr--project-dir`) which look for the project.clc or pom.xml. we might update the to try for `build.boot` too
