### ISSUE TITLE
find usages  with remote repl ?

### ISSUE THREAD

**Issue by maruks** [clojure-emacs/clj-refactor.el#181]
find usages  doesn't  seem to work when cider is connected to a remote repl.

Emacs opens a new buffer  but there are no results:
"'foo' occurs in the following places:"

(cljr-version)
"clj-refactor 1.0.5, refactor-nrepl 1.0.5"

:plugins [[cider/cider-nrepl "0.9.1"]
            [speclj "3.3.0"]
            [refactor-nrepl "1.0.5"]
            [lein-exec "0.3.5"]]

**Comment by expez** [comment]
If you do `(setq nrepl-log-messages t)` what does the message being sent to the middleware look like?  I'm guessing the `dir` argument is wrong.

**Comment by maruks** [comment]
it is wrong

(<-
  err  "java.io.FileNotFoundException: /Users/maris/work/.../foo.clj (No such file or directory)\n........
  ex  "class java.io.FileNotFoundException"
  id  "49"
  session  "ac3457d4-3238-4857-a6fc-19dbbe6ed0f9"
  status  ("done" "refactor-nrepl-error")
)

**Comment by maruks** [comment]
There is another project where find-usages doesn't work even with local repl. 
A namespace is always in a "bad state".   I have no idea why.

**Comment by expez** [comment]
> A namespace is always in a "bad state". I have no idea why.

If you do `(setq cljr--debug-mode)` and `M-x cljr-reload-config` you should get a nasty stacktrace from `tools.analyzer.jvm` when you run `find-usages` which might give you some indication as to why the AST can't be built.

I'm guessing this is caused by unsupported reader literals.  Taking `*data-readers*` into account when building an AST was recently fixed.

**Comment by expez** [comment]
> find usages doesn't seem to work when cider is connected to a remote repl.

Our middleware (which runs on the machine where the repl is started) needs to have access to the source files, to build an abstract syntax tree.  Furthermore, the repl has to be started in the context of the project where you want to run `find-usages` or we won't be able to find the source files on the classpath.  In other words you can't keep one repl open and jump around between projects calling `find-usages`.

If any of this describes the situation in the original post, then there's unfortunately nothing we can do.

**Comment by maruks** [comment]
It seems that it sends local pathname to remote REPL and expects to find it on machine where
REPL is running      

"/Users/maris/work/.../foo.clj"   is filename on my mac.     I am connected to REPL on a linux box.
There is no such file there.

(<-
err "java.io.FileNotFoundException: /Users/maris/work/.../foo.clj (No such file or directory)\n........
ex "class java.io.FileNotFoundException"
id "49"
session "ac3457d4-3238-4857-a6fc-19dbbe6ed0f9"
status ("done" "refactor-nrepl-error")
)

**Comment by expez** [comment]
Yeah, as I explained above, the current implementation has some limitations with regard to remote repls. 

What is your use-case for connecting to a remote repl for when doing development?

**Comment by sickill** [comment]
`cljr-clean-ns` gives me a similar issue. My use case is: I run the repl inside a Vagrant VM and connect to it from Emacs on my Mac. The error says it expected local paths to be found in a VM (remote). But I guess this isn't something that can be easily fixed.

**Comment by expez** [comment]
Someone else had a similar issue and submitted a PR to fix clean-ns.  It should work with 2.0.0.

**Comment by sickill** [comment]
@expez thanks, works like a charm with 2.0.

**Comment by jasonjckn** [comment]
i also have a similar use case, i'm doing development inside a docker container of my app, so I use remote repl to connect into the docker container
