### ISSUE TITLE
Debugging user-error: Some namespaces are in a bad state

### ISSUE THREAD

**Issue by tsdh** [clojure-emacs/clj-refactor.el#184]
I just started using `clj-refactor.el` and love it. However, when I perform a refactoring needing AST access like `cljr-rename-symbol` in [this project](https://github.com/jgralab/funnyqt), I always get the error message:

```
error in process filter: user-error: Some namespaces are in a bad state:
   error "Class not found: String" in funnyqt.xmltg-test;
   error "Class not found: String" in funnyqt.tg-test;
   error "Class not found: String" in funnyqt.coevo.tg;
   error "Class not found: String" in funnyqt.bidi
```

The `funnyqt.xmltg-test` is very small, looks good to me, and has no explicit reference to `String` at all, so I wonder what's causing the error.  And apparently, all these namespaces compile fine and their functions work as intended (at least with respect to what the tests cover).

This happens with `clj-refactor-20150706.1342` from MELPA and `[refactor-nrepl "1.2.0-SNAPSHOT"]` in my `~/.lein/profiles.clj`. I've updated from `[refactor-nrepl "1.1.0"]` only to check if the problem was gone with the newer release which it is not.

**Comment by expez** [comment]
If you do `M-x cljr-toggle-debug-mode` you'll expose the underlying error thrown by `tools.analyzer` when attempting to build an AST.  That might give you some clue as to what the problem is.

**Comment by tsdh** [comment]
Ah, I think the problem is due to [CLJ-1232](http://dev.clojure.org/jira/browse/CLJ-1232), and [this hunk](https://github.com/jgralab/funnyqt/commit/4b24bb395e698af05b989e516df43c7fa8a9d1c4#diff-0ccf9b57197c0e2a477df1e7bf37dba6L408) is the workaround.

**Comment by tsdh** [comment]
That has solved the issue with `String` but now I get `error in process filter: funnyqt.coevo.tg-test is in a bad state! Error: count not supported on this type: Symbol`.  I did `M-x cljr-toggle-debug-mode` but that doesn't seem to provide more information or at least I have no clue where the additional information goes.  Any help?

**Comment by expez** [comment]
The stracktrace should end up in your repl buffer (we delegate this to cider.  In the future this will re-use the functionality to display regular stracktraces).  If you can't see it there a last resort is to do `(setq nrepl-log-messages t)` which lets you inspect all the data going to and from the middleware stack.

`tools.analayzer` evaluates your code when it builds the AST, so when you're running `(count 'foo)` it's going to blow up.

**Comment by felipebueno** [comment]
I have the same problem and it happens 30 seconds after I start a repl so I had to uninstall clj-refactor :cry: 

The project is here:
https://github.com/sneerteam/sneer

and the error is:
```
  error in process filter: user-error: Some namespaces are in a bad state: error "Class not found: TupleBase" in sneer.tuple.transmitter-test;   error "Class not found: TupleBase" in sneer.admin
  error in process filter: Some namespaces are in a bad state: error "Class not found: TupleBase" in sneer.tuple.transmitter-test; error "Class not found: TupleBase" in sneer.admin
```

**Comment by expez** [comment]
> I have the same problem and it happens 30 seconds after I start a repl so I had to uninstall clj-refactor

This seems like an overreaction :p A lot of stuff will still work even though your project contains errors.

You're likely suffering from this too: http://dev.clojure.org/jira/browse/CLJ-1232 

The fix is to fully qualified any typehints referencing `TupleBase`.

**Comment by felipebueno** [comment]
Oh, sorry, I'm going to explain the issue better.

I had to uninstall because I use Midje auto-tests and, after that error, it doesn't work anymore.

**Comment by felipebueno** [comment]
I'll try that fix. Thanks :smiley: :+1:

**Comment by expez** [comment]
> Oh, sorry, I'm going to explain the issue better.

>I had to uninstall it because I use Midje auto-tests and, after that error, it doesn't work anymore.

I don't understand how one can affect the other.  All that `user-error` means is that `tools.analyzer` can't build a abstract syntax tree representing your project. And without that there are certain things we cannot do.

**Comment by felipebueno** [comment]
Here is a "before and after" the error:

![screenshot from 2015-08-13 12 35 24](https://cloud.githubusercontent.com/assets/241271/9254093/f103696c-41b7-11e5-8233-edd3f70ee56e.png)

![screenshot from 2015-08-13 12 35 33](https://cloud.githubusercontent.com/assets/241271/9254089/ee3dd32a-41b7-11e5-8f4a-1707ede17955.png)

And then I can't use Midje anymore.
