### ISSUE TITLE
cljr-clean-ns duplicates ns docstring as :doc metadata

### ISSUE THREAD

**Issue by tsdh** [clojure-emacs/clj-refactor.el#185]
When performing `cljr-clean-ns` it will duplicate the existing `ns` form docstring as additional `^{:doc "..."}` metadata. I think having the normal docstring after the namespace name is nicer to read than `:doc` metadata, but at least it shouldn't be duplicated. (clj-refactor.el version 1.1.0)

**Comment by expez** [comment]
We'll get `1.1.1` out the door later today.

**Comment by tsdh** [comment]
@expez See my message on the commit.  I have the feeling that this won't work with namespaces which have `:doc` metadata instead of a positional docstring.
