### ISSUE TITLE
could please make sure clj-refact can be installed from melpa-stable?

### ISSUE THREAD

**Issue by ruiyang** [clojure-emacs/clj-refactor.el#187]
cannot wait to try clj-refactor, but I got problems installing from stable.melpa.org.
The first issue is that it requrie edn.el v1.1.1, but only edn v1.0 available on melpa stable.
I submitted a issue to edn github, and the maintainer fixed it. Now I got peg-20130320.158 not available. I really want to try it, how could I install it easily from melpa stable?

If there is no easy way, I will have to switch to melpa, which not my preference, since I prefer to use relatively stable package.

**Comment by ruiyang** [comment]
peg seems to be required by edn.

**Comment by ruiyang** [comment]
duplicate with https://github.com/expez/edn.el/issues/4.

But I am not sure if we fixed peg issue, what will come next, hopefully not another missing dependency.

**Comment by expez** [comment]
This is in the works, I'll keep you updated.

**Comment by expez** [comment]
@ruiyang We'll cut another release of `clj-refactor` which will be available on melpa stable today or tomorrow.

**Comment by ruiyang** [comment]
successfully installed from melpa stable. Thanks a lot for the quick response! @expez
