### ISSUE TITLE
clj-refactor auto-evals ns declarations in current project

### ISSUE THREAD

**Issue by samaaron** [clojure-emacs/clj-refactor.el#189]
It seems that since `v1.1.0` when I connect to a project, the namespaces in my directory are all auto-evalled. This means that if they contain any side effects - they will be executed.

This is unfortunate when I connect to a project which is designed for side effects such as an Overtone project!!!

Is there a way to suppress the auto eval of namespaces? I'd prefer to be in control of which namespaces are evalled...

**Comment by benedekfazekas** [comment]
that is indeed true. we used to have a warning about this in the README but it seems it got removed in the latest readme/wiki clean up, still mentioned here: https://github.com/clojure-emacs/refactor-nrepl

> Warning: The clean -ns op dependes on tools.analyzer to determine which vars in a file are actually being used. This means the code is evaluated and any top-level occurrences of (launch-missiles) should be avoided.

so basically we (well, the library we use, tools.analyzer) need to eval the code to be able to build an AST we can work with. however, not all of our features need an AST: on our wiki (https://github.com/clojure-emacs/clj-refactor.el/wiki) all the AST dependent features are marked with `*` . the rest are implemented in vanilla emacs-lisp. on the other hand, the more advanced features (clean-ns, find-usages, rename symbols, extract fn) are all AST dependent.

you have basically two options I think:
- only use the emacs-lisp backed features: simply remove `refactor-nrepl` from your profiles.clj (if you use leiningen)
- at start up we eagerly build and cache the ASTs for all the namespaces in your project. you can opt out of this with setting `cljr-eagerly-build-asts-on-startup` to nil in your emacs config. that means we will only build AST for the namespace you are invoking an AST needing feature for. (note tho, that if you run find usages or rename symbol: that will again try to build ASTs for all namespaces in your project)

at the moment we don't have an option to exclude building ASTs for certain namespaces although we do exclude files not on your classpath for example.

hope this clarifies the situation, let us know what you think.

**Comment by expez** [comment]
Building ASTs take a long time so we eagerly start doing that as soon as we can so any refactorings depending on the ASTs will be snappy.  This has the unfortunate side-effect of evaluating all your code.

You can put `(setq cljr-eagerly-build-asts-on-startup nil)` in you config to disable this behavior eagerness.

Any refactorings depending on the AST will trigger side-effects, though.  Possibly twice, like with `rename-symbol` where we first build an AST (if eager building is off) to do the work, and then rebuild the the AST afterward to make sure we have an AST around for the most recent changes.

**Comment by expez** [comment]
Hot damn, you beat me to it by a few seconds @benedekfazekas! :)

**Comment by benedekfazekas** [comment]
:) this time.

we should probably put that warning back on the wiki, what do you think?

**Comment by samaaron** [comment]
Ah, that's painful!

That's a real shame as it essentially is a huge conflict with a core part of my Clojure usecase. Admittedly I'm probably a bit weird though.

It would be great if it asked me before going ahead and evalling my code and launching all the missiles! (In my case I had a cacophony of noise!!). I could then say no, and it could remember for the rest of that session...

**Comment by expez** [comment]
> It would be great if it asked me before going ahead and evalling my code and launching all the missiles! 

If you update that setting and additionally do `(setq cljr-auto-clean-ns nil)` then missiles won't be launched unless you call some refactoring.

As an aside, in the next version `clean-ns` won't require an AST to be built and thus be side-effect free.
