### ISSUE TITLE
'Enter' doesn't terminate refactoring it adds a new line

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#190]
OSX, prelude, clj-refactor 0.10.0-SNAPSHOT
When I introduce a let I get two points as expected. I then type the name I want and press return. Rather than terminating the refactoring 'session' I get a carriage return.

If I 'cancel' (e.g. Control-G) then the refactoring session is preserved and terminated so I can carry on editing as normal so I can workaround this for now.

**Comment by magnars** [comment]
Enter should be terminating it. What command is enter bound to when you're in that mode? (Find out with C-h k enter)

**Comment by yatesco** [comment]
Hi Magnar, I think my environment is messed up actually so this might be a red herring (Control-Shift-anything beeps for example).

However, here is the result:

RET runs the command newline, which is an interactive compiled Lisp                                                       
function in `simple.el'.                                                                                                  
                                                                                                                          
It is bound to RET.                                                                                                       
                                                                                                                          
(newline &optional ARG INTERACTIVE)                                                                                       
                                                                                                                          
Insert a newline, and move to left margin of the new line if it's blank.                                                  
If option `use-hard-newlines' is non-nil, the newline is marked with the                                                  
text-property `hard'.                                                                                                     
With ARG, insert that many newlines.                                                                                      
                                                                                                                          
If `electric-indent-mode' is enabled, this indents the final new line                                                     
that it adds, and reindents the preceding line.  To just insert                                                           
a newline, use M-x electric-indent-just-newline.                                                                          
                                                                                                                          
Calls `auto-fill-function' if the current column number is greater                                                        
than the value of `fill-column' and ARG is nil.                                                                           
A non-nil INTERACTIVE argument means to run the `post-self-insert-hook'.                                                  
                                                                           
> On 13 Jul 2015, at 13:31, Magnar Sveen <notifications@github.com> wrote:
> 
> Enter should be terminating it. What command is enter bound to when you're in that mode? (Find out with C-h k enter)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/clojure-emacs/clj-refactor.el/issues/190#issuecomment-120910607>.
>

**Comment by magnars** [comment]
So, both of your cursors work properly (they mirror what you write) - this tells me that `multiple-cursors-mode` is active. Yet, the keybinding that is defined in that mode is not active? (defined [here](https://github.com/magnars/multiple-cursors.el/blob/master/multiple-cursors-core.el#L432)). That is really weird. Is `C-g` bound to `mc/keyboard-quit`?

Did you remember to enter the editing mode before checking the keybinding?

**Comment by yatesco** [comment]
No I didn't,  I will check first thing tomorrow.

**Comment by expez** [comment]
@yatesco ping :)

**Comment by yatesco** [comment]
Apologies - this completely fell off my radar!

Within the editing mode the enter key is still mapped to 'newline'. In additional, I get a prompt asking if I want to describe key for all the cursors. Below is the result go C-h k and enter:

RET runs the command newline, which is an interactive compiled Lisp                                                                           
function in `simple.el'.                                                                                                                      
                                                                                                                                              
It is bound to RET.                                                                                                                           
                                                                                                                                              
(newline &optional ARG INTERACTIVE)                                                                                                           
                                                                                                                                              
Insert a newline, and move to left margin of the new line if it's blank.                                                                      
If option `use-hard-newlines' is non-nil, the newline is marked with the                                                                      
text-property `hard'.                                                                                                                         
With ARG, insert that many newlines.                                                                                                          
                                                                                                                                              
If `electric-indent-mode' is enabled, this indents the final new line                                                                         
that it adds, and reindents the preceding line.  To just insert                                                                               
a newline, use M-x electric-indent-just-newline.                                                                                              
                                                                                                                                              
Calls `auto-fill-function' if the current column number is greater                                                                            
than the value of `fill-column' and ARG is nil.                                                                                               
A non-nil INTERACTIVE argument means to run the `post-self-insert-hook'.

**Comment by magnars** [comment]
Ok, so for some reason the multiple-cursors keymap isn't in effect, or at least the `<enter>` keybinding is overruled by something else. Why that happens with your setup is beyond me.

 Is `C-g` bound to `mc/keyboard-quit`?

**Comment by yatesco** [comment]
It is indeed.

**Comment by yatesco** [comment]
There is something weird going on in my combination of terminal/zsh settings/emacs version/prelude so by all means attribute this to a local issue and don’t waste time on it. If other people have reported this then ok, but if it is just me then based on other things I have seen locally; close this and move on :-).

**Comment by magnars** [comment]
Ah, you're using emacs inside the terminal? That is a breeding ground for weird keyboard bugs. Yes, indeed, that solves it. Look again:

```el
(define-key mc/keymap (kbd "<return>") 'multiple-cursors-mode)
```

This says `<return>` which does not exist in the terminal. There is only `RET` in the terminal. I have not bound to `RET` because I want people to be able to insert newlines with `C-m` - which in the weird world of terminals is the same as `RET`. 

You can do:

```el
(define-key mc/keymap (kbd "RET") 'multiple-cursors-mode)
```

in your own settings, and if you want to insert newlines, use `C-j` instead. :)

**Comment by yatesco** [comment]
I see - thanks for the time Magnar. You are another example of why the Clojure community rocks!

**Comment by magnars** [comment]
No worries. Thanks for the kind words. :)
