### ISSUE TITLE
.cljc and .cljs aren't supported

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#191]
OSX, prelude, clj-refactor 0.10.0-SNAPSHOT
I can introduce a let in .cljc but if I try and refactor and remove that let I get told only clj files are supported.

**Comment by expez** [comment]
The middleware told you the truth, it hasn't learned how to handle anything but `.clj` files, yet.

**Comment by yatesco** [comment]
But it did let me introduce the let in the .cljc file. Are you saying that the support is per-refactoring? I assumed it was global...

**Comment by expez** [comment]
Some refactorings don't need to know about `clj` and `cljs` and `cljc`, like `cljr-introduce-let` or all the threading related refactorings.  I think it would be a shame to deny you all refactorings just because a few doesn't work!

**Comment by yatesco** [comment]
Oh, I agree completely - I am loving cli-refactor! It was my mistaken assumption that if one worked they would all work (as I assumed it was simply using lexical analysis for example).

Is there anyway I can find out where a given refactor will work?

And, to repeat, my 5 minute experimentation with cli-refactor is making my day! Thanks a bunch.

**Comment by expez** [comment]
It's somewhat hard to see but in the [list of refactorings](https://github.com/clojure-emacs/clj-refactor.el/wiki) those refactorings that use the middleware are marked with a `*`.

Of these I think the only one that will work is `add-missing-libspec`

**Comment by yatesco** [comment]
OK - thanks again.

**Comment by piotr-yuxuan** [comment]
> The middleware told you the truth, it hasn't learned how to handle anything but .clj files, yet.
> — @expez

Perhaps I'm wrong but methinks things have changed since last year:
https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl 

I've been using clj-refactor.el with pure Clojure and have enjoyed it! However, I'm now writing ClojureScript and it would be really great to have the same editing power :-)

**Comment by benedekfazekas** [comment]
Although figwheel can be used with cider nicely nowadays but unfortunately this does not mean that clj-refactor's middleware depending features can work on cljs files now :/

Please note that as it is stated in the thread above *some* refactorings which don't need the middleware at all will still work on cljs files. In fact many of these got migrated to clojure-mode itself lately. Please have a look on the wiki where all the refactorings are listed to see which refactoring falls in which category.

**Comment by piotr-yuxuan** [comment]
Thanks for your quick feedback.

I'm aware of refactorings without * are still available, but for example `rl` would be awesome to have ^^

**Comment by benedekfazekas** [comment]
this is the blocker essentially: https://github.com/clojure/tools.analyzer.js#outdated

there is no usable analyzer for cljs I know of at the moment. We could run our own stripped down analyzer only doing what we need for clj-refactor but this feels like a big undertaking for me atm -- assuming same true for @expez.

**Comment by wnr** [comment]
In our project, the bulk of the code lies in cljc files (but without any reader conditionals). Would it be possible to enable these features for such files?

**Comment by expez** [comment]
@wnr Yeah, if it can be safely treated as a clj file then you should be able to modify the software to work anyway.
