### ISSUE TITLE
Extract function on entire body fails

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#200]
It does not extract locals. Ie

```
(defn test [game]
  (map :face (remove :matched? game)))
```

If you try to extract `(remove :matched? game)`, it works as expected. 

If you try to extract `(map :face (remove :matched? game))`, then `game` is not considered a local, and is not included in the signature of the new function.

**Comment by expez** [comment]
It works if point is inside the sexp, but fails if it's on the `(`

**Comment by expez** [comment]
well, the tests were failing locally (same as for `change-functionsignature`), but since they pass on travis that's fine :p
