### ISSUE TITLE
Request: from-example on a namespace qualified symbol

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#202]
In the following example, if I call `fe` on `db/something`, I get a new `defn` whose name is `db/something`. It would be nice if, instead, clj-refactor created a `defn` called `something` on the `database.clj` file.

    (ns website.core
      (:require [website.database :as db]))

    (db/something 10)

**Comment by expez** [comment]
We've discussed this as a cool addition, but we also agreed that this pattern of usage is pretty rare.  I'd guess only a few % of the calls to `fe` would trigger this code path.

Pull request welcome! :)
