### ISSUE TITLE
Get rid of 'error in process filter'

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#204]
This happens frequently and makes it look like we have no idea what we're doing.  IIRC this message is displayed when `nrepl` sees the `:err` key in the return value.

**Comment by expez** [comment]
`cljr-debug-mode` seems to have been broken by recent commits (to cider?). Instead of getting a stacktrace in the repl buffer, like before, there's now this:

`error in process filter: cljr--maybe-rethrow-error: Unclosed character class near index 9 ...` in the `*messages*` buffer.

**Comment by bbatsov** [comment]
This happens when there's an unhandled error in the process filter (CIDER's connection to nREPL so to speak). It has nothing to do with nREPL messages and is likely caused by some actual error in `clj-refactor`'s code.

**Comment by bbatsov** [comment]
See http://www.gnu.org/software/emacs/manual/html_node/elisp/Filter-Functions.html

**Comment by expez** [comment]
```
(defun cljr--call-middleware-async (request &optional callback)
  (nrepl-send-request request callback))
```

with a `callback` which uses `cljr--maybe-rethrow-error` is the source of this.

**Comment by expez** [comment]
Closing this as impossible after wrestling with this myself and asking other gurus for help.
