### ISSUE TITLE
I got the error when using `cn`.

### ISSUE THREAD

**Issue by vmfhrmfoaj** [clojure-emacs/clj-refactor.el#207]
I use `cider-nrepl` "0.10.0-SNAPSHOT", `refactor-nrepl` "1.2.0-SNAPSHOT"

source file:
```clojure
(ns adb.help
  (:refer-clojure :exclude [range])
  (:import (com.android.ddmlib RawImage) ;; work fine remove the parenthesis (i.e. (com.android.ddmlib RawImage) -> com.android.ddmlib.RawImage)
           (java.awt.image     BufferedImage)))

(def ^:private range (memoize (comp doall clojure.core/range)))

(def ^:private n-cpu (.. Runtime getRuntime availableProcessors))

(defn raw->img!
  "Convert, `ddmlib.RawImage' -> `awt.image.BufferedImage'"
  [raw img]
  (let [w (.-width  raw)
        h (.-height raw)
        byte-per-pixel (/ (.-bpp raw) 8)]
    (->> (range 0 (* w h) (/ (* w h) n-cpu))
         ((juxt identity
                (comp #(concat % (list (* w h)))
                      (partial drop 1))))
         (apply interleave)
         (partition 2)
         (pmap (fn [[s e]]
                 (let [px (rem s w)
                       py (/   s w)
                       pw w
                       ph (/ (- e s) w)
                       rgb-array (->> (range s e)
                                      (map #(.getARGB ^RawImage raw (* % byte-per-pixel)))
                                      int-array)]
                   (.setRGB ^BufferedImage img, px py, pw ph, rgb-array, 0, w))))
         dorun)
    img))

(defn raw->img
  "Convert, `ddmlib.RawImage' -> `awt.image.BufferedImage'"
  [raw]
  (let [img (BufferedImage. (.-width  raw)
                            (.-height raw)
                            BufferedImage/TYPE_INT_ARGB)]
    (raw->img! raw img)))
```

>java.lang.NullPointerException: null
> at clojure.lang.Symbol.intern (Symbol.java:60)
>    clojure.core$symbol.invoke (core.clj:546)
>    refactor_nrepl.ns.rebuild$create_import_form.invoke (rebuild.clj:184)
>    refactor_nrepl.ns.rebuild$create_import_components$iter__15630__15634$fn__15635.invoke (rebuild.clj:189)
>    clojure.lang.LazySeq.sval (LazySeq.java:40)
>    clojure.lang.LazySeq.seq (LazySeq.java:49)
>    clojure.lang.RT.seq (RT.java:484)
>    clojure.core$seq.invoke (core.clj:133)
>    clojure.core$map$fn__4245.invoke (core.clj:2551)
>    clojure.lang.LazySeq.sval (LazySeq.java:40)
>    clojure.lang.LazySeq.seq (LazySeq.java:49)
>    clojure.lang.RT.seq (RT.java:484)
>    clojure.core$seq.invoke (core.clj:133)
>    clojure.core$sort.invoke (core.clj:2827)
>    refactor_nrepl.ns.rebuild$sort_imports.invoke (rebuild.clj:194)
>    refactor_nrepl.ns.rebuild$build_import_form.invoke (rebuild.clj:202)
>    refactor_nrepl.ns.rebuild$rebuild_ns_form.invoke (rebuild.clj:235)
>    refactor_nrepl.ns.clean_ns$clean_ns.invoke (clean_ns.clj:38)
>    refactor_nrepl.middleware$clean_ns_reply.invoke (middleware.clj:73)
>    refactor_nrepl.middleware$wrap_refactor$fn__16072.invoke (middleware.clj:120)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    cider.nrepl.middleware.inspect$wrap_inspect$fn__3730.invoke (inspect.clj:108)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    clojure.tools.nrepl.middleware.pr_values$pr_values$fn__977.invoke (pr_values.clj:17)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    cider.nrepl.middleware.complete$wrap_complete$fn__3423.invoke (complete.clj:52)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    cider.nrepl.middleware.undef$wrap_undef$fn__7900.invoke (undef.clj:30)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    cider.nrepl.middleware.debug$wrap_debug$fn__3892.invoke (debug.clj:352)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    cider.nrepl.middleware.test$wrap_test$fn__7605.invoke (test.clj:201)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    clojure.tools.nrepl.middleware.session$session$fn__1106.invoke (session.clj:192)
>    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__797.invoke (middleware.clj:24)
>    clojure.tools.nrepl.server$handle_STAR_.invoke (server.clj:19)
>    clojure.tools.nrepl.server$handle$fn__1170.invoke (server.clj:28)
>    clojure.core$binding_conveyor_fn$fn__4145.invoke (core.clj:1910)
>    clojure.lang.AFn.call (AFn.java:18)
>    java.util.concurrent.FutureTask.run (FutureTask.java:266)
>    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
>    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
>    java.lang.Thread.run (Thread.java:745)

**Comment by expez** [comment]
Fixed in https://github.com/clojure-emacs/refactor-nrepl/commit/7eb38e1ac45121835a27dc2a57ce5e3f06e42aad (messed up the issue reference :/)

I've also deployed a new snapshot to clojars. 

Thanks for the excellent bugreport @vmfhrmfoaj!

**Comment by vmfhrmfoaj** [comment]
Thank you for quick response. :+1:
