### ISSUE TITLE
cljr-stop-referring fail on ns-declaration with unexpected newline

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/clj-refactor.el#208]
When the namespace declaration contains a newline aftere the :require keyword, in a situation where it would normally work, I get the following message instead:

- /Place cursor on the namespace whose vars you want to stop referring to./

I'll take a look at this myself a bit later.

**Comment by expez** [comment]
Great!

It's actually always annoyed me slightly that I have to move point to use this refactoring and not just get a completing read of namespaces referring stuff.  You might consider re-writing this in order to solve this bug :)

**Comment by expez** [comment]
@luxbock Ping :)

**Comment by luxbock** [comment]
The original issue was a rather easy fix. I'll take at the thing you mentioned as well, but before I do I started wondering how it should actually work in practice.

The way it works right now is that the operation gets called on the namespace that you want to stop referring, and it acts on all of the referred symbols from that namespace. Are you suggesting that the user should be able to call it on a symbol that's currently being referred to, in anywhere in the file? If that's the case, I wonder if there might be confusion for the user for why all the other symbols from the namespace just got the treatment instead of just the one that they called the operation on?

**Comment by expez** [comment]
I thought maybe you'd get a prompt of all the namespaces with a `:refer [..]` clause and you'd get to pick among them.

**Comment by expez** [comment]
@luxbock any progress on this?

If it's too much trouble, the easy fix is much better than an open issue! :)

**Comment by luxbock** [comment]
I think handling the case of nested ns-declarations in Elisp is too complicated for me. I think opening up the ns-parser via the middleware would be much nicer, as we discussed on IRC before. I wouldn't mind writing this in Clojure myself, but the fact that the tests are (were?) failing from beforehand makes me a bit hesitant to move stuff around, which I think one would definitely want to do in `refactor-nrepl.ns.ns-parser`.
