### ISSUE TITLE
Odd insert on add-missing

### ISSUE THREAD

**Issue by philjackson** [clojure-emacs/clj-refactor.el#209]
Hey,

I've not attempted to debug this yet. Thought I'd post here first in case it's already found/fixed somewhere else. If not, I'll put some time into a fix - any hints welcome.

Quite often I get the following issue when adding a missing libspec:

Given:

    (ns connect-engine.routes.event-test
      (:require [buddy.hashers :as hashers]
                [clojure.java.jdbc :as jdbc]
                [clojure.test :refer :all]
                [connect-engine
                 [authentication :as auth]
                 [db :as db]
                 [json :as json]
                 [db-helpers :refer [with-empty-db-connection]]
                 [handler :refer [app]]
                 [test-helpers :as helpers :refer [example-event-type! with-db example-race!]]
                 [util :refer [map->]]]
                [connect-engine.routes.event :refer :all]
                [ring.mock.request :as mock]))

I put the cursor on a missing function, execute add missing libspec and end up with this:

    (ns ^{:clojure.test/each-fixtures (#object[connect_engine.routes.event_test$eval40098$fn__40099 0x22b0f966 "connect_engine.routes.event_test$eval40098$fn__40099@22b0f966"])}
      connect-engine.routes.event-test
      (:require [buddy.hashers :as hashers]
                [clojure.java.jdbc :as jdbc]
                [clojure.test :refer :all]
                [connect-engine
                 [authentication :as auth]
                 [db :as db]
                 [db-helpers :refer [with-empty-db-connection]]
                 [handler :refer [app]]
                 [json :as json]
                 [test-helpers :as helpers :refer [example-event-type! example-race! example-runner! with-db]]
                 [util :refer [map->]]]
                [ring.mock.request :as mock]))

**Comment by expez** [comment]
LOL!

This is very bad!  

Whenever there's metadata attached to the ns we print it in the ns form.  This is to support people putting `doc` and `author` metadata etc on the ns form.  There's a list of stuff to strip, including metadata added by the compiler, but we should probably exclude metadata added by `core.test` too!

Actually, what we really should do is read that metadata map on its so we only get the stuff actually appearing the file and not all the stuff that was added programmatically.

**Comment by expez** [comment]
New snapshot deployed.  Thanks for the bug report @philjackson!

**Comment by philjackson** [comment]
Thank you, @expez!
