### ISSUE TITLE
Can’t use with code that relies on protocols and stable records?

### ISSUE THREAD

**Issue by brunchboy** [clojure-emacs/clj-refactor.el#212]
This may simply be an issue with me hoping for too much, but I could not find a more informal mailing list on which to discuss this, so I will open an issue here, in the hopes of at least being educated.

I would love to be able to use this great tool, but as soon as I enable it within Emacs, my project [Afterglow](https://github.com/brunchboy/afterglow) starts blowing up, because I have preconditions in various functions that check that their arguments satisfy protocols or are particular classes, and it seems that clj-refactor is reloading namespaces to the extent that the protocols and records/classes are being redefined, and no longer match the versions that were compiled into the preconditions.

Is this a known issue, are there any workarounds or ways of dealing with it?

**Comment by expez** [comment]
Most likely you're a victim of [CLJ-1232](http://dev.clojure.org/jira/browse/CLJ-1232).  Try to fully qualify the stuff that's blowing up and see if that helps.

**Comment by expez** [comment]
If this isn't it, I'd love a minimal example of breakage to solve this.

**Comment by brunchboy** [comment]
Hmm, interesting. I will try that but I will be surprised if it helps because I am getting a fundamentally different kind of error than the one seen there. The types are known (and imported) in both namespaces. And they classes (names) look the same when you print them out in the REPL, but they are not considered the same. I will try to find some time to put together a minimal example.

**Comment by expez** [comment]
I'm not sure what exactly broke for you, but trying to run `find-usages` on your project made that op blow up pretty hard.

[this file](https://github.com/brunchboy/afterglow/blob/master/resources/templates/fixture-definition.clj) is on the classpath and has the file ending `.clj`.  We try to read this as a regular clojure file, when looking for macro definitions in the macro and that doesn't work out.

**Comment by brunchboy** [comment]
Ah, interesting. I can address *that* issue, anyway: I will rename that file to end in `.clj.template` and see if that helps anything else. I am hoping to help investigate this further this weekend anyway.

**Comment by brunchboy** [comment]
All right, I just pushed a change which renames that file so it will no longer confuse `find-usages`, for what it's worth! If I have a chance to put together a more minimal example that triggers the problem, I will let you know. Thanks so much for digging into this already!

**Comment by brunchboy** [comment]
OK, since you have cloned out the project anyway, here is how to get the crash I was reporting:

With `clj-refactor` hooked up, use `cider-connect` on a Clojure file in the Afterglow project (I usually just start with `project.clj`). That will put you in the `afterglow.examples` namespace.

Try to invoke `(use-sample-show)`. This will fail:

```
1. Unhandled java.lang.AssertionError
   Assert failed: (satisfies? rhythm/IMetronome base-metronome)

                          REPL:  292  afterglow.show/show
                   RestFn.java:  457  clojure.lang.RestFn/invoke
                          REPL:   48  afterglow.examples/use-sample-show/fn
                     Atom.java:   37  clojure.lang.Atom/swap
                      core.clj: 2238  clojure.core/swap!
                          REPL:   44  afterglow.examples/use-sample-show
                   RestFn.java:  397  clojure.lang.RestFn/invoke
                          REPL:    1  afterglow.examples/eval46870
```

If, however, you do this without `clj-refactor` being enabled, it works fine.

If I can come up with an isolated, minimal example that does not require my project, I will post that too. In this case, what seems to be happening is that my `IMetronome` protocol is being redefined between when the file was originally loaded, and when we try calling `(use-sample-show)`, even though it is protected within a `defonce` form.

**Comment by expez** [comment]
We rely on `tools.analyzer.jvm` to build an AST to do work on.  Unfortunately `t.a` has to evaluate your code to do its thing (you can only get so far with static analysis on a language like clojure).  If you've narrowed this down to a `defonce` form then I'm guessing it's getting evaluated more often than you'd like.

I've been listening to [resurrection](https://www.mixcloud.com/brunchboy/resurrection/) while coding this morning.  Great stuff! :+1:

**Comment by brunchboy** [comment]
Yes, I believe the problem is that my `defprotocols` and `defrecords` are getting evaluated too many times, which causes them to become incompatible with references being held by other namespaces, showing up as precondition failures. How do people deal with this? I am thinking that I will just need to keep `clj-refactor` turned off except when I decide to embark on a refactoring binge, during which I do not expect to be able to run or test my code.

> [I love that you found Resurrection! :grinning: I have been spending too much of my time working on Afterglow to mix lately, and I miss it. I will have to force myself to switch modes for a bit soon. A friend is asking for music at a party next month, that will help refocus me.]

**Comment by expez** [comment]
> Yes, I believe the problem is that my defprotocols and defrecords are getting evaluated too many times, which causes them to become incompatible with references being held by other namespaces, showing up as precondition failures. 

I don't think the `satisfies?` predicate is affected by re-evaluation.  

In any event, I'd still like to see if we can boil this down to a minimal example so we can document any limitations.

**Comment by brunchboy** [comment]
Well, it definitely seems to be affected by re-evaluation in this case. Here is a pretty minimal set of namespaces with which I have been able to reproduce the problem. I started with an empty project via `lein new test`. I wasn't able to reproduce the problem with just two namespaces (though I did not try too hard), but as soon as I introduced the third, I managed to recreate the exact same issue.

First, a namespace to introduce the protocol and provide an implementation, like my `rhythm.clj`:

```clojure
(ns test.proto)

(defonce
  ^{:private true
    :doc "Protect protocols against namespace reloads."}
  _PROTOCOLS_
  (defprotocol ISimple
  "Testing reloading issues"
  (simply-respond [this] "Return something")))

(defrecord Simple [v]
  ISimple
  (simply-respond [this]
    v))

(defn make-simple [v]
  (Simple. v))
```

Then, a namespace to rely on that protocol and verify it:

```clojure
(ns test.third
  (:require [test.proto :as proto]))

(defn check-simple
  "Check that argument satisfies ISimple"
  [x]
  {:pre [(satisfies? proto/ISimple x)]}
  (println (proto/simply-respond x) "Hello, World!"))
```

And, finally, a namespace which constructs something which is supposed to satisfy the protocol, and passes it to the namespace which checks that:

```clojure
(ns test.core
  (:require [test.proto :as proto]
            [test.third :as third]))

(def impl (proto/make-simple "From Core"))

(defn perform-test
  []
  (third/check-simple impl))
```

This all works fine as long as I don't have Emacs configured to load `clj-refactor`. I launch Emacs, find the `project.clj` in my new `test` project, run `cider-jack-in` and try it out:

```clojure
; CIDER 0.9.1 (Java 1.8.0_51, Clojure 1.6.0, nREPL 0.2.10)
user> (require 'test.core)
; -> nil
user> (test.core/perform-test)
; From Core Hello, World!
; -> nil
user> (in-ns 'test.core)
; -> #<Namespace test.core>
test.core> (def impl (proto/make-simple "Trying again"))
; -> #'test.core/impl
test.core> (perform-test)
; Trying again Hello, World!
; -> nil
```

But as soon as uncomment the lines which activate `clj-refactor`, quit and restart Emacs, and try that again:

```clojure
; CIDER 0.9.1 (Java 1.8.0_51, Clojure 1.6.0, nREPL 0.2.10)
user> (require 'test.core)
; -> nil
user> (test.core/perform-test)
; From Core Hello, World!
; -> nil
user> (in-ns 'test.core)
; -> #<Namespace test.core>
test.core> (def impl (proto/make-simple "Trying again"))
; -> #'test.core/impl
test.core> (perform-test)
; -> AssertionError Assert failed: (satisfies? proto/ISimple x)  test.third/check-simple (form-init7341883379295106263.clj:4)

1. Unhandled java.lang.AssertionError
   Assert failed: (satisfies? proto/ISimple x)

                          REPL:    4  test.third/check-simple
                          REPL:    9  test.core/perform-test
                          REPL:    1  user/eval15454
```

**Comment by expez** [comment]
TIL more about how protocols work on the jvm.

One pretty easy fix is to remove the `defonce`, wrapping your protocols, and hit`C-c C-x`, bound to `cider-refresh,` to use `tools.namespace` to reload everything back into the repl in dependency order after calling the refactorings that evaluate code.

**Comment by brunchboy** [comment]
Unfortunately, when there are real-time background threads communicating with DMX and MIDI interfaces at 30ms intervals, I just can’t go reloading some of my namespaces. And those threads communicate via the protocols, which is why they can’t be re-evaluated. Hmm, I guess I just can’t use a system like clj-refactor which reloads namespaces frequently and unpredictably. (These crashes happen even when I have not engaged in any refactoring.)

Hmm, maybe if there were a way to turn it completely off and back on via key bindings, I could leave it off most of the time, then make sure I have all light shows shut down before turning it on, doing some refactoring, and turning it back off before starting a show; that could save significant time compared to having to totally restart Emacs and the REPL. But my use case may be too far outside the norm to be worth worrying about.

**Comment by expez** [comment]
> It seems I just can’t use a system like clj-refactor which reloads namespaces frequently and unpredictably. (These crashes happen even when I have not engaged in any refactoring.)

This shouldn't be the case.  We build ASTs in three situation:

1. On startup we build everything, controlled by the variable `cljr-eagerly-build-asts-on-startup` 2. When you issue a command, requiring an AST, we build ASTs for the files that have changed.
3. After e.g. `cljr-rename-symbol` we rebuild the ASTs.

In other words, by doing `(setq cljr-eagerly-build-asts-on-startup nil)` and not using `clj-refactor` you should see no unpredictable breakage.

**Comment by brunchboy** [comment]
Ah! I was unaware of `cljr-eagerly-build-asts-on-startup` and don’t see it documented anywhere in a quick scan of the project home page or wiki. It might be worth adding a quick section on how to cope with namespaces that are not amenable to reloading, with a definitive list of when these AST builds might happen.

I may give your suggestion a try. I assume there are some commands which will build an AST of the whole project, though, like perhaps `find-usages`? My one remaining snag would be how to be able to keep my protocols protected by `defonce` so I can reload those files myself when I am working on them without breaking compatibility with existing threads, and still have them survive AST builds.

Out of curiosity, what is it about the way that clj-refactor loads the file when building its AST which causes the `defonce` to be ignored?

**Comment by expez** [comment]
> I was unaware of cljr-eagerly-build-asts-on-startup and don’t see it documented anywhere in a quick scan of the project home page or wiki. 

Emacs aims to be self-documenting so if you do `M-x customize-group <RET> cljr <RET>` you'll see all the available settings and their docstrings.

> I assume there are some commands which will build an AST of the whole project,

`find-usages`, `rename-symbol`, `inline-symbol`, `remove-let` and `remove-debug-fns`

> Out of curiosity, what is it about the way that clj-refactor loads the file when building its AST which causes the defonce to be ignored?

This is done by `tools.analyzer`, it has to eval the code in order to build an AST.  As part of doing that it evaluates the contents of the `defonce`.  We could do this in a tooling session, but spinning up an additional jvm is kind of annoying and it's never been a problem before.

> My one remaining snag would be how to be able to keep my protocols protected by defonce so I can reload those files myself when I am working on them without breaking compatibility with existing threads, and still have them survive AST builds.

This seems impossible given how protocols are implemented, short of introducing another jvm just for tooling.  Your project is somewhat exceptional in that it can't easily by reloaded wholesale during development.

The good news is you can keep using most of clj-refactor now that you're aware of the few troublemakers :)

**Comment by brunchboy** [comment]
Ah, yes, the Emacs customize interface, so lovingly optimized for a text terminal over a 2400 bps modem. :stuck_out_tongue_winking_eye:  Your Wiki home page even mentioned it, but I find it so painful to look at (especially since you need to expand every single option to see what its default value is) that my eyes skated right over that, looking for some nice markdown-generated HTML. Sorry!

Thanks for the list of "troublemakers". Armed with all this new knowledge, I can get back to experimenting with clj-resource, so I shall close this issue.
