### ISSUE TITLE
Display locals in scope at point in the mini-buffer

### ISSUE THREAD

**Issue by luxbock** [clojure-emacs/clj-refactor.el#213]
When using `extract-function` to chop down a larger function into smaller parts, before executing, it would be handy to know what the current locals in scope at point are. Would a feature where you can toggle the display of the local symbols in the mode-line be useful to anyone else?

**Comment by benedekfazekas** [comment]
sounds interesting. in fact you could show both the available locals in scope and the ones used. what would be the practical use btw? what is the workflow you have in mind?

**Comment by luxbock** [comment]
When I design functions top-down I often find it easier to write the whole thing out as one giant blob which I then break down for easier readability, and `extract-function` and `promote-function` are handling the job spectacularly. I've noticed though that when I'm deep down the parens trying to decide where to chop things off, I spend a lot of my mental energy keeping track of which function parameters and locals are currently in scope, so it just occured to me why not let the computer handle that for me instead.

**Comment by benedekfazekas** [comment]
fair enough. do you want to give it a go?

**Comment by luxbock** [comment]
Yeah sure, although I'm a bit uncertain on how to implement this on the Emacs side.

Displaying the locals at the mini-buffer on a keypress would be easy enough, but from usability point of view it would be the best if the information was automatically updated as I move around the buffer, without having to invoke it separately.

**Comment by benedekfazekas** [comment]
hm.. @Malabarba did a really nice thing for the debugger lately when debug info shows up in the buffer itself on a layer (?!) demoed here: http://endlessparentheses.com/debugger-improvements-in-cider-0-10-0.html

no idea how to do this but surely you will get help in the cider or refact-nrepl gitter room when you get there

**Comment by expez** [comment]
Locals automatically being displayed in the minibuffer will be competing for attention with what's provided by eldoc, by cider, making both useless.  This is not something I'm interested in.

We can display the locals while prompting the user for the function name, as we've already gathered the locals at that point.  That way the user can choose to abort if the resultant function would take 7 parameters.

**Comment by Malabarba** [comment]
Yes, cider has a new file with some functions for creating overlays. You mind find then helpful if you go down that route. 

That said, it won't help with your question of how to implement this. The best place to start is just a command that displays this info on demand. 

Then, if you want to display it permanently in the minibuffer, you should hook into eldoc, which is the minor responsible for this kind of thing. Cider uses it to constantly display function signatures on the minibuffer, so you can look there for tips on how to implement that.
