### ISSUE TITLE
Improve discoverability of refactorings

### ISSUE THREAD

**Issue by gregsexton** [clojure-emacs/clj-refactor.el#214]
Hi,

For some of the refactorings I use less frequently I often forget their mnemonics. I hacked this together a while back to help with this. It makes use of the (newly extracted) magit popup functionality to put refactorings on a single prefix and then a single key press from there, all while displaying my options.

Just wanted to share the code below and possibly open a discussion as to how you can make refactorings more discoverable.

Maybe you're happy to take a dependency on magit-popup? In which case feel free to steal as much or as little of this as you like. :) I think I left out a few of the refactorings and some of the key choices are definitely questionable.

      (magit-define-popup clj-refactor-ns-popup
        "some doc"
        :actions '((?i "Add import to ns" cljr-add-import-to-ns)
                   (?m "Add missing libspec" cljr-add-missing-libspec)
                   (?d "Add project dependency" cljr-add-project-dependency)
                   (?r "Add require to ns" cljr-add-require-to-ns)
                   (?u "Add use to ns" cljr-add-use-to-ns)
                   (?c "Clean ns" cljr-clean-ns)
                   (?h "Hotload dependency" cljr-hotload-dependency)
                   (?p "Project clean" cljr-project-clean)
                   (?n "Remove unused requires" cljr-remove-unused-requires)
                   (?e "Replace use" cljr-replace-use)
                   (?s "Sort ns" cljr-sort-ns)
                   (?o "Sort project dependencies" cljr-sort-project-dependencies)
                   (?t "Stop referring" cljr-stop-referring)))

      (magit-define-popup clj-refactor-code-popup
        "some doc"
        :actions '((?F "Find usages" cljr-find-usages)
                   (?c "Cycle coll" cljr-cycle-coll)
                   (?i "Cycle if" cljr-cycle-if)
                   (?p "Cycle privacy" cljr-cycle-privacy)
                   (?s "Cycle stringlike" cljr-cycle-stringlike)
                   (?d "Destructure keys" cljr-destructure-keys)
                   (?e "Extract function" cljr-extract-function)
                   (?x "Create fn from example" cljr-create-fn-from-example)
                   (?E "Expand let" cljr-expand-let)
                   (?L "Introduce let" cljr-introduce-let)
                   (?m "Move form" cljr-move-form)
                   (?M "Move to let" cljr-move-to-let)
                   (?n "Promote function" cljr-promote-function)
                   (?X "Remove debug fns" cljr-remove-debug-fns)
                   (?R "Rename file" cljr-rename-file)
                   (?k "Remove let" cljr-remove-let)
                   (?r "Rename symbol" cljr-rename-symbol)
                   (?f "Thread first all" cljr-thread-first-all)
                   (?l "Thread last all" cljr-thread-last-all)
                   (?U "Unwind all" cljr-unwind-all)
                   (?u "Unwind" cljr-unwind)
                   (?D "Add declaration" cljr-add-declaration)))

**Comment by expez** [comment]
There's already [clj-helm](https://github.com/philjackson/cljr-helm) which is pretty similar.  

Personally I use [helm-descbinds](https://github.com/emacs-helm/helm-descbinds), which let's me do `C-c C-m C-h` and get a popup of all available functions at the cljr prefix.  

There's also `C-c C-m ?`, bound to `cljr-describe-refactoring`, which displays the wiki documentation in an emacs buffer, to remind you of what some refactoring does without losing context.

What do you guys think @magnars @benedekfazekas?  This question keeps coming up, even though I feel like we're covered.

**Comment by magnars** [comment]
I quite like the magit popups, at least. I guess it wouldn't hurt to have something built-in that does this.

**Comment by gregsexton** [comment]
@expez, I wasn't aware of clj-helm. I'm personally not a helm fan so this doesn't solve the problem for me, but it seems worth linking to in the wiki for others?

Maybe interfaces to the refactorings could be optional additional packages that people could choose from? I see you have the var `cljr--all-helpers` that contains all the info someone would need to construct an interface. Maybe you could commit to exposing this data structure in a stable form?

Having said this, I'm not sure how it would work with the magit popups. There are too many functions to comfortably fit on a single popup, which is why I didn't use this var originally.

**Comment by expez** [comment]
> but it seems worth linking to in the wiki for others

Absolutely!

> Maybe you could commit to exposing this data structure in a stable form?

`cljr--all-helpers` is what's used by `cljr-helm`, so we already treat this as part of the outward API.

**Comment by benedekfazekas** [comment]
I guess we could extend `cljr--all-helpers` with a third value in the second list which could denote the 'type' of the refactoring. something along the lines of the divisions proposed above. what these divisions would be is actually an interesting question.

**Comment by benedekfazekas** [comment]
please see #220 as a proposal. couple of things up for discussion:
- the command types: I do think controlling the grouping in `clj-refactor` is a good idea but I might not get the grouping right
- if we should add the `magit-popup` code to clj-refactor (I would prefer it in a separate project, although `magit-popup` would not introduce too many new deps)

**Comment by expez** [comment]
The magit popup lib is a good candidate for extraction out of magit and to be made available for general consumption.  In fact, we've requested as much once before.  IIRC that request was well-received but at the time a complete rewrite of the popup functionality was planned so we put it off.

**Comment by gregsexton** [comment]
Thanks a lot for your effort here. I'm happy to submit to whatever groupings you think are reasonable. I would advise you take your time to gain consensus as refactoring the groupings will annoy users who have already learned where things are!

magit-popup has already been extracted: http://melpa.org/#/magit-popup

**Comment by benedekfazekas** [comment]
no worries. groupings: exactly, happy to hear suggestions.

**Comment by Malabarba** [comment]
Personally, i love magit, but I think magit popups are overkill here. Hydras would be more lightweight and even offer more useful functionality (like a timeout before the popup, or a sticky keymap).

**Comment by Malabarba** [comment]
That said, I'm just here to make a suggestion, not block progress. :)

**Comment by expez** [comment]
[Here](https://github.com/abo-abo/hydra) is the hydra in question.  This looks cool as shit!

**Comment by benedekfazekas** [comment]
will check hydras. the point here is to provide a datastructure which these tools can use. I appreciate this take of mine could be quite `magit-popup` inspired...

**Comment by gregsexton** [comment]
The thing I wanted was the popup that lists refactorings against their keybind. Do you get this with hydras?

**Comment by expez** [comment]
@gregsexton Here's the solution I'm using to discover keybindings in general. [helm-descbinds](https://github.com/emacs-helm/helm-descbinds)

![helm-descbinds](http://i.imgur.com/3GwOlFM.png)

This popup is created by hitting `C-c C-m C-h` where `C-c C-m` is the prefix key to which I've bound `clj-refactor`.

**Comment by benedekfazekas** [comment]
I think it does. and if understand it right we could actually reuse our two char mnemonics (not only 1 char is allowed) -- not sure how generating a buffer menu could be automated based on our `cljr--all-helpers`)

**Comment by gregsexton** [comment]
@expez, thanks for the screen shot. It does look useful. I'm just not sure if I want to bring in all of helm just for this.

**Comment by benedekfazekas** [comment]
to compare magit popups and hydra menus i drafted both solutions quickly.

## magit popup

![cljr-magit-popup](https://cloud.githubusercontent.com/assets/1003422/9580500/d4850b40-4ff1-11e5-8bbc-a7067c362e72.gif)

## hydra menu

![cljr-hydra-menus](https://cloud.githubusercontent.com/assets/1003422/9580507/de859b32-4ff1-11e5-8e18-af8099a939f7.gif)

I think hydra has the more pros (note tho that possibly I did not get all the config options of magit popups)
- it understands multiple key events so we can use the original key combos (more beneficial for our users as it teaches them the key combo they can use with a prefix)
- hydras are easily embeddable so we can use a main menu (optionally)
- the user can keep the hydra alive until finished the refactoring session, kinda nice (see gif above)

I propose to add hydra as a dep to clj-refactor (it only depends on `cl-lib`) and provide our own menus. magit popus can be implemented like cljr-helm in a separate project.

what do you think, ppl?

**Comment by expez** [comment]
I like the hydra better too, but how about just having a single level with all the refactorings available?  The code related refactoring list is already quite a large, a few more rows won't make a huge difference.

**Comment by benedekfazekas** [comment]
haha i was thinking to do the opposite. eg tweak the types so i can break the code type into two types

**Comment by expez** [comment]
Grouping things more doesn't help answer the questions:

1. What is available?
2. What is the keybinding for that refactoring again?

**Comment by expez** [comment]
>  you still need to see the code and its context. 

I don't think anyone would want to use this all the time, but in the beginning when learning what's available and then every now and again to get a reminder.  As an 'expert user' of clj-refactor I certainly never want to see this menu myself.

**Comment by magnars** [comment]
I agere with Ben on this one. I've ben using magit for years - still need
to reference the menu now and then. Best to make it more than an
encyclopedia.
man. 31. aug. 2015 kl. 17.03 skrev Lars Andersen <notifications@github.com>:

**Comment by benedekfazekas** [comment]
pushed the hydra powered menus see #220 implementation could be nicer in terms of being more dynamic but this is an implementation detail. if no further comments/objections here will merge #220 tmrw to close this.

**Comment by gregsexton** [comment]
Looks great! Thanks for taking on this request. I'm a hydra convert too. I recently created a hydra for paredit and I'm not looking back. :)

**Comment by benedekfazekas** [comment]
no worries. hope it will be helpful ;)
