### ISSUE TITLE
Add supporting middleware op for magic requires?

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#215]
In most projects the use of aliases are consistent (and we should try to nudge people in that direction if they are not).  How about making a middleware op to get the alias mappings in the current project and use those to serve up suggestions for magic require?

So if there's some ns on the disk called `com.acme.utils` which we've seen aliased as `util` then when the user types `util/frobnicate` we can prompt if they'd like `com.acme.utils` added to the ns form.

**Comment by yatesco** [comment]
+1 also taking into account how test subjects are named (i.e. `:refer :all` or `:as sut`). See https://github.com/clojure-emacs/cider/issues/1283 for more info.

**Comment by expez** [comment]
Could you do a copy-paste job and create a new issue for clojure-emacs/cider#1283?  It's not really related to this proposed enhancement.

**Comment by yatesco** [comment]
Done: #217

My thinking was that the same code that learns about the project specific aliases could also learn about how tests are `refer`ed.

**Comment by Malabarba** [comment]
> when the user types util/frobnicate we can prompt if they'd like com.acme.utils added to the ns form

Better not prompt while the user is in the middle of typing. Since magic-requires is already an existing feature, it's probably safe to make it smarter without bothering the user.

**Comment by expez** [comment]
> Better not prompt while the user is in the middle of typing. 

`cljr-magic-requires` is either `gogogo`, `prompt` or `off` :)
