### ISSUE TITLE
Insufficient require form when creating test.cljc

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#216]
Create `src/test/a/b/c_test.cljc` and it produces:

``` Clojure
(ns a.b.c-test
  (:require [a.b.c :refer :all]
                 [clojure.test :refer :all]))
```

It would be better if it produced a clic aware test reference, for example:

``` Clojure
(ns a.b.c-test
  (:require [a.b.c :refer :all]
                #?(:clj [clojure.test :refer :all]
                     :cljs [cljs.test :refer :all)))  ;; or whatever the correct new cljs namespace is
```

**Comment by expez** [comment]
Would be great if you edited the OP with a copy-paste job instead of just linking.

**Comment by yatesco** [comment]
done - apologies @expez, I wasn't sure of the 'etiquette'.

**Comment by expez** [comment]
Thanks for the report @yatesco.  We're in the very early stages of adding support for cljs and cljc.
