### ISSUE TITLE
Parameterise whether require ns use `:refer all` or `:as sut` when creating namespace form 

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#217]
At the moment the automatically generated `:require` statement pulls in the subject under test as `[a.b.c :refer :all]`. I, and I think a bunch of people would prefer `[a.b.c :as sut]`.

Would be great if `cider` exposed a var which either:
 - toggled between the two (e.g. `cider-pull-su-as-refer-all`)
 - provided a template for the require form (e.g. `(setq cider-sut-require-form "[:refer % :as sut]")`)

I dunno - I am an emacs newbie, but hopefully the intent of this issue is clear.

Thanks!

**Comment by expez** [comment]
I'd prefer just making this the new default because there is no `:refer :all` in cljs and it's kind of considered a bad practice as it is.  What do you guys think @benedekfazekas @magnars?

**Comment by expez** [comment]
Seems I messed up the issue reference, but this is fixed in https://github.com/clojure-emacs/clj-refactor.el/commit/98f1013f0918d93b26ba0d1bea0cb743fad31be0
