### ISSUE TITLE
error in process filter: Symbol's function definition is void: cider-nrepl-op-support

### ISSUE THREAD

**Issue by djg123** [clojure-emacs/clj-refactor.el#222]
After installing clj-refactor and adding `[cider/cider-nrepl "0.10.0-SNAPSHOT"]` to `.lein/profiles.clj`
the error message 
    
    error in process filter: Symbol's function definition is void: cider-nrepl-op-support 

started showing up when I run `cider-jack-in` or if I run `cljr-find-usages`.

I am using `clj-refactor 1.2.0-SNAPSHOT (package 20150902.625)`, `CIDER 0.10.0snapshot (package 20150826.847)`, and `clojure-mode (version 4.2.0-snapshot)` with `GNU Emacs 24.4.1`.

**Comment by expez** [comment]
`cider-nrepl-op-supported-p` was recently added to cider.  You need to upgrade to the latest version of CIDER.
