### ISSUE TITLE
"cljr clean ns" should keep namespace meta information

### ISSUE THREAD

**Issue by huahaiy** [clojure-emacs/clj-refactor.el#223]
Such as :doc and :author, etc, instead of removing them.

**Comment by expez** [comment]
I can't reproduce, but I know this was a problem in the past.  What's the output of `M-x cljr-version` (in emacs)?

If it's anything other than 

`clj-refactor 1.2.0-SNAPSHOT (package: 20150902.625), refactor-nrepl 1.2.0-SNAPSHOT`

I'd appreciate if you upgraded, tried again, and posted a minimal example exhibiting the problem if it still persists.

**Comment by huahaiy** [comment]
Yes, I have the latest versions as shown above. The bug can be reproduced when there is a comment before the name space declaration. A minimal example follows:

;; ===========================================================================
;;
;; Copyright (c) Example Inc. All rights reserved.
;;
;; ===========================================================================
(ns ^{:doc "Important documentation"}
  example.core
  (:import java.io.ByteArrayInputStream)
  (:require [clj-time.core :as t]
            [clojure.string :as s]
            [clojure.java.io :as io]
            [taoensso.timbre :as timbre]))

(timbre/refer-timbre)

(defn foo
  "I don't do a whole lot."
  [x]
  (let [t (t/now)
        ss (ByteArrayInputStream. (io/file "afile.txt"))]
    (println (s/trim x) "Hello, World!")))

The presence of the copyright notice will trigger the bug. Removing it removes the bug, but it is common for copyright notice to appear at that position.

**Comment by expez** [comment]
I've deployed a new snapshot containing this fix.  Thanks for the bug report @huahaiy!

**Comment by huahaiy** [comment]
Thanks for the quick fix.
