### ISSUE TITLE
Running cljr-find-usages kills repl

### ISSUE THREAD

**Issue by djg123** [clojure-emacs/clj-refactor.el#224]
When I run `cljr-find-usages` I get the following message in the mini-buffer: 
`Also kill server process or buffer? (y or n)`. The repl then gets disconnected.

I also find this in `*Messages*` directly after running the command: `nREPL: Connection unexpectedly closed (connection broken by remote peer)`.

My setup:
```
CIDER 0.10.0snapshot (package: 20150914.1558)
clj-refactor 1.2.0-SNAPSHOT (package: 20150910.1031)
clojure-mode (version 4.2.0-snapshot)
GNU Emacs 24.4.1
```

**Comment by expez** [comment]
@djg123 Could you show us some of the messages in `*nrepl-messages*` after you issue the command `cljr-find-usages`?

@Malabarba @bbatsov any recent changes that might explain this in CIDER?

**Comment by bbatsov** [comment]
Looking at the messages it looks that the connection died. Then it prompted for the server buffer to be killed as well. Nothing extraordinary there.

**Comment by expez** [comment]
> Nothing extraordinary there.

The connection dying upon running `cljr-find-usages` is not the intended outcome :)

**Comment by djg123** [comment]
Okay, it seems that the command does the right thing if I execute it while the cursor is on the var name. As soon as I try to run the command again while the cursor is in a different spot, the connection dies.

Here is output from `*nrepl-messages*` when the connection dies:
```
(--->
  op  "find-symbol"
  prefix-rewriting  "true"
  debug  "false"
  ns  "dir"
  /home/djg/program3/clojure/bitfinex-api/  "file"
  /home/djg/program3/clojure/bitfinex-api/src/bitfinex_api/core.clj  "line"
  133  "column"
  35  "name"
  parameters  "ignore-errors"
  id  "57"
)
```

Also, here is output from the `*nrepl-messages*` buffer when the cursor *is* on top of a valid identifier:

```
(--->
  op  "find-symbol"
  prefix-rewriting  "true"
  debug  "false"
  ns  "bitfinex-api.core"
  dir  "/home/djg/program3/clojure/bitfinex-api/"
  file  "/home/djg/program3/clojure/bitfinex-api/src/bitfinex_api/core.clj"
  line  133
  column  13
  name  "build-parameters"
  id  "55"
)
(<-
  id  "55"
  occurrence  "(:line-beg 7 :line-end 8 :col-beg 1 :col-end 23 :name \"bitfinex-api.core/build-parameters\" :file \"/home/djg/program3/clojure/bitfinex-api/src/bitfinex_api/core.clj\" :match \"(declare build-parameters get-request convert-to-floats\\n          parseDouble)\")"
  session  "cddbef57-87a8-4084-98a7-a553de6172a9"
)
(<-
  id  "55"
  occurrence  "(:line-beg 40 :line-end 40 :col-beg 32 :col-end 49 :name \"bitfinex-api.core/build-parameters\" :file \"/home/djg/program3/clojure/bitfinex-api/src/bitfinex_api/core.clj\" :match \"(str with-path-arg \\\"?\\\" (build-parameters parameters))\")"
  session  "cddbef57-87a8-4084-98a7-a553de6172a9"
)
(<-
  id  "55"
  occurrence  "(:line-beg 133 :line-end 137 :col-beg 1 :col-end 29 :name \"bitfinex-api.core/build-parameters\" :file \"/home/djg/program3/clojure/bitfinex-api/src/bitfinex_api/core.clj\" :match \"(defn build-parameters [parameters]\\n  (s/join \\\"&\\\"\\n          (map (fn [[k v]]\\n                 (format \\\"%s=%s\\\" (s/replace (name k) \\\"-\\\" \\\"_\\\") v))\\n               parameters)))\")"
  session  "cddbef57-87a8-4084-98a7-a553de6172a9"
)
(<-
  count  3
  id  "55"
  session  "cddbef57-87a8-4084-98a7-a553de6172a9"
  status  ("done")
)
```

I see that `ns` for the first example is `dir`, while `ns` for the working example is the correct namespace for my buffer. In both cases, I executed `cljr-find-usages` directly after running `cider-repl-set-ns` successfully.

**Comment by expez** [comment]
@djg123 I also thought about raising a `user-error` when the cursor isn't on a symbol but this is the first time someone has tried to do that.  I'd also feel like I'd have to raise errors everywhere else where a symbol below point is expected.  Do you think that's necessary?

**Comment by djg123** [comment]
@expez: 
The purpose of a `user-error` is to help teach the user how the software is supposed to work. After you know how the software behaves, you don't need it anymore. 

My expectation, when I first ran `cljr-find-usages` was that it would prompt for input in the mini-buffer with the symbol under the cursor as a default. This is how `cider-find-var` works. But now that I know how `cljr-find-usages` is supposed to work, I like it the way it is.

That being said, I think it would be *better* to have `user-error`s than not. But you should only make it a priority if a lot of users ask for it.

**Comment by djg123** [comment]
Now, I am actually getting a much less serious error in the mini-buffer after running `cljr-find-usages` when the cursor is not on a symbol:
```
error in process filter: Unclosed character class near index 9
(^|\W)[]\W
```

**Comment by expez** [comment]
I'd guess this means you have a bad regexp somewhere in your project, which prevents `tools.analyzer.jvm` from building an AST. 

I'll look into getting more information into the stacktraces.  It would be nice if it gave you file and line number instead of just asking you to check at index 9.
