### ISSUE TITLE
inline-symbol prompts for class

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#225]
Place point on `out` and call `cljr-inline-symbol`.

```clojure
  (let [out (fork-out (vals new-state))]
    ;; (System/setOut (PrintStream. out))
    (alter-var-root #'*out* (constantly out)))
```

I get a prompt saying `Member in class: `.
If I change the symbol to `oua` the problem is gone.

**Comment by expez** [comment]
Thanks for the report @Malabarba!
