### ISSUE TITLE
Inline symbol doesn't seem to work for string variables.

### ISSUE THREAD

**Issue by bilus** [clojure-emacs/clj-refactor.el#231]
Given the following snippet (point position indicated by ][ in the code):

```clojure
(let [pa][ssword "password"]
              (with-open [recovery-file (generate-recovery-file password)]))
```

`clr-inline-symbol` produces:

```clojure
(with-open [recovery-file (generate-recovery-file password)])
```

Note the missing quotes around `password`.

**Comment by expez** [comment]
`M-x cljr-version <RET>`

I can't reproduce this in `1.2.0-SNAPSHOT` and some code paths related to this functionality was made quite a bit more robust in `2.0.0-SNAPSHOT`.

**Comment by bilus** [comment]
Here it goes:

![image](https://cloud.githubusercontent.com/assets/1025537/10072532/cd559bee-62c2-11e5-90d5-fdcf0c6b61ae.png)

I'm an Emacs n00b; how do I install 2.0.0-SNAPSHOT? It seems only 1.2.0-SNAPSHOT of clj-refactor.el is available in melpa and on your github? Or should I leave the package as it is and upgrade only refactor-repl? Thanks.

**Comment by expez** [comment]
@bilus 2.0.0-SNAPSHOT is now the latest version of clj-refactor and refactor-nrepl.  If you update with the lastest version from melpa, and update`profiles.clj` you should be good.

**Comment by bilus** [comment]
Thanks!

**Comment by bilus** [comment]
After updating, I'm unable to use clj-refactor in the same project. Oddly enough, I'm getting:

cljr--maybe-rethrow-error: clojure.lang.ExceptionInfo: Circular dependency between om-event-bus.impl and om-event-bus.impl {:reason :mranderson046.toolsnamespace.v0v3v0-alpha1.clojure.tools.namespace.dependency/circular-dependency, :node om-event-bus.impl, :dependency om-event-bus.impl}

It is odd, because I'm running a clj REPL, running a clj-refactor command in a .clj buffer and the file it seems to complain about is generated from https://github.com/bilus/om-event-bus/blob/master/src/cljx/om_event_bus/impl.cljx

As you can see, .cljs file does refer to its .clj counterpart to require macros but .clj file contains no such reference.

**Comment by expez** [comment]
Man, I'm truly sorry you're having such a shit time getting started with clj-refactor :( 

This seems to be a bug in `tools.namespace`, which is triggered when it processes the output of the cljx plugin.

The good news is I recently wrote some code to exclude everything under `<project root>/target` which should provide a workaround for this issue (since that's where the cljx files appear to end up).  

I just published a new snapshot with these changes.

You can use `lein -U <task>` to force an update of snapshots, e.g. with `lein -U repl`.

**Comment by bilus** [comment]
First of all, I absolutely love clj-refactor. Zero shit time; it's marvelous!

1. Inline symbol, confirmed, it works -- thank you so much.

2. Wow... you're fast; I was typing my reply as yours arrived. I worked around the issue by a bit of restructuring (I'm the maintainer); but I'll move it to .cljc sometime soon. I updated anyhow to be on the latest one. Thanks again.

**Comment by expez** [comment]
Glad you got it working! :+1:
