### ISSUE TITLE
Get rid of sort-ns, replace-use and remove-unused-requires in 2.0.0?

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#235]
Right now a huge chunk of our code base is dedicated to doing work on the ns form.  Part of my motivation for writing `clean-ns` was that these functions were both fragile and difficult to maintain/extend.

Once we solve, the trivial, https://github.com/clojure-emacs/refactor-nrepl/issues/119 there's no technical reason to keep this duplication around.

Does anyone have an objection to removing them?

**Comment by benedekfazekas** [comment]
I am a bit worried that since there might not be a 1.2.0 release of refactor-nrepl ppl who are still using 1.6 clojure might get quite a bit annoyed: they can't use the refactor-nrepl based cljs support but the vanilla elisp is removed as well...
