### ISSUE TITLE
'cljr-add-missing-libspec' is not working with clj-refactor-20150924.256 version

### ISSUE THREAD

**Issue by ksseono** [clojure-emacs/clj-refactor.el#236]
when I tried following command to install clj-refactor
`
M-x package-install clj-refactor
`

I met a warning as below:
`
In end of data:
clj-refactor.el:4287:1:Warning: the following functions are not known to be defined:
    cider-nrepl-op-supported-p, cider-nrepl-send-sync-request,
    cider-nrepl-send-request, cider-repl-emit-interactive-stderr
`

And because of these missing functions, when I tried 'cljr-add-missing-libspec' I met this message:
`
"symbol's function definition is void" cider-nrepl-op-supported-p 
`

It seems like current default version which is 'clj-refactor-20150924.256' has a problem. The warning is not shown with the version "1.1.0" which is properly working, even it has more warnings during the installation.

**Comment by expez** [comment]
These functions are only present in the latest version of CIDER.  You have to update CIDER.

**Comment by ksseono** [comment]
@expez Thank you so much! After updating CIDER to latest version, the cli-refactor is working properly and the warning message is gone as you said :+1:
