### ISSUE TITLE
IDEA? Hook in some refactorings on save

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#245]
I think it would be great if some of the refactorings (e.g. `clean-ns`) executed automatically when saving the file. Is this possible, and if so - how :-).

**Comment by magnars** [comment]
Something like this, maybe? :-)

```cl
(defun enable-clojure-mode-stuff ()
  (clj-refactor-mode 1)
  (add-hook 'before-save-hook 'cljr-clean-ns t t))

(add-hook 'clojure-mode-hook 'enable-clojure-mode-stuff)
```

**Comment by magnars** [comment]
There might be issues with `cljr-clean-ns` being async, come to think of it, tho.

**Comment by expez** [comment]
> There might be issues with `cljr-clean-ns` being async, come to think of it, tho.

This should still work, but the changes won't be saved.  `cljr-clean-ns` should perhaps save the buffer after doing it's thing?

**Comment by magnars** [comment]
I'm always a little annoyed when a command saves the buffer for me. It triggers builds in figwheel or runs tests for me, when I'm not ready for it to happen. So my vote is to have as few autosaves as possible.

**Comment by expez** [comment]
> I'm always a little annoyed when a command saves the buffer for me.

yeah, I feel the same way.  It's easy now for anyone wanting this behavior to just add a piece of advice anyway.

**Comment by yatesco** [comment]
Thanks both.

@magnars - the simple answer is don't write so many tests (I jest of course), I also love the over-estimation of "easy enough for anyone" :-)!

In all seriousness, I have found the `feature` tests in this and multiple-cursors to be very inspiring. I actually dug out my cucumber/gherkin experience from a few years back, dusted it off, captured some domain rules in it and then remembered why I hate regular expressions :-).

Anyway, again, thanks both.

**Comment by magnars** [comment]
:-)
