### ISSUE TITLE
IDEA - highlight unused vars

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#246]
Given that `find-usages` exist, is there any trick to highlighting vars that aren't used?

**Comment by expez** [comment]
In general you can't know for sure, given the dynamic nature of clojure, but with good test coverage you should be able to just delete stuff and see if anything breaks.

I was surprised to see [eastwood](https://github.com/jonase/eastwood) lacking this functionality but you can get some help from [sniper](https://github.com/w01fe/sniper).  If this was in [eastwood](https://github.com/jonase/eastwood) we'd get it for free with [flycheck-clojure](https://github.com/clojure-emacs/squiggly-clojure).

**Comment by benedekfazekas** [comment]
we also had plans to integrate sniper few months ago but then it did not
happen. perhaps wroth a look: such a PR would be awesome ;)

**Comment by yatesco** [comment]
Thanks both. @benedekfazekas - man, you don't now how bad my emacs skills are :-). I wish I had the time to get into this instead of continually asking others to do this sort of thing for me :-(. One day I will contribute something back, I promise!

**Comment by expez** [comment]
> we also had plans to integrate sniper few months ago but then it did not
happen. perhaps wroth a look: such a PR would be awesome ;)

I still think sniper should be left in its own package.  There's no point in taking on even more stuff to maintain.  Furthermore, if we go down that path we'd soon find ourselves integrating with kibit, eastwood, typed-clojure etc etc.

**Comment by benedekfazekas** [comment]
@Colin this is more like clj coding tho. and re @expez: haha so PR wlc with
considerations

**Comment by expez** [comment]
closing as solved by the combination of sniper (globals) and eastwood (locals) via flycheck-clojure
