### ISSUE TITLE
helm interference

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#247]
Hi all,
From looking at issues here and in multiple-cursors it appears there are some teething problems with helm. In particular, when I `M-x` ->  `cljr-move-to-let` I can see the let is created and multiple-cursors is activated but my focus is still in the 'thingy-majig' at the bottom of emacs where I can see `M-x` waiting for a prompt.

If I turn off helm-everywhere then it all works OK.

I am torn because I use helm everywhere and would struggle to give up `helm-ag` and `helm-occur` so I as wondering if there was a way of making these (I expect the 'culprit' is actually multiple-cursors?) play nicer. 

Alternatively, is there a 'helm-recovery' package :-) that provides similar capabilities as helm but for ido?

Or, is there a magic combination of keys that temporarily deselects helm whilst I do refactoring?

Thanks!

**Comment by expez** [comment]
I think the easiest solution for you would be to just learn the keybindings for these refactorings. .e.g `C-c C-m ml`.  This has the benefit of being a lot quicker, after a small initial investment.

I don't use helm myself, instead i use ido with the following addons:

* ido-vertical-mode
* flx-ido
* ido-hacks

I think you'll have better luck opening this issue over at the helm repo.

**Comment by benedekfazekas** [comment]
you can also give a try to hydra menus which actively teach you the combos
(see wiki)

**Comment by yatesco** [comment]
That's fantastic - I didn't realise it worked with the keybindings and was only a problem if a refactoring was launched from `M-x`. 

Perfect - and thanks for the ido/hydra hints.
