### ISSUE TITLE
Making namespace prefix notation optional

### ISSUE THREAD

**Issue by nblumoe** [clojure-emacs/clj-refactor.el#249]
Would be cool, if we could make the prefix notation in `clean-ns` and the like optional. Using prefix notation could stay the default, but clj-refactor options in the emacs config could disable it.

How does that sound? Would a PR have a chance of getting merged? Any pointers towards how to implement this (e.g. existing or upcoming implementations of options)?

**Comment by expez** [comment]
Hi

This is already implemented.  Just put `(setq cljr-favor-prefix-notation nil)` in your `.emacs.d/init.el` or do `M-x customize-group <RET> cljr <RET>`to use the customize facilities in emacs to change the setting.

Since `cljs` doesn't support prefix notation this is disabled in cljs files, and in cljc files (for reasons of symmetry :P).

**Comment by nblumoe** [comment]
Cool, thanks!

There is no explicit documentation on Github for the options, is there? I found https://github.com/clojure-emacs/clj-refactor.el/wiki#customization and now that I know about it, this is sufficient for me. Also has the benefit of always being up to date.

Maybe adding an additional link to the README would make that more obvious?

**Comment by expez** [comment]
> There is no explicit documentation on Github for the options, is there?

That's right.  The docstrings for the variables are intended to be good enough.  If they're not, that's definitely a bug :)  

In general the customization system in emacs is a great way to discover settings you can tweak for any package.  I'll update the readme to link to the customization page to point this out.  Thanks for the suggestion!

**Comment by nblumoe** [comment]
Thanks again, also for the great package, I really like it!

Up to you to decide, if it's just me being to dumb not having found this myself or if it's worth making it more explicit in the README.

Cheers!
