### ISSUE TITLE
cljr-rename-symbol don't work outside a function

### ISSUE THREAD

**Issue by edipofederle** [clojure-emacs/clj-refactor.el#251]
Hi,

let say a have a code like this:

```
(let [point 10]
  (if (> point 10)
    :bar
    :foo))
```
If I try call ```cljr-rename-symbol``` in order to rename ```point``` this happens

![screen shot 2015-10-31 at 1 32 06 pm](https://cloud.githubusercontent.com/assets/50778/10864389/d37097d0-7fd3-11e5-8633-aff61ae587fd.png)

And REPL (cider) is terminated

My emacs version: 24.5.1
clj-refactor version: 1.2.0

Whats going on here ?

Thanks in Advance

**Comment by expez** [comment]
This is weird and I have no idea what's going on.  Does this happen if you upgrade to the latest snapshot (2.0.0)?

In any event, code like this is only seen in tutorials, or it's going to make up say 0.001% of the code in the project so I'm not sure I want to expend much effort solving this.

Any interest in looking into this yourself?

**Comment by edipofederle** [comment]
Yes, is not a "real world" code. I will try to update to 2.0.0 and let you know. If it not works, I will try take a look. 

Thanks

**Comment by edipofederle** [comment]
Hi again,

I just upgrade to 2.0.0 and now I receive:

``` Wrong type argument: hash-table-p, (:line-beg 28 :line-end 28 :col-beg 12 :col-end 15 :name "foo" ...)Error during redisplay: (eval (mode-line-mode-name)) signaled (void-function mode-line-mode-name)```

In both case, inside a function or outside.

**Comment by expez** [comment]
You also need to upgrade the middleware. In general, they should be on the same version or weird stuff might happen.

**Comment by edipofederle** [comment]
Yes. It works inside and outside a function. With both in same version. I will close it.

Thanks

**Comment by expez** [comment]
Glad to hear it! :)
