### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#252]
@rejeep Do you have any idea why our builds, like [this one](https://travis-ci.org/clojure-emacs/clj-refactor.el/jobs/88333991), are all suddenly failing in this manner?

```
-UUU:----F1  *scratch*      All L1     (Lisp Interaction) ----------------------
Opening directory: no such file or directory, /home/travis/build/clojure-emacs/\
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

The builds work fine locally :/

In the `travis` branch I tried doing the same in [.travis.yml](https://github.com/clojure-emacs/clj-refactor.el/blob/travis/.travis.yml) as you do in your ecukes project, but it failed in the same manner.

**Comment by rejeep** [comment]
Doesn't seem unreasonable that it has something to do with this message: `Opening directory: no such file or directory, /home/travis/build/clojure-emacs/\`

Have you seen that before? Should it exist?

**Comment by expez** [comment]
Yeah, I think that message is key too.  I've never seen it before.  I'm guessing that folder is part of the directory structure travis sets up per-project. 

Anyway, I was hoping you'd seen this problem yourself.  I thought travis made some changes to their infra/setup which caused this, but I when I tried to run our tests on circleci instead I got something similar:

```
Opening directory: No such file or directory, /home/ubuntu/clj-refactor.el/tmp
```

`tmp` is the name of a dummy project we run our tests against.

The good thing with circle is that you can ssh into the test box to investigate.  Guess that's the next step.

**Comment by expez** [comment]
https://github.com/clojure-emacs/clj-refactor.el/commit/d0f22cbdb064e673379278293568ce037f12f6ab

There was an actual test failure here, but deleting a non-existing directory has started erroring, which was the real problem.

**Comment by rejeep** [comment]
Weird, glad it worked out though!
