### ISSUE TITLE
Replace use ignores alias

### ISSUE THREAD

**Issue by jonpither** [clojure-emacs/clj-refactor.el#253]
I have 

`(ns dev
  (:use [foo.system :as system]))`

(system/do-stuff)

`r-u` (replace use) will replace the ns decl with:

`(ns dev
  (:require [foo.system :refer :all]))`

This then breaks the call to `(system/do-stuff)`

**Comment by benedekfazekas** [comment]
that is an interesting one. although the above is valid why would you use `use` with alias instead of `refer` (with alias)?

that said even if it is not preferred we could support getting rid of it...

**Comment by expez** [comment]
@jonpither I recommend you switch to `cljr-clean-ns`. 

I consider the elisp stuff to be deprecated and have been pushing for their removal, but I keep meeting resistance :p /cc @magnars

**Comment by magnars** [comment]
The resistance to removing elisp stuff was due to clean-ns 1) missing clojurescript support, and 2) missing project-clean support. I think both of those are close to fixed?

**Comment by expez** [comment]
I'm not aware of any problems with the cljs support, though I don't write much of that lately.  AFAIK `cljr-clean-ns` also works fine with `cljr-project-clean` now.  I seem to remember @benedekfazekas doing some work a while back to make that happen.

**Comment by jonpither** [comment]
@benedekfazekas this is code I found in the wild, there's no rhyme or reason to it.

**Comment by benedekfazekas** [comment]
fair enough @jonpither have you given a try to `clean ns` instead of `replace use`?

**Comment by jonpither** [comment]
I tried `clean ns`, but I get `cljr--op-supported?: Symbol's function definition is void: cider-nrepl-op-supported-p`, guess I have some setup issue to sort out (although I did make an effort to have the latest of everything). Need to dig into why it's not working.

**Comment by benedekfazekas** [comment]
I think your cider version is behind meaning the elisp part of cider which clj-refactor.el depends on

**Comment by benedekfazekas** [comment]
for latest clj-refactor.el you need the latest cider: https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L11

**Comment by jonpither** [comment]
Upgraded CIDER.

Clean-ns converts


(ns dev
  (:use [foo.system :as system]))

to 

(ns dev
  (:require [foo.system :as system :refer :all]))

Which is the correct thing.

I now have this healthy report in my REPL, for this is me to sort out:

WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.0.0-SNAPSHOT (package: 20151102.134) and 1.1.0, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.
ERROR: CIDER's version (0.10.0-snapshot) does not match cider-nrepl's version (0.9.1). Things will break!

**Comment by benedekfazekas** [comment]
that is an easy tweak most likely in your `~/.lein/profiles.clj` (assuming you define these things there and you use leiningen)

**Comment by magnars** [comment]
@expez I can confirm that `cljr-clean-ns` now works fine with project-clean.
