### ISSUE TITLE
Remove-requires fails when no require in the ns declaration

### ISSUE THREAD

**Issue by jonpither** [clojure-emacs/clj-refactor.el#254]
i.e. 

`(ns bar.foo
  (:use [bar.core]))`

I executed RR through muscle memory, and to see what would happen, didn't expect to see an exception...

**Comment by benedekfazekas** [comment]
yeah, should be a pretty straight forward fix. thx for reporting

**Comment by expez** [comment]
Closing both issues because `cljr-clean-ns` doesn't suffer from these issues.
