### ISSUE TITLE
Thread-first/last leave hanging parentheses

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#255]
It's been a while since my last bug report, so here's another one before you get too comfortable. :-)

Using the thread commands on something like this:

    (map inc
         (range))

Will give me something like this

    (->> (range)
         (map inc
              ))

Although it really should give this

    (->> (range)
         (map inc))

Cheers

**Comment by expez** [comment]
Thanks for the report, @Malabarba :+1:
