### ISSUE TITLE
Hydra  HOWTO linked to but missing from wiki

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/clj-refactor.el#257]
Rather confusing as I'm trying to use the Hydra support. Awesome project, thanks for the hard work!

**Comment by benedekfazekas** [comment]
fair point. currently only [parent menu for hydra menus](https://github.com/clojure-emacs/clj-refactor.el/wiki/Hydra) works. it kinda demonstrates how to use the hydras for clj-refactor tho.

**Comment by expez** [comment]
How do you want to fix this, @benedekfazekas?  I'm inclined to just remove the links.  I'm not sure each hydra menu needs its own page.

**Comment by benedekfazekas** [comment]
I guess I will make some more screen casts. still need centre to have a
full coverage of key combos even if there is a bit of repetition

**Comment by arrdem** [comment]
@expez I'd suggest just fixing it, /wiki/hydra exists, right now I think the link goes to /wiki/hydra-main. I'd never heard of hydra before and found even what little y'all have on the subject really useful. Presuming that users are up to date with the Emacs new hotness is not like to end well in my case at least.

**Comment by benedekfazekas** [comment]
done. enjoy :)

**Comment by expez** [comment]
Great @benedekfazekas! :+1:
