### ISSUE TITLE
unwind sometimes creates badly styled forms

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#259]
This is fairly small, and might be a pain to fix. =P

Use `unwind-all` on this form.

    (->> [a b]
         (some (fn [x]
                 (when x
                   10))))

The outcome will be this:

    (some (fn [x]
            (when x
              10)) [a b])

In general, when a multi-line sexp ends, there should be nothing else on the same line.

Cheers

**Comment by expez** [comment]
Fixed as part of the move to clojure-mode, so it won't be tackled here.  Great work @benedekfazekas!
