### ISSUE TITLE
Rename Symbol Arguement Type Error

### ISSUE THREAD

**Issue by TheTedHogan** [clojure-emacs/clj-refactor.el#262]
I'm getting the following message whenever I try and use cljr-rename-symbol:
>cljr--rename-occurrences: Wrong type argument: hash-table-p, (:line-beg 98 :line-end 98 :col-beg 14 :col-end 29 :name "genisys-forecasts.handler/wrapper-helper" ...)

There's a similar error that occurs with projectile, but I've been unable to get this error to disappear.

**Comment by benedekfazekas** [comment]
just a guess but most likely your clj-refactor.el and refactor-nrepl is out of sync. if you use the latest snapshots try to clj-refactor by pulling the latest

**Comment by expez** [comment]
@TheTedHogan do `M-x cljr-version <RET>` and you'll see the version mismatch.  You're running a version of `refactor-nrepl` which is older than `clj-refactor`.

**Comment by TheTedHogan** [comment]
Thank you. I was missing the glaring error message when cider starts.
