### ISSUE TITLE
cljr-slash and clojurescript not friends

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#263]
Have a `.clj`-file with:

```clj
(require [datomic.api :as d])
```

and a `.cljs`-file with:

```clj
(require [quiescent.dom :as d])
```

Type `(d/` in a cljs-file. `datomic.api` is automatically required.

**Comment by expez** [comment]
Can't reproduce this.  Are you running the latest version?

**Comment by magnars** [comment]
Yes, this still happens on the latest versions of clj-refactor and refactor-nrepl.

I'm not running any cljs-repl, only a clj-repl. Maybe that explains it?

**Comment by expez** [comment]
I just tried both situations and it did the right thing.  Granted I just aliased `set` and `string` to `s` in clj and cljs and checked that the right thing was brought into a new cljs ns.

If this is still easy to reproduce for you, could you check the message (containing the `namespace-aliases` response) from the backend and see if it looks right?  Specifically, the data under the `cljs` key shouldn't contain the datomic namespace as that's clj only.

**Comment by magnars** [comment]
The `cljs` key contains `d (quiescent.dom)` like it should. The `clj` key contains `d (datomic.api)`.

**Comment by expez** [comment]
@magnars i think you have to step through `cljr--call-middleware-for-namespace-aliases` and see why `cljr--clj-context?` returns `t` causing a lookup in the clj part of the return value.

**Comment by magnars** [comment]
`cljr--clj-context?` returns `t` because `cljr--clj-file?` returns `t` because `(eq major-mode 'clojure-mode)`.

**Comment by expez** [comment]
@magnars thanks.  Clojure-mode was updated a while back to add clojurescript-mode for cljs files and cljc-mode for cljc files.  Updating clojure-mode should solve this. 

I guess I did it this way because I wanted this to work even if there was no file backing the buffer, but I suppose we could change this to check for a file ending instead?  Thoughts?

**Comment by expez** [comment]
CIDER 0.10-SNAPSHOT depends on clojure-mode v 5, which contains this change.

**Comment by magnars** [comment]
I had upgraded everything, but I also had this in my settings:

```el
(add-to-list 'auto-mode-alist '("\\.cljs$" . clojure-mode))
```

Fixing that solved the issue. 

Thanks for the help, and sorry about the noise.

**Comment by magnars** [comment]
As for my thoughts on the check, I'm not sure how many people actually have namespace declarations in scratch buffers. Either way has its faults, I guess. :)
