### ISSUE TITLE
implement remove unused locals

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#264]
something like http://www.mobypicture.com/user/Borkdude/view/18654333

I am thinking instead of highlighting we could run a remove unused locals. `find-used-locals` (or something very similar) should be the backend.

**Comment by magnars** [comment]
I think the greying out of unused locals is generally more useful, but I can see how it might be prohibitevly expensive to do via the nrepl socket.

**Comment by benedekfazekas** [comment]
in theory we could precalculate and cache unused locals. only we need a file save hook or something to refresh this cache... does not feel trivial

**Comment by magnars** [comment]
If they are truly local, as in `let` and function parameters, I guess the way to make it fast would be to figure it out in elisp.

**Comment by benedekfazekas** [comment]
it seems to me now that this should be available already in flycheck clojure via eastwood `:unused-locals` and `:unused-fn-args` only I did not manage to get the flycheck config right to prove. It does rather belong to flycheck too

**Comment by magnars** [comment]
Agreed, that's a fair point. And removing them could still be a
refactoring, like you said.
lør. 28. nov. 2015 kl. 11.21 skrev Benedek Fazekas <notifications@github.com

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
These days it's pretty common to use clj-kondo as a linter, in which case removing the offenders is easy enough
