### ISSUE TITLE
Suggested keybinding conflicts with cider keybindings

### ISSUE THREAD

**Issue by r0man** [clojure-emacs/clj-refactor.el#269]
The README suggest to use the keybinding `(cljr-add-keybindings-with-prefix "C-c C-m")`. However this conflicts with the cider keybinding for `cider-macroexpand-1`. I would suggest to use `C-c C-R`, or another free keybinding.

**Comment by expez** [comment]
I use cljr constantly so I want a prefix that is fast and easy on the hands.  CIDER also has every keybinding with the <kbd>C-c</kbd> prefix covered, so between CIDER and other packages a conflict is all but guaranteed, unless we pick some truly crippling combination.  Additionally, the suggested keybinding has the benefit of not being used very often. Personally I've rebound macroexpand1 to <kbd> C-c m</kbd>, but others might be fine with invoking this using `M-x` on the rare occasion they do debug a macro.

I agree the conflict is unfortunate, but I think the recommendation is solid, and it's trivial for anyone who disagrees to change it.

**Comment by expez** [comment]
We might document that we're shadowing this binding, though.

**Comment by bbatsov** [comment]
> We might document that we're shadowing this binding, though.

Guess this would be enough. Btw, if you want something short and handy you might promote a keybinding using `Super`.

**Comment by expez** [comment]
WIki also updated
