### ISSUE TITLE
Wrong number of arguments error after upgrade cider from 0.9.1 to 0.10.0

### ISSUE THREAD

**Issue by qianyan** [clojure-emacs/clj-refactor.el#270]
The error message in emacs:
nREPL server started on 53310
nREPL: Establishing direct connection to localhost:53310 ...
nREPL: Direct connection established
error in process filter: funcall: Wrong number of arguments: (2 . 2), 1
error in process filter: Wrong number of arguments: (2 . 2), 1

configuration is
```clojure
{:plugins [[refactor-nrepl "2.0.0-SNAPSHOT"]
                             [cider/cider-nrepl "0.10.0"]]
```
And also failed with
```clojure
{:plugins [[refactor-nrepl "1.1.0"]
                             [cider/cider-nrepl "0.10.0"]]
```

**Comment by expez** [comment]
It should work fine with 2.0.0-SNAPSHOT.  Keep in mind you need that version for both refactor-nrepl and clj-refactor.  You can check your version by doing `M-x cljr-version <RET>`.

Probably the package manager messed up when you upgraded.  Try deleting everything related to clj-refactor from `.emacs.d/elpa` (either that whole dir, or at least say every folder with CIDER or clj-refactor in the name), restart emacs and re-install clj-refactor.

**Comment by qianyan** [comment]
I go to `melpa-stable` and try to find the clj-refactor 2.0.0-SNAPSHOT, but there is only 1.1.0 version. where to get the correct one?

**Comment by expez** [comment]
`melpa-stable` only has stable version. The SNAPSHOT isn't stable so it's only availabone on [melpa]( "http://melpa.org/packages/").

Here's my list of package archives, which includes both melpa and melpa-stable

```el
(setq package-archives '(("melpa" . "http://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("elpy" . "http://jorgenschaefer.github.io/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/"))
      package-enable-at-startup nil)
```

**Comment by qianyan** [comment]
I reload emacs after clean clj-refactor-1.0 directory under `.emacs.d/elpa`, then reports this error
`http://melpa.org/packages/clj-refactor-20150623.1219.tar, Not found`.

I search in `melpa.org` and the latest is 20151203.239. two questions there:
1. how it know which version should be downloaded, here, why 20151203.239?
2. why the version number(20151203.239) is really different with 2.0.0-SNAPSHOT?

**Comment by Malabarba** [comment]
> I reload emacs after clean clj-refactor-1.1.0 directory under .emacs.d/elpa, then reports this error http://melpa.org/packages/clj-refactor-20150623.1219.tar, Not found.

Sounds like you just need to refresh your package list. Call M-x list-packages. 

> 2. why the version number(20151203.239) is really different with 2.0.0-SNAPSHOT?

That's just a thing with Melpa.

**Comment by expez** [comment]
> I reload emacs after clean clj-refactor-1.1.0 directory under .emacs.d/elpa, then reports this error
http://melpa.org/packages/clj-refactor-20150623.1219.tar, Not found.

I'm guessing version `clj-refactor-20150623.1219.tar` is the 1.1.0 release from june, so this error occurs because you're asking melpa for a package which only exists on melpa-stable.

> I search in melpa.org and the latest is 20151203.239. two questions there:
1. how it know which version should be downloaded, here, why 20151203.239?
2. why the version number(20151203.239) is really different with 2.0.0-SNAPSHOT?

The version available on melpa is always whatever is on the `master` branch of this github repository.  The version number used by melpa, `20151203.239`, is the date of the snapshot plus something or other which identifies a commit on that date (the part after the `.`).  There has been 226 commits to `master` since we released 1.1.0 so melpa has built 226 packages which all represent 2.0.0-SNAPSHOT with names like 20151203.239.

**Comment by qianyan** [comment]
problem is resolved by these steps
1. clean clj-refactor-1.1.0 directory under `.emacs.d/elpa`
2. add in `("melpa" . "http://melpa.org/packages/")` to `init.el` (in China. VPN needed)
3. reload emacs, fail fast?
4. `M-x list-packages`, search clj-refactor `i` & `x` to install it.

@expez @Malabarba Thanks a ton.

**Comment by expez** [comment]
Glad you got it working, @qianyan!
