### ISSUE TITLE
Rename file is broken with CIDER.0.10.0

### ISSUE THREAD

**Issue by jonpither** [clojure-emacs/clj-refactor.el#278]
using cider/cider-nrepl 0.10.0, refactor-nrepl 1.1.0

cljr--maybe-rethrow-error: Wrong number of arguments: ((cider-buffer-ns cl-struct-nrepl-response-queue-tags t) (request connection &optional abort-on-input) "Send REQUEST to the nREPL server synchronously using CONNECTION.
Hold till final \"done\" message has arrived and join all response messages
of the same \"op\" that came along.
If ABORT-ON-INPUT is non-nil, the function will return nil at the first
sign of user input, so as not to hang the interface." (let* ((time0 (current-time)) (response (cons (quote dict) nil)) (nrepl-ongoing-sync-request t) status) (nrepl-send-request request (function (lambda (resp) (nrepl--merge response resp))) connection) (while (and (not (member "done" status)) (not (and abort-on-input (input-pending-p)))) (setq status (nrepl-dict-get response "status")) (if (member "need-input" status) (progn (cider-need-input (current-buffer)) (setq time0 (current-time))) (if (and nrepl-sync-request-timeout (> (cadr (time-subtract (current-time) time0)) nrepl-sync-request-timeout)) (progn (error "Sync nREPL request timed out %s" request)))) (nrepl-dict-put response "status" (remove "need-input" status)) (accept-process-output nil 0.01)) (if (member "done" status) (progn (let* ((ex (and t (nrepl-dict-get response "ex"))) (err (and ex (nrepl-dict-get response "err")))) (if err (if (member "eval-error" status) (funcall nrepl-err-handler) (cider-repl-emit-interactive-stderr err) (switch-to-buffer-other-window connection)))) (let* ((id (and t (nrepl-dict-get response "id")))) (if id (save-current-buffer (set-buffer connection) (nrepl--mark-id-completed id)))) response)))), 1
user-error: Minibuffer window is not active
Mark set
CIDER 0.10.0

**Comment by expez** [comment]
Upgrade to 2.0.0-SNAPSHOT.  CIDER's API changed substantially when moving to 0.10.0.  This means all communication with the middleware is broken, not just the op related to file renaming.

**Comment by jonpither** [comment]
I'm using refactor-nrepl 2.0.0-SNAPSHOT, CIDER 0.10.0, nREPL 0.2.12 and still get the problem.

**Comment by expez** [comment]
```
Really rename /home/expez/git/test/src/test/core.clj to /home/expez/git/test/src/test/corer.clj? (y or n) y
Rename complete! 2 files affected.
```

Granted I'm running 0.11-SNAPSHOT of CIDER, but that shouldn't matter.

I think I need some more info to go on.  Does this always error for you?  Would the `lein new test` renaming above fail for you?

**Comment by benedekfazekas** [comment]
have you upgraded the elisp client (clj-refactor.el) as well?

**Comment by jonpither** [comment]
I upgraded to clj-refactor.el 2.0.0-SNAPSHOT and it's fixed. 

This does mean that people installing cider and clj-refactor.el from melpa-stable will face the same issue I had (I think). Closing as fixed for me..

**Comment by expez** [comment]
> This does mean that people installing cider and clj-refactor.el from melpa-stable will face the same issue I had (I think). 

Yes, we currently don't have a stable release which works properly with the latest stable CIDER.
