### ISSUE TITLE
add-missing-libspec randon errors

### ISSUE THREAD

**Issue by edipofederle** [clojure-emacs/clj-refactor.el#284]
Hi,

I am trying to use ``add-missing-libspec`` but two different kind of error happens. For exemplo:

If I have this code:

``(str/trim "some string ")``

Then I put the cursor at ``trim`` and call ``add-missing-libspec``, I get:

``mapcar: Wrong type argument: listp, {:name``

Or, if I have this code:

``(defroutes)``

And call ``add-missing-libspec``, I get

``1. Caused by java.lang.RuntimeException
   Unable to resolve symbol: defroutes in this context
  Util.java:  221  clojure.lang.Util/runtimeException``

**note:** The compojure depedency exists on my project.clj

My profiles.clj:

``{:user {:plugins [[cider/cider-nrepl "0.11.0-SNAPSHOT"]
                  [refactor-nrepl "2.0.0-SNAPSHOT"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}``

Any idea here?

Thanks in advance

**Comment by expez** [comment]
Update clj-refactor to the latest version.  A new version of the middleware snapshot was pulled in (automatically) and there's now a version mismatch.
