### ISSUE TITLE
`cljr-clean-ns` removes `:refer :all` namespaces

### ISSUE THREAD

**Issue by voxdolo** [clojure-emacs/clj-refactor.el#285]
This is particularly problematic when running it in a test namespace, where the common idiom is to use `[clojure.test :refer :all]`.

**Comment by voxdolo** [comment]
To expand on the above a bit, I have a ns where I start with this require:

```clj
(:require [clj-time.core :as time]
            [clojure.test :refer :all]
            [com.foo.bar :as bar])
```

and end up with:

```clj
(:require [clj-time.core :as time]
            [com.foo.bar :as bar])
```

After running `cljr-clean-ns`.

**Comment by expez** [comment]
I probably won't be able to reproduce this unless you give me more to go on.

**Comment by voxdolo** [comment]
The `refactor-nrepl` version in my dependencies is: `2.0.0-20160115.115832-17`.

On trying to narrow down to the smallest possible case, I see that there must be some other factors at play. I'll attempt to narrow down to a minimal case and comment again.

**Comment by expez** [comment]
> I'll attempt to narrow down to a minimal case and comment again.

In my experience this can be a lot of work.  A github repo I can clone, or even a gist with an ns where clean-ns misbehaves would be enough.

**Comment by expez** [comment]
Ping @voxdolo

**Comment by voxdolo** [comment]
Hi @expez, sorry, hectic week. Here's a pared-down file I can demonstrate the issue with:

```
(ns ^:automation integration.search-test
  (:require [clj-time.core :as time]
            [clj-time.format :as format]
            [clojure.test :refer :all]
            [integration.test-helpers :as helper]
            [kerodon.core :refer :all]
            [kerodon.test :refer :all]))

(deftest search-provider-is-down
  (let [days-from-now #(format/unparse (format/formatters :date) (time/plus (time/now) (time/days %)))]
    (-> (helper/log-in "user@example.com" "password")
        (choose :.destination "Las Vegas")
        (fill-in :#check_in (days-from-now 30))
        (fill-in :#check_out (days-from-now 33))
        (press "Search Suites")
        (follow-redirect)
        (helper/card-for? "Suitest Hotel EVAR" "Manuel Test Suite"))))
```

After running `cljr-clean-ns` I end up with:

(ns integration.search-test
  (:require [clj-time
             [core :as time]
             [format :as format]]
            [integration.test-helpers :as helper]))

(deftest search-provider-is-down
  (let [days-from-now #(format/unparse (format/formatters :date) (time/plus (time/now) (time/days %)))]
    (-> (helper/log-in "user@example.com" "password")
        (choose :.destination "Las Vegas")
        (fill-in :#check_in (days-from-now 30))
        (fill-in :#check_out (days-from-now 33))
        (press "Search Suites")
        (follow-redirect)
        (helper/card-for? "Suitest Hotel EVAR" "Manuel Test Suite"))))
```

With which there are a few problems:

1. the three necessary `:refer :all` requires are removed
2. `clj-time` namespaces are condensed to a single nested require. I wasn't aware this was a valid syntax, though it seems to work... this seems like it should be configurable (perhaps it is).
3. namespace metadata is removed.

Does this better illustrate the issue?

Thanks!

**Comment by expez** [comment]
This works when the namespace is loaded. We query the running repl in order to figure out referred symbols.  Doing that via static analysis would be hard with impossible edge-cases.  Nevertheless, perhaps we should ensure that the ns is loaded.

1. It removes `kerodon.test` when I try this after loading, but I can't see that that namespace is used.
2. This is called prefix notation and is valid.  See the doc for the ns form.
3. Confirmed.  Definite bug.

Thanks @voxdolo!

**Comment by expez** [comment]
Actually your metadata declaration isn't valid.  When I do `(meta (find-ns 'the-ns))` the return value is `nil`.

If you read the doc for `ns` it says it expects a metadata map.  Here's an example from the refactor-nrepl tests:


````clj
(ns ^{:author "Trurl and Klapaucius"
      :doc "test ns with meta"}
    resources.ns2-meta
  (:require
    [clojure.pprint :refer [fresh-line]]
    [clojure.pprint :refer [get-pretty-writer]]
    [clojure.pprint :refer [cl-format]]
    [clojure.pprint :refer [get-pretty-writer fresh-line cl-format]]
    [clojure.instant :refer [read-instant-calendar]]
    [clojure.instant :refer :all]
    [clojure.test.junit :refer [with-junit-output]])
  (:use clojure.test
        clojure.test
        [clojure.string :rename {replace foo
                                 reverse bar}]
        [clojure.edn :rename {read-string rs
                              read rd}]))
```

**Comment by voxdolo** [comment]
@expez 

1. You're correct about ensuring it's loaded. When I do that, the `:refer :all` requires are preserved properly (`kerodon.test` should have been removed, as I elided the `has` in that test that used it).
2. Is this configurable? It's a significant style change for my application which has _many_ namespaces.
3. That _is_ a valid metadata declaration. When you supply a single metadata key without a value, the default value is set to boolean `true`. see below:

```
user> (ns ^:foobly foo.bar)
nil
foo.bar> (meta (find-ns 'foo.bar))
{:foobly true}
```

**Comment by benedekfazekas** [comment]
for 2. it is, set `(setq cljr-favor-prefix-notation nil)` in your emacs config

**Comment by voxdolo** [comment]
@benedekfazekas cheers!

**Comment by expez** [comment]
@voxdolo I'm sorry, you are right.  I tried adding metadata in this form to test this, but metadata isn't updated when re-evaluating.  It was only visible once I killed the repl and loaded an ns with meta like that from the start.

**Comment by voxdolo** [comment]
@expez my initial issue is resolved. I'm happy to close this and open an issue about the metadata being removed if you like.
