### ISSUE TITLE
Clarity on  `cljr-warn-on-analyzer-needs-eval` and `cljr-warn-on-eval`

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#288]
Not sure if this is a bug, but the README.md states that I only need to set 'cljr-warn-on-analyzer-needs-eval' to `nil` to suppress the warning when the AST needs rebuilding. However, if I set that to `nil`and then `rename-symbol` I still see the prompt. If I also set `cljr-warn-on-eval` to `nil` then I don't.

First - is this correct behaviour? I couldn't grok the relationship between the two.

Second, if that is correct behaviour then the README.md should be updated (happy to do so once I understand more).

**Comment by benedekfazekas** [comment]
Simply forgot to update the README when I renamed the defcustom. Will fix
asap. Thx for catching it!

**Comment by yatesco** [comment]
My pleasure :-).
