### ISSUE TITLE
cljr-add-missing-libspec fails with "Wrong type argument"

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/clj-refactor.el#290]
clj-refactor 20160128.921

I tried to add missing libspec for:

    (render-file "index.html" {}))

which is a selmer function. this is what I get in return:

    Wrong type argument: hash-table-p, (selmer\.parser :ns)

```cljr-add-missing-libspec``` doesn't work no matter which spec I'm trying to add. It ends up always with "Wrong type argument". Project is boot-based and for example above - selmer is definitely in its dependencies.

**Comment by expez** [comment]
upgrade refactor-nrepl so the versions are in sync

**Comment by mbuczko** [comment]
thanks for response.

problem appeared with [refactor-nrepl "2.1.0-alpha1"]. should I downgrade to 2.0.0-snapshot ?

**Comment by expez** [comment]
yes, I think 2.1.0-alpha is something @benedekfazekas is using to test an upcoming feature.  Judging by the erorr you're getting that branch hasn't been synced with master for a while.  The next release will be 2.0.0.

@benedekfazekas we probably shouldn't publish artifacts like that.  Once we go to 2.1.0-SNAPSHOT the alpha release will still be considered more recent.  I think we probably have to skip to 2.2.0-SNAPSHOT once 2.0.0 is out heh

**Comment by mbuczko** [comment]
ok, refactor-nrepl downgraded to 2.0.0-SNAPSHOT and looks like it behaves correctly now.

i'm closing this issue.

one more question though. is cljr-add-missing-libspec limited somehow to clojure sources only, or should it work fine with clojurescripts as well?

**Comment by expez** [comment]
> is cljr-add-missing-libspec limited somehow to clojure sources only, or should it work fine with clojurescripts as well?

It should work with cljs too.  The sources have to be loaded, though.

**Comment by benedekfazekas** [comment]
yup, sorry for the confusion with 2.1.0-alpha I was really eager to be nice to my alpha testers ;). If I remember right you cant really remove artifacts from clojars (will recheck) I might look into sync with master tho and republish it until we release 2.0.0.
