### ISSUE TITLE
cljr-add-missing-libspec doesn't clean namespace after adding spec

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/clj-refactor.el#292]
I tried it few times on different sources and looks like cljr-clean-ns is not invoked after cljr-add-missing-libspec when cljr-auto-clean-ns is set to t.

let's look at following example:

    (ns sample
      (:require [clojure.tools.logging :as log]
                [compojure.core :refer [GET]]))

    (defn init-routes []
      (routes
        (GET "/index.html" [] (log/info "foo"))))

adding missing ```routes``` spec ends up with following ns:

    (ns sample
      (:require [clojure.tools.logging :as log]
                [compojure.core :refer [GET]]
                [compojure.core :refer [routes]]))

and how it looks like after cleaning:

    (ns sample
      (:require [clojure.tools.logging :as log]
                [compojure.core :refer [GET routes]]))

**Comment by expez** [comment]
Ya, I see this too.  Thanks for the report.  `cljr--maybe-clean-ns` needs to be updated with a conditional flushing of the buffer to file.  `clean-ns` acts on the file on disk and so doesn't see the unsaved changes just made to the ns form.

**Comment by mbuczko** [comment]
maybe this is also why sometimes libspec is not really added to ns (even though the the message says otherwise). invoking ```cljr-add-missing-libspec``` again mysteriously helps. I see it rarely and usually can't reproduce for a next few hours.

**Comment by expez** [comment]
Yes, it will replace the ns form (but only if something's actually changed) while not knowing about the libspec that was just added.
