### ISSUE TITLE
Drop the dash.el dep

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clj-refactor.el#294]
Emacs now features `seq.el` (added in 25.1) and `subr-x.el` (added in 24.4), which provide pretty much everything commonly used by `dash.el`. `seq.el` is also a package on GNU ELPA. CIDER already replaced dash and I think it'd be nice if you did this as well.

**Comment by Malabarba** [comment]
Worth noting that seq.el will be built-in starting with Emacs 25. So that's one less dependency for those users.

**Comment by bbatsov** [comment]
Yeah, that's what I meant. I've clarified a bit my original post. I know dash.el is @magnars's baby, but I feel `seq.el` is the way to go forward.

**Comment by expez** [comment]
Pull request welcome

**Comment by slipset** [comment]
Out of curiosity, `dash.el` defines `-partial`which `seq.el` does not define. wat to do?

**Comment by Malabarba** [comment]
Emacs has `apply-partially`. Although a lot of times it's shorter to just write a `lambda`. :-)

**Comment by benedekfazekas** [comment]
woot, woot! 👍
