### ISSUE TITLE
update 20160214.1246 ,error:

### ISSUE THREAD

**Issue by MedusaIDE** [clojure-emacs/clj-refactor.el#295]
> version:20160214.1246
> emacs version:GNU Emacs 25.0.90.3 (x86_64-w64-mingw32)

(setq debug-on-error t)
(package-install 'clj-refactor)

`
Debugger entered--Lisp error: (void-variable cljr-inject-dependencies-at-jack-in)
  (and cljr-inject-dependencies-at-jack-in (boundp (quote cider-jack-in-lein-plugins)) (boundp (quote cider-jack-in-nrepl-middlewares)))
  (if (and cljr-inject-dependencies-at-jack-in (boundp (quote cider-jack-in-lein-plugins)) (boundp (quote cider-jack-in-nrepl-middlewares))) (progn (cljr--inject-jack-in-dependencies)))
  (eval-after-load (quote cider) (if (and cljr-inject-dependencies-at-jack-in (boundp (quote cider-jack-in-lein-plugins)) (boundp (quote cider-jack-in-nrepl-middlewares))) (progn (cljr--inject-jack-in-dependencies))))
  eval-buffer(#<buffer  *load*> nil "d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246/clj-refactor-autoloads.el" nil t)  ; Reading at buffer position 11305
  load-with-code-conversion("d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246/clj-refactor-autoloads.el" "d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246/clj-refactor-autoloads.el" nil t)
  load("d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246/clj-refactor-autoloads" nil t)
  package--activate-autoloads-and-load-path([cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) nil nil "d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246" ((:keywords "convenience" "clojure" "cider")) nil])
  package--load-files-for-activation([cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) nil nil "d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246" ((:keywords "convenience" "clojure" "cider")) nil] :reload)
  package-activate-1([cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) nil nil "d:/MedusaIDE/caches/elpa/clj-refactor-20160214.1246" ((:keywords "convenience" "clojure" "cider")) nil] :reload :deps)
  package-unpack([cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) tar "melpa" nil ((:keywords "convenience" "clojure" "cider")) nil])
  package-install-from-archive([cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) tar "melpa" nil ((:keywords "convenience" "clojure" "cider")) nil])
  mapc(package-install-from-archive ([cl-struct-package-desc inflections (20121016 157) "convert english words between singular and plural" nil single "melpa" nil ((:url . "https://github.com/eschulte/jump.el") (:keywords "ruby" "rails" "languages" "oop")) nil] [cl-struct-package-desc peg (20150707 2341) "Parsing Expression Grammars in Emacs Lisp" nil single "melpa" nil nil nil] [cl-struct-package-desc edn (20150929 146) "Support for reading and writing the edn data format from elisp" ((cl-lib (0 3)) (emacs (24 1)) (dash (2 10 0)) (peg (0 6)) (s (1 8 0))) single "melpa" nil ((:url . "https://www.github.com/expez/edn.el") (:keywords "edn" "clojure")) nil] [cl-struct-package-desc paredit (20150217 713) "minor mode for editing parentheses" nil single "melpa" nil ((:keywords "lisp")) nil] [cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) tar "melpa" nil ((:keywords "convenience" "clojure" "cider")) nil]))
  package-download-transaction(([cl-struct-package-desc inflections (20121016 157) "convert english words between singular and plural" nil single "melpa" nil ((:url . "https://github.com/eschulte/jump.el") (:keywords "ruby" "rails" "languages" "oop")) nil] [cl-struct-package-desc peg (20150707 2341) "Parsing Expression Grammars in Emacs Lisp" nil single "melpa" nil nil nil] [cl-struct-package-desc edn (20150929 146) "Support for reading and writing the edn data format from elisp" ((cl-lib (0 3)) (emacs (24 1)) (dash (2 10 0)) (peg (0 6)) (s (1 8 0))) single "melpa" nil ((:url . "https://www.github.com/expez/edn.el") (:keywords "edn" "clojure")) nil] [cl-struct-package-desc paredit (20150217 713) "minor mode for editing parentheses" nil single "melpa" nil ((:keywords "lisp")) nil] [cl-struct-package-desc clj-refactor (20160214 1246) "A collection of clojure refactoring functions" ((emacs (24 4)) (s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (24)) (multiple-cursors (1 2 2)) (cider (20160208)) (edn (1 1 2)) (inflections (2 3)) (hydra (0 13 2))) tar "melpa" nil ((:keywords "convenience" "clojure" "cider")) nil]))
  package-install(clj-refactor)
  (progn (package-install pkg))
  (if (not (package-installed-p pkg)) (progn (package-install pkg)))
  package-require(clj-refactor)
  eval((package-require (quote clj-refactor)) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

`

**Comment by bcarrell** [comment]
Same error here.

**Comment by benedekfazekas** [comment]
weird. very likely something fishy with my yesterday commit following up a change in Cider to autoinject dependencies at repl start up time.

@bcarrell what is your emacs and cider version pls?
@MedusaIDE what is your cider version?

**Comment by bcarrell** [comment]
Emacs version: `GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6)`
Cider version: Latest MELPA, `20160214.1402`, `Version: 0.11.0-cvs`

**Comment by bcarrell** [comment]
I think the cause is the `eval-after-load` form not quoting the `when`.

**Comment by benedekfazekas** [comment]
yup, thx. pls retest (when gets to melpa or from github)

**Comment by Malabarba** [comment]
I think this will still happen with the quoted version. The problem is that that code is run immediately after cider loads, which means it runs **before** clj-refactor loads. Therefore that variable is not defined yet. 

You need to require clj-refactor before checking the value of cljr-inject-dependencies-at-jack-in.

**Comment by benedekfazekas** [comment]
fixed in `clj-refactor-20160215.1606`
