### ISSUE TITLE
Offer the latest stable version as the default value in -add-project-dependency

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#297]
After choosing the artifact name in `cljr-add-project-dependency`, we are offered a (usually long) list of possible versions.
It would be nice if the latest stable version were used as default value.

For instance, instead of seing this:

```
Version: |
```

We would see this:

```
Version (default 0.2.0): |
```

**Comment by magnars** [comment]
That sounds like a good improvement. Mine already does it, due to some combination of my myriad of ido-packages.

**Comment by expez** [comment]
Same here.  All I do is hit <kbd>RET</kbd> to select the most recent version.

**Comment by Malabarba** [comment]
Sadly, I just tried it and simply hitting `RET` doesn't work on the regular prompt. It sends an empty string.
