### ISSUE TITLE
Should not use C-m for key binding

### ISSUE THREAD

**Issue by PhilipMay** [clojure-emacs/clj-refactor.el#300]
Hello,

C-m is bount to return (new line). This should not be part of the refactoring macros like C-c C-m rs.

**Comment by magnars** [comment]
clj-refactor does not set up any keybindings by default - you choose your own with `cljr-add-keybindings-with-prefix` or `cljr-add-keybindings-with-modifier` - or by adding your own a la carte.

**Comment by PhilipMay** [comment]
So I just add this to the init.el file?
```el
(require 'clj-refactor)

(defun my-clojure-mode-hook ()
    (clj-refactor-mode 1)
    (yas-minor-mode 1) ; for adding require/use/import statements
    ;; This choice of keybinding leaves cider-macroexpand-1 unbound
    (cljr-add-keybindings-with-prefix "C-c C-m"))

(add-hook 'clojure-mode-hook #'my-clojure-mode-hook)
```

**Comment by magnars** [comment]
Note that you have added `C-m` in your init file. Replace it with something else, and you're golden.

**Comment by hoisharka** [comment]
I loaded the clj-refactor package before the cider package, then cider-macroexpand-1 was unbound.
