### ISSUE TITLE
Add project dependencies from custom repository

### ISSUE THREAD

**Issue by javierholguera** [clojure-emacs/clj-refactor.el#303]
`clj-refactor.el` is using `refactor-nrepl`, which seems to support dependency resolution against Maven Central and Clojars only. Is there any way to add project dependencies from other than those repos? Specifically I'd like to be able to configure a company-owned ArtifactoryOnline repo.

Thanks!

**Comment by expez** [comment]
No, this is unfortunately impossible.

I'll accept a PR if you want to work on it, though :)
