### ISSUE TITLE
cljr-slash triggers within keywords

### ISSUE THREAD

**Issue by achesnais** [clojure-emacs/clj-refactor.el#305]
I write lots of Datomic queries which contain keywords with slashes in them (e.g. `:artist/name`), and I wish cljr-slash didn't trigger each time I wrote one as it interrupts for a noticeable instant my typing flow.

I see that cljr uses `cider-in-comment-p` and `cider-in-string-p` to decide on whether it must trigger. I wonder if one could add a check for keywords as well?

**Comment by expez** [comment]
Thanks for the report, the current situation is clearly unacceptable!

**Comment by benedekfazekas** [comment]
having second thoughts about this. a namespaced keyword needs a require so triggering `cljr-slash` is the right behaviour. only the `:` char is not stripped from the beginning of the prefix so it never finds the aliases it should.

**Comment by Malabarba** [comment]
>  a namespaced keyword needs a require

Only if it uses a double-colon (`::`). If there's a single `:` then the prefix is **not** an alias.
