### ISSUE TITLE
Allow `sut` alias to be customized

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#312]
I use the letter `o` for aliasing the original code namespace in test files. It would be nice if the current `sut` alias were a variable I could customize.

By the way, what does `sut` stand for?

**Comment by magnars** [comment]
It is already customizable. There's a defcustom to change the entire thing. :)

SUT is System Under Test.

**Comment by magnars** [comment]
https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L199

**Comment by Malabarba** [comment]
>It is already customizable. There's a defcustom to change the entire thing. :)

Maybe I'm missing it, but I don't see a way to customize sut in any of those variables. :-(
In fact, [line 1027](https://github.com/clojure-emacs/clj-refactor.el/blob/master/clj-refactor.el#L1027) would lead to believe it is hardcoded.

>SUT is System Under Test.

I see. Thanks. :-)

**Comment by magnars** [comment]
Ah, doh. It's everything else that's customizable. Sorry about that.
søn. 20. mar. 2016 kl. 23.50 skrev Artur Malabarba <notifications@github.com
