### ISSUE TITLE
clj-refactor-20160303.536.tar: Not found

### ISSUE THREAD

**Issue by antonharald** [clojure-emacs/clj-refactor.el#319]
When trying to install clj-refactor via M-x package-install I get this:

https://melpa.org/packages/clj-refactor-20160303.536.tar: Not found

What could be the reason for this? I'm using emacs 24.4.1 on linux mint

**Comment by expez** [comment]
melpa doesn't store old snapshots, I think.  The latest snapshot is `20160329.331`.  As to why your emacs is requesting an old snapshot, I don't know.

**Comment by bbatsov** [comment]
Stable package db. Do `package-refresh-packages` and try again.
