### ISSUE TITLE
Can't find reader macros

### ISSUE THREAD

**Issue by caioaao** [clojure-emacs/clj-refactor.el#320]
Refactors that need to run the project fail with the following error (full stack trace [here](https://github.com/clojure-emacs/clj-refactor.el/files/198275/stacktrace_readerm.txt) - file paths were removed):
```
error in process filter: cljr--get-error-value: Error in nrepl-refactor: java.util.concurrent.ExecutionException: clojure.lang.ExceptionInfo: No reader function for tag time {:type :reader-exception, :line 31, :column 30, :file "..."}
```
I've printed the value from `*data-readers*` in CIDER repl and the macros are being declared correctly. Everything else works fine (running tests, loading code to CIDER, etc).
Idk if it's related or not, but the macros are declared in other projects. I've tried copying the `data_readers.clj` file from those project to the one I'm working, but it didn't work either.
Versions used:
- cider: 20160216.440
- clj-refactor: 20160329.331
- cider-nrepl: 0.11.0-SNAPSHOT
- refactor-nrepl: 2.2.0-SNAPSHOT

**Comment by benedekfazekas** [comment]
pls upgrade to latest snapshots (cider 0.12.0-SNAPSHOT and clj-refactor 2.3.0-SNAPSHOT) just to rule out that this is related to this mranderson issue: benedekfazekas/mranderson#12

**Comment by expez** [comment]
Also, is this with leiningen?

**Comment by caioaao** [comment]
@benedekfazekas looks like that issue was fixed in 2.2.0. Anyway, I tested it with the versions you said and the error is the same.
yes @expez, I'm using leiningen here

**Comment by caioaao** [comment]
Looks like the error was fixed, but another one appeared: 
[stacktrace_readerm.txt](https://github.com/clojure-emacs/clj-refactor.el/files/209275/stacktrace_readerm.txt)
As this is related to refactor-nrepl, should I reopen the issue there instead of here?

**Comment by expez** [comment]
> Looks like the error was fixed

I published the latest snapshot after you posted this message so I'm not sure you actually ran a new version.

> but another one appeared: 
stacktrace_readerm.txt

In the future, could you please link to a gist, so I don't have to download a file to view stacktraces?

> As this is related to refactor-nrepl, should I reopen the issue there instead of here?

Yes, that would be great!

Thanks for taking the time to report issues!
