### ISSUE TITLE
Tracking down clj-refactor-breaking clojure code

### ISSUE THREAD

**Issue by sgrove** [clojure-emacs/clj-refactor.el#329]
Running `clj-refactor 2.0.0, refactor-nrepl 2.0.0` (may be fixed already, will check after posting bug. EDIT: updated, but it just times out now. Probably something local to our project.)

Running e.g. `cljr-find-usages` will find a few usages of a symbol in our project, but will eventually fail without enough info to track down the offending file/form:

```
error in process filter: cljr--maybe-rethrow-error: clojure.lang.ExceptionInfo: Unreadable form {:type :reader-exception}
error in process filter: clojure.lang.ExceptionInfo: Unreadable form {:type :reader-exception}
```

In the `*nrepl-messages localhost*` buffer, I see e.g.:
```
(<-- 
  error  "clojure.lang.ExceptionInfo: Unreadable form {:type :reader-exception}"
  id  "23"
  session  "7d2550a0-c9a0-4f3d-a17f-02e1ef6a21f6"
  status  ("done")
)
```
## Expected behavior
Enough info to find out where the problem is coming from.

## Steps to reproduce the problem
Put an unreadable form somewhere in your project and run `cljr-find-usages`

## Environment & Version information
`clojure 1.8`

**Comment by benedekfazekas** [comment]
Can you please retest with latest stable (2.2.0) or latest master.

**Comment by expez** [comment]
Usually the location information is preserved in the error thrown.  I'm not sure what's causing it to be omitted, but this definitely isn't how it's supposed to work.

> Can you please retest with latest stable (2.2.0) or latest master.

IIUC he edited in that he tried and that and the result was that the request just timed out instead.

**Comment by benedekfazekas** [comment]
whoops thanks, missed that (no notifications about description updates apparently)

having a hard time to reproduce this tbh. wonder how come whatever causes this exception loads at all (assuming you are using some form of reloaded workflow)

**Comment by expez** [comment]
> wonder how come whatever causes this exception loads at all (assuming you are using some form of reloaded workflow)

Might be a difference between the clj reader and the tools.reader reader.

**Comment by expez** [comment]
I can't reproduce this on the latest snapshot.  Here's what I get:

```
error in process filter: refactor-nrepl is unable to build an AST for refactor-nrepl.ns.prune-dependencies. tools.analyzer encountered the following problem: Unreadable form
```

That's the right file where I added the unreadable form.  Attempting to load that file into the repl gives me further help in tracking down exactly where the problem is.
