### ISSUE TITLE
Add-require doesn't jump back

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#331]
1. Move to the end of the file.
1. Invoke add-require.
2. TAB twice.
3. Type a namespace.
4. TAB a few more times to finish the snippet.

No matter how many times I TAB, I'm left at the ns form. I always have to manually move back to were I was in the file.

If I'm the only one experiencing this, let me know which functions I can debug to get to the bottom of it. :+1:

**Comment by magnars** [comment]
I tried this in my Emacs now, and pressing TAB the last time took me back to where I was.

Is the snippet ever exited when you press TAB? If so, maybe there's something wrong with the hook or the return function. If not, that sounds like a yasnippet issue. Do you use yasnippet outside of cljr?

**Comment by Malabarba** [comment]
>Is the snippet ever exited when you press TAB? 

Do you know how I could check this?
I definitely don't see a shaded background, but it's possible some variable isn't getting cleared.

**Comment by magnars** [comment]
I have no idea how that worked for me, but clj-refactor was using an old `yas/` prefixed version of the hook. I changed it to the new `yas-` prefix. Let me know if that solves your issue.

**Comment by Malabarba** [comment]
That didn't fix it for me. I'll look into my hooks to see what's stopping it.

**Comment by Malabarba** [comment]
here we go. `(cljr--assert-leiningen-project)` in `cljr--maybe-sort-ns` signals an error and aborts the process. Looks like it would work better as a regular predicate inside the `when` instead of an assertion.

**Comment by expez** [comment]
@Malabarba are on you on boot, then?  I'm pretty sure we don't need to assert leiningen here.  It should work on boot too.  Perhaps the fix is to just remove that assertion?

**Comment by Malabarba** [comment]
Yes, I'm on boot. And indeed `cljr--clean-ns` works fine for me.
