### ISSUE TITLE
Add #_ reader form 

### ISSUE THREAD

**Issue by agzam** [clojure-emacs/clj-refactor.el#334]
Clojure's `#_` (Ignore next form reader macro) is very useful. Would be very cool to have a function and a dedicated key binding to toggle it. 

My initial attempt looks like this:

    (defun cljr-toggle-ignore-next-form ()
      "Ignore next form (#_)"
      (interactive)
      (if (search-backward "#_" 2 t 1)
	  (delete-char 2)
	(progn
	  (let ((fc (following-char)))
	    (cond ((-contains? '( ?\) ?\] ?\} ) fc) (paredit-backward-up))
		  ((-contains? '( ?\( ?\[ ?\: ?\{ ) fc) nil)
		  (t (beginning-of-thing 'sexp)))
	    (insert "#_")))))

What do you guys, think?

**Comment by expez** [comment]
I personally use [this](http://endlessparentheses.com/a-comment-or-uncomment-sexp-command.html) a lot, but I guess I can see this being useful.  

@benedekfazekas has done some fantastic work in moving our elisp-only refactorings over to `clojure-mode`.  We might considering implementing this feature over there straight away.

**Comment by benedekfazekas** [comment]
I like the idea although I use @Malabarba's hack too quoted by Lars. Agree
with him: factor out paredit and see what @Malabarba and @bbatsov think
about it.

**Comment by Malabarba** [comment]
I too use the comment-sexp function linked above, but I know a lot of people prefer the #_ reader macro, so I'd be fine with adding something like this to Clojure mode. 
It needs a bit of work though. 
Currently if you try to comment a form but there's already a commented form higher up in the file it will go there and uncomment it instead.

**Comment by bbatsov** [comment]
I'm fine with adding something like this to clojure-mode, but it definitely needs some polish. I'm guessing we can add a variant of it for the `comment` macro as well (although using paredit wrapping & unwrapping with some form is not complex at all).

**Comment by agzam** [comment]
Guys, `comment-sexp` and this are different things. This guy would force Clojure's Reader to ignore any form that follows this macro

**Comment by Malabarba** [comment]
Commenting a sexp with semi colons is the same thing as commenting it with #_, isn't it?

**Comment by bbatsov** [comment]
Yep, it is. Commenting with `comment` results in a `nil` return value.

**Comment by agzam** [comment]
according to the docs http://clojure.org/reference/reader
> The form following #_ is completely skipped by the reader. (This is a more complete removal than the comment macro which yields nil)

**Comment by Malabarba** [comment]
@agzam I think you misunderstood us. :-)
The comment-sexp command we all talked about uses semi-colons to comment out (or uncomment) a sexp. It has exactly  the same effect as using #_. It has nothing to do with Clojure's `(comment ...) ` macro. You can follow the link expez posted to see it in action. 

Nonetheless, like  I said, your proposal would be a fine addition to Clojure-mode, just as long as we fix the issue when removing the #_.

**Comment by agzam** [comment]
@Malabarba no, I get it, it works for sexps but for something like this:  
 ```
(foo [a b #_c] )
...
```
semicolons make it difficult

 ```
(foo [a b
;c
]
....)
```

**Comment by Malabarba** [comment]
> Honestly I'm starting to think that default comment operator in clj/cljs/cider-repl modes should always comment with #_ and only use semicolons when block of lines region is selected

If you're referring to the behaviour of commands like `M-;` (which is an Emacs built-in), then I think it would be nice to have a command that uses `#_` if the region exactly encompasses a sexp, but while using `;;` if the region encompasses something more general.
Unfortunately, I think that would be a little too complicated to implement (mostly because it would have to seamlessly support UNcommenting both of those syntaxes).

OTOH, having a separate command to comment/uncomment a sexp with `#_` is much simpler and seems like a fine compromise to me.

**Comment by agzam** [comment]
@Malabarba oh, I'm excited, I guess it's possible to make it smart enough. 

- Is there a way to check if the thing-at-point commented without having to search backwards for either `;` or `#_`?

**Comment by Malabarba** [comment]
For ;; comments you can use `syntax-ppss`, but I don't think it'll work for #_. 
You may also want to have a look at [this command](http://endlessparentheses.com/a-comment-or-uncomment-sexp-command.html). It's a pretty good example of how complicated it can be to determine _what_ needs to be uncommented. And that doesn't even account for #_. 

I think our efforts would be better spent adding your command above. :-)

**Comment by benedekfazekas** [comment]
@agzam it seems there was a really promising discussion here and also an agreement that this should be rather implemented in clojure-mode. Shall I close this here? has it perhaps made to clojure-mode already?

**Comment by Malabarba** [comment]
Yeah, we should move the issue to Clojure mode, even if no one is ready to implement it.

**Comment by benedekfazekas** [comment]
migrated to clojure-mode
