### ISSUE TITLE
No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentVector

### ISSUE THREAD

**Issue by Mestelan** [clojure-emacs/clj-refactor.el#335]
I get this error after invoking cljr-rename-symbol. Am I doing anything wrong?
Extract from my *messages* buffer:

To perform this op the project needs to be evaluated.
  Analyzing a large project might take a while: hit C-g to abort.
  (Set cljr-warn-on-eval to nil to analyze the project without warning)
  Do you want to proceed? (y or n) y
(No changes need to be saved)
Fetching symbol occurrences...
if: Error in nrepl-refactor: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentVector
 at java.util.concurrent.FutureTask.report (FutureTask.java:122)
    java.util.concurrent.FutureTask.get (FutureTask.java:192)
    clojure.core$deref_future.invokeStatic (core.clj:2208)
    clojure.core$future_call$reify__6962.deref (core.clj:6688)
    clojure.core$deref.invokeStatic (core.clj:2228)
    clojure.core$deref.invoke (core.clj:2214)
    refactor_nrepl.find.find_symbol$find_symbol.invokeStatic (find_symbol.clj:242)
    refactor_nrepl.find.find_symbol$find_symbol.invoke (find_symbol.clj:235)
    refactor_nrepl.middleware$find_symbol_reply.invokeStatic (middleware.clj:60)
    refactor_nrepl.middleware$find_symbol_reply.invoke (middleware.clj:57)
    refactor_nrepl.middleware$wrap_refactor$fn__13923.invoke (middleware.clj:135)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    clojure.tools.nrepl.middleware.session$add_stdin$fn__774.invoke (session.clj:238)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.refresh$wrap_refresh$fn__19171.invoke (refresh.clj:172)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.track_state$wrap_tracker$fn__19692.invoke (track_state.clj:201)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.pprint$wrap_pprint$fn__11649.invoke (pprint.clj:108)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.complete$wrap_complete$fn__15223.invoke (complete.clj:38)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    clojure.tools.nrepl.middleware.pr_values$pr_values$fn__611.invoke (pr_values.clj:22)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.test$wrap_test$fn__19334.invoke (test.clj:286)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.stacktrace$wrap_stacktrace$fn__11719.invoke (stacktrace.clj:174)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    cider.nrepl.middleware.pprint$wrap_pprint_fn$fn__11623.invoke (pprint.clj:50)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    clojure.tools.nrepl.middleware.session$session$fn__759.invoke (session.clj:192)
    clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__424.invoke (middleware.clj:22)
    clojure.tools.nrepl.server$handle_STAR_.invokeStatic (server.clj:19)
    clojure.tools.nrepl.server$handle_STAR_.invoke (server.clj:16)
    clojure.tools.nrepl.server$handle$fn__830.invoke (server.clj:28)
    clojure.core$binding_conveyor_fn$fn__4676.invoke (core.clj:1938)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.PersistentVector
 at clojure.core$_cache_protocol_fn.invokeStatic (core_deftype.clj:568)
    clojure.java.io$fn__9390$G__9372__9395.invoke (io.clj:35)
    clojure.java.io$file.invokeStatic (io.clj:424)
    clojure.java.io$file.invoke (io.clj:418)
    refactor_nrepl.core$find_in_dir.invokeStatic (core.clj:89)
    refactor_nrepl.core$find_in_dir.invoke (core.clj:80)
    refactor_nrepl.find.find_symbol$find_global_symbol.invokeStatic (find_symbol.clj:139)
    refactor_nrepl.find.find_symbol$find_global_symbol.invoke (find_symbol.clj:132)
    refactor_nrepl.find.find_symbol$find_symbol$fn__10004.invoke (find_symbol.clj:238)
    clojure.core$binding_conveyor_fn$fn__4676.invoke (core.clj:1938)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)

---
clj-refactor 2.3.0-SNAPSHOT (package: 20160501.434), refactor-nrepl 2.3.0-SNAPSHOT

;; CIDER 0.12.0 (Seattle), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_91

### Leiningen or Boot version
Leiningen 2.6.1 on Java 1.8.0_91 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2015-03-07 on trouble, modified by Debian

### Operating system
Debian GNU/Linux Jessie

**Comment by expez** [comment]
Hi

This isn't a known bug.  Do you have a public repo available where this problem happens, so we can reproduce it?

**Comment by Mestelan** [comment]
It happens on a rather simple clojure file. I will provide a minimal example tonight.

**Comment by Mestelan** [comment]
It actually happens on any clojure file I test; including this most simple one:
(defn square [n]
  (* n n))

(defn fib-iter [n]
  (defn fib-iter-countdown [countdown a b p q]
    (cond (= 0 countdown) a
          (even? countdown) (fib-iter-countdown (/ countdown 2) a b
                                                (+ (square p) (square q))
                                                (+ (* 2 p q) (square q))
                                                )
          :else (fib-iter-countdown (- countdown 1 )
                                    (+ (* a (+ p q)) (* b q))
                                    (+ (* b p ) (* a q))
                                    p q)))
  ;; the basic procedure is a special case of p=0, q=1
  (fib-iter-countdown n 1 0 0 1))

**Comment by expez** [comment]
The error message is a bit confusing, but this happens because you're running the refactoring on a file without a namespace form.

The refactorings are intended for large projects, with a particular structure, and use a build tool.  I'm guessing you're going to run into a lot more problems if you try to use the more advanced refactorings (those that require our middleware) on your sicp exercises.

On our wiki there'a list of refactorings, with stars (IIRC) next to the ones that require the middleware.  You should be able to use most of the other refactorings.

**Comment by Mestelan** [comment]
I understand now; thanks for attention and patience.
