### ISSUE TITLE
Aborting cljr-move-form loses code

### ISSUE THREAD

**Issue by mtnygard** [clojure-emacs/clj-refactor.el#340]
## Expected behavior

When aborting an incomplete move-form refactoring (or _any_ refactoring, for that matter!) I expect my code to be as it was before I started the operation. That is, an incomplete refactoring should have no effect on my code.
## Actual behavior

As soon as cljr-move-form is invoke, the form is killed from the original buffer. THEN the prompt is displayed. If the operation is aborted by the user or fails due to targeting a file that is opened as a read-only buffer, the form is gone.

(Although it can be recovered with undo, this is hardly a desirable user experience!)
## Steps to reproduce the problem

Begin moving a form to a new namespace with C-a C-c mf. While in the minibuffer with the prompt, abort the operation with C-g. Observe that the form is lost.
### clj-refactor.el version information

clj-refactor 2.2.0, refactor-nrepl 2.2.0
### CIDER version information

CIDER 0.12.0 (Seattle)
### Leiningen or Boot version

```
#http://boot-clj.com
#Sun Jul 31 13:26:32 CDT 2016
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_CLOJURE_VERSION=1.9.0-alpha8
BOOT_VERSION=2.6.0
```
### Emacs version

```
GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-05-28 on coil.local
```
### Operating system

OS X 10.11 "El Capitan"

**Comment by expez** [comment]
Adding undo, and handling <kbd>C-g</kbd> in the middle of a refactoring, is a huge amount of work.  I'd absolutely love that feature, but unfortunately I don't have as much time to invest in this project anymore.

**Comment by benedekfazekas** [comment]
I will have a closer look on this and all new issues after holidays etc around end of August.

**Comment by benedekfazekas** [comment]
looking at `undo-tree` to buy a solution for this but really half heartedly. deffo don't want to add an extra dependency to the package (still can support an undo feature optionally if `undo-tree` is available)

tbh to do as much as actual changing files as possible in the client (clj-refactor.el case: emacs) and not in the middleware was a conscious decision to mitigate undo and similar problems. this particular case can be perhaps solved by either using vcs (git/magit etc) or emacs built in undo facility.

I also think that the `bug` and `enhancement` labels are kinda contradicting ;) I am inclined towards enhancement.

**Comment by Malabarba** [comment]
You could wait and only remove the code after promoting the user. This won't solve the problem when Emacs fails to write the target file, but it would at least allow the use to cancel the prompt without a nasty surprise. :-)

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
> Adding undo, and handling C-g in the middle of a refactoring, is a huge amount of work. I'd absolutely love that feature, but unfortunately I don't have as much time to invest in this project anymore.

This seems the correct resolution for this issue (particularly looking at ts date)

In general it's a good habit to use Git `add`/`commit` judiciously prior to any refactoring (with any tool!).
