### ISSUE TITLE
Find symbols representing keywords in a keyworded map globally

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/clj-refactor.el#343]
So if keyworded maps are destructured in the parameter list of a defn we can globally find these and possibly rename them.

**Comment by expez** [comment]
How is this any different from grep/replace?  A destructured `name` somewhere might be the name of a person in one context but the name of an artifact somewhere else.  So if we renamed every `name` we'd be doing the wrong thing.

I don't see how we can do anything unless the keyword is namespaced and at that point grep/replace does exactly the same thing.

**Comment by benedekfazekas** [comment]
hm.. you might be right. closing this then.
