### ISSUE TITLE
Find usages error on lein-bikeshed code

### ISSUE THREAD

**Issue by doubleagent** [clojure-emacs/clj-refactor.el#348]
Screenshot shows all the details I have.  I commented out virtually all the code, saved, killed and restarted cider a few times.  The error occurs during project analysis.  Something to do with leiningen plugins, maybe?

![cider_bikeshed_find_usages_err](https://cloud.githubusercontent.com/assets/56522/19178515/f4788e0e-8c18-11e6-8ffb-1e45d1ff741d.png)

**Comment by benedekfazekas** [comment]
can't really replicate this. I checked out `dakrone/lein-bikeshed` added clojure 1.7 as a dependency (that may not be necessary). when i jacked in I had `bikeshed.core-test` in a bad state due the free text line at the end of the namespace. mind you that should not cause problems with finding/renaming in the rest of the namespaces in the project. after i commented this line out even that error went away.

would be helpful to know what versions you are using (`M-x cider-version` and `M-x cljr-version` might help)

**Comment by expez** [comment]
The stacktrace would also be helpful!

**Comment by doubleagent** [comment]
The problem was with the free text line in `bikeshed.core-test`.  Apologies for wasting your time @benedekfazekas , you're a saint for trying to reproduce.

This taught me that clj-refactor prints errors to the _*Messages*_ buffer.
