### ISSUE TITLE
Feature request: add an arity to a function

### ISSUE THREAD

**Issue by exupero** [clojure-emacs/clj-refactor.el#349]
By default I define functions as

```clojure
(defn func [arg]
  body)
```

Adding an arity to such a function requires

1. Wrapping the existing arglist and body in parens,
2. Inserting a set of parens, and
3. Defining a new arglist.

This is the most tedious refactoring I regularly do, and seems like a good candidate for a clj-refactor operation. I don't have any suggestions for how such an operation ought to work; any automated system ought to beat doing it manually.

**Comment by bbatsov** [comment]
Sounds like a good idea (and like something that can probably be done in `clojure-mode` directly).

**Comment by Malabarba** [comment]
I believe there's already a command about editing function signature.

**Comment by benedekfazekas** [comment]
there is. but I don't think it can add a new version of the function with
diff number of arities..

**Comment by expez** [comment]
Yeah, this would be something else, and way more basic.

I think this is a good idea, I find this operation tedious too, and I second the notion that we might put it in clojure-mode directly.

**Comment by benedekfazekas** [comment]
migrated over to clojure-mode
