### ISSUE TITLE
a way to rename a directory of clj files

### ISSUE THREAD

**Issue by AlexBaranosky** [clojure-emacs/clj-refactor.el#35]
This could probably be build on to of `cljr-rename-file` :)

**Comment by expez** [comment]
Am I missing anything here?

1. Create/rename dir
2. Move each file
3. Update the ns form of each affected ns to match new directory structure
4. Update all ns statements in namespaces using the namespaces we moved
5. Update any fully qualified references to vars in the affected namespaces

Anything I'm missing?  If people are reading and evaling strings then they're on their own, obviously.

1-4 seem trivial, 5 seems like a good use-case for our new ast powers.
