### ISSUE TITLE
Project evaluation doesn't seem to work with tramp

### ISSUE THREAD

**Issue by erno** [clojure-emacs/clj-refactor.el#350]
## Expected behavior

I invoked the rename-symbol refactoring on a project that I was editing over
tramp. I expected this to do a refactoring without crashing.
## Actual behavior

After prompting about "the project needs to be evaluated" I got an
exception like "if: Error in nrepl-refactor: java.io.FileNotFoundException: /scp:username@remotehost:/home/mydev/my-something/src/clj/my-something/handler.clj (No such file or directory)"
## Steps to reproduce the problem

I tried it on another project over tramp and got a similar failure, so I assume
this is straightforward.
### clj-refactor.el version information

clj-refactor 2.2.0, refactor-nrepl 2.2.0
### CIDER version information

```
;; CIDER 0.12.0 (Seattle), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_91

```
### Leiningen or Boot version

Leiningen 2.7.0 on Java 1.8.0_91 OpenJDK 64-Bit Server VM
### Emacs version

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian
### Operating system

Ubuntu 16.04.1 LTS

**Comment by benedekfazekas** [comment]
hm.. this is related to #181 and #286 I think. wonder if relative paths would be a possible fix here...

**Comment by maxfurman** [comment]
@benedekfazekas I might work on a PR for this, since I'm having the same problem, but I'm not sure what I'd need to change to enable relative paths. If you don't mind, could you please pointing me in the right direction? Thanks.

**Comment by benedekfazekas** [comment]
The difficulty with this one that it is not really the elisp client (clj-refactor.el) that needs to be able to access these files but the clojure backend implemented as a [nrepl middleware](https://github.com/clojure-emacs/refactor-nrepl). As this feature (rename symbol, find symbol) depends on analyzing the whole project with `tools.analyzer`.

For this reason we look for the project files and filter them as well making sure they are actually on the classpath etc. See [refactor-nrep.ns.tracker](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/ns/tracker.clj) and [refactor-nrepl.core](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/core.clj) for details.

**Comment by benedekfazekas** [comment]
my comment wasn't meant as discouraging.  hopefully you are rewriting the analyzing bit in refactor-nrepl atm. let me know if I can help ;) btw what is your use case for working on files over tramp?

**Comment by erno** [comment]
I think the repl related processes are already running on the remote host, so maybe the issue
is just stripping out the tramp syntax from the paths?

**Comment by expez** [comment]
If the middleware is already running on the remote host it has to be modified to strip away the network part of the path and then put it back when sending the result back.

Feel free to submit a patch if either of you want to maintain that functionality.

Closing this for now, as the issue will stay open until the project dies otherwise.
