### ISSUE TITLE
"Invalid token" during cljr-clean-ns for keywords with namespace aliases

### ISSUE THREAD

**Issue by Peeja** [clojure-emacs/clj-refactor.el#353]
## Expected behavior

Namespace form should be cleaned with no errors.
## Actual behavior

`clojure.lang.ExceptionInfo: Invalid token: ::foo/bar`

Sounds like `::foo/bar` is being evaluated without the `foo` alias in place.
## Steps to reproduce the problem

Run `cljr-clean-ns` in a namespace containing:

``` clj
(ns my-app.core
  (:require [foobar.core :as foo]))

::foo/bar
```
### clj-refactor.el version information

```
clj-refactor 2.3.0-SNAPSHOT (package: 20160524.146), refactor-nrepl 2.3.0-SNAPSHOT
```
### CIDER version information

```
;; CIDER 0.13.0snapshot (package: 20160524.714), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_51
```
### Leiningen or Boot version

```
Leiningen 2.5.3 on Java 1.8.0_51 Java HotSpot(TM) 64-Bit Server VM
```
### Emacs version

24.4.1
### Operating system

OS X 10.9.5

**Comment by expez** [comment]
You need to load the namespace into the repl or it won't be able to resolve the alias.  Once that is done it should work correctly.

Several people have been tripped up by this lately.  `clean-ns` is run so frequently I'm not sure prompting for a load would be a good either, though.  

Let me know if that does it for you.

**Comment by Peeja** [comment]
Oh, I see. I can't do that: I'm in ClojureScript. Is there any way around that?

**Comment by expez** [comment]
Should work in that way for cljs too.  

We might have a bug in cljs, then.

**Comment by unkelly** [comment]
I ran into this problem trying to use `cljr-find-usages`. The offending instance is outside of the namespace I'm running in. I guess the project analysis isn't smart enough to load each namespace before analyzing?

**Comment by unkelly** [comment]
Oh nice, running `cider-load-all-project-ns` prior to refactoring solves it 👍

**Comment by Peeja** [comment]
@expez Huzzah! Thank you!
