### ISSUE TITLE
Change the default of cljr-favor-prefix-notation to false

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#363]
The default is currently `t`.

Back in the day my argument in favor of this was one of readability.  Whenever I had to reference the ns form that job was made quicker by this grouping.

My arguments for changing it now are the following:

* It reduces [greppability](http://john.freml.in/grep-orientated-programming) because you can't easily find out where a namespace is in use by searching for its name.
* cljs is now a thing and it doesn't support prefix notation at all, so we don't use it anyway in cljs files or in cljc files.

**Comment by jsab** [comment]
This is in line with @stuartsierra's [How to ns](https://stuartsierra.com/2016/clojure-how-to-ns.html). It would be great if clj-refactor.el would support the format proposed in the article. At this time I run the [how-to-ns](https://github.com/gfredericks/how-to-ns) plugin after using clj-refactor.
