### ISSUE TITLE
Optional dependencies?

### ISSUE THREAD

**Issue by Pitometsu** [clojure-emacs/clj-refactor.el#364]
Can this plugin be useful without hydra and paredit? I prefer `guide-key` and `smartparens` over them.

**Comment by benedekfazekas** [comment]
in summary yes it could be but that would require some work. hydra we use for improving  discoveribility if you choose to opt out and run you own similar feature that should be fine. paredit we use to navigate clj/cljs code internally tho.

this could be refactored so we use elisp core functions for navigation. not trivial but doable work (PR welcome ;) ).
also you don't have to use paredit if you use clj-refactor you can use smartparens I appreciate you still need to install it as a dependency.

hope this helps.

**Comment by magnars** [comment]
I don't agree about the "PR welcome" for convoluting our internals. Our
usage of paredit in no way stops other people from using smartparens.
søn. 5. mar. 2017 kl. 09.32 skrev Benedek Fazekas <notifications@github.com

**Comment by expez** [comment]
> I don't agree about the "PR welcome" for convoluting our internals. 

Yeah, this is just likely to create subtle bugs without much benefit.

I also prefer `smartparens`, and use it daily, and it causes no interference with clj-refactor.

**Comment by benedekfazekas** [comment]
there would be of course a very realistic risk of introducing regressions with such a PR. on the flip side I have to do this migration (from paredit navigation to elisp core functions for navigation) when I port features over to `clojure-mode`/`cider`. that is said I don't deny that there is probably more valuable and more fun things to look at if @Pitometsu is willing to invest more energy here and put together a PR (which @Pitometsu has not yet said ;) )

**Comment by magnars** [comment]
> on the flip side I have to do this migration (from paredit navigation to elisp core functions for navigation) when I port features over to clojure-mode/cider

Ack, what a waste of time. Are people not able to install more than one emacs package? Why spend time on porting stuff into the already humongous CIDER, when we could be fixing bugs and adding features to clj-refactor instead?

**Comment by bbatsov** [comment]
> Ack, what a waste of time. Are people not able to install more than one emacs package? Why spend time on porting stuff into the already humongous CIDER, when we could be fixing bugs and adding features to clj-refactor instead?

Because a lot more people would use them if bundled with clojure-mode or CIDER. That's a recurring discussion at every conference I attend - people don't want to install a ton of packages - they want to install one and be done with it.

**Comment by magnars** [comment]
Wow, that just puts a giant question mark on my face. How exactly would such a conversation unfold? I'd like to ask those people "Would you like us to spend time on bugfixes and features, or would you like us to consolidate everything into a single package so that you don't have to type M-x package-install more than a single time?"

**Comment by benedekfazekas** [comment]
haha @magnars i hear you. I also changed (hopefully improved) them a bit here and there. I have the impression people mostly don't even really realise that cider and cljr are different packages -- and they don't really have to either if they use spacemacs for example. also cljr visibility is much lower than cider's which is both natural i guess but still a shame...

**Comment by bbatsov** [comment]
Yeah, that's pretty much the case. Also some people had some negative experiences with cljr a while back a decided to drop the ball on it and wait for CIDER to eventually adopt its useful features (as after a discussion some time ago I mentioned at a few conferences that a subset of the cljr functionality would end up in CIDER eventually).

Btw, I still believe that this is the way to go - if something useful and relatively simple it should live in `clojure-mode` or `cider`. The features that @benedekfazekas moved to clojure-mode benefited all the `inf-clojure` users out there and there are plenty of them these days, as it's a popular way to work with planck and lumo.
