### ISSUE TITLE
Support for renaming ns aliases

### ISSUE THREAD

**Issue by lvh** [clojure-emacs/clj-refactor.el#366]
Especially with new syntax in Clojure 1.9 for making namespaced maps easier to use, including e.g. `#::x{:a 1}` and `{::x/keys [a b c]}`, this is becoming a more and more useful feature that's tricky to write the correct regex alternative for.

**Comment by bbatsov** [comment]
Seems this should go to clojure-mode.

**Comment by lvh** [comment]
I have no particular opinion on where it lives; I use both anyway :D Why should this go in clojure-mode? I figured since it's renaming...

**Comment by bbatsov** [comment]
> I have no particular opinion on where it lives; I use both anyway :D Why should this go in clojure-mode? I figured since it's renaming...

Most refactoring commands that were Elisp only were moved there, so more people would have access to them. Anyways, discard my initial comment - I misread what this ticket was about.

**Comment by anthonygalea** [comment]
@bbatsov I think this issue can be closed as it was done in https://github.com/clojure-emacs/clojure-mode/pull/529

**Comment by bbatsov** [comment]
Yeah, totally.
