### ISSUE TITLE
CLJ-R no longer works in .cljs/.cljc files

### ISSUE THREAD

**Issue by Nollo** [clojure-emacs/clj-refactor.el#370]
## Expected behavior

Working in a .cljs or .cljc file

## Actual behavior

```
To perform this op the project needs to be evaluated.
  Analyzing a large project might take a while: hit C-g to abort.
  (Set cljr-warn-on-eval to nil to analyze the project without warning)
  Do you want to proceed? (y or n)
``` 
y

`cljr--maybe-rethrow-error: Only .clj files are supported!`

## Steps to reproduce the problem

- Open a .cljs file
- Select a piece of code
- Try do call `cljr-extract-function`

## Environment & Version information
GNU Emacs 25.2.1 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76) of 2017-02-09
Spacemacs: develop branch
CIDER: 0.15.0-snapshot
clj-refactor: 0.2.3-snapshot
clojure/tools.repl: 0.2.12
Leiningen 2.7.1 on Java 1.8.0_111 Java HotSpot(TM) 64-Bit Server VM

Starting nREPL server via /usr/local/bin/lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.12\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.0-SNAPSHOT\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.15.0-SNAPSHOT\"\] -- repl :headless :host ::...

**Comment by expez** [comment]
cljs and cljc are largely lacking support for more advanced refactorings.  It's always been this way, so this isn't a bug.

Thankfully, someone has shown interest in helping us out: https://github.com/clojure-emacs/refactor-nrepl/issues/195

**Comment by Nollo** [comment]
Damn I didn't see these issue before creating this one. Thanks for clarification.
