### ISSUE TITLE
Inflections 2.3 doesn't exist anymore?

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-refactor.el#375]
https://stable.melpa.org/packages/inflections-2.3.el (which clj-refactor declares a dep on) gives a 404. https://stable.melpa.org/packages/inflections-2.4.el is available

**Comment by expez** [comment]
@purcell Any idea what's happening here?

**Comment by purcell** [comment]
Yes. We don't keep old packages on MELPA Stable currently, so it's really more like an archive of the latest stable version. Why would you need a specific old version? Emacs will always install the highest available version anyway.

**Comment by expez** [comment]
@vemv this seems to be a normal situation, were you unable to install clj-refactor?

**Comment by vemv** [comment]
Yes I am unable, I get this:

![image](https://cloud.githubusercontent.com/assets/1162994/25853772/2d4eac64-34ce-11e7-89a3-061510658437.png)

Cheers - Victor

**Comment by vemv** [comment]
I guess that updating `;; Package-Requires:  [...] (inflections "2.3") ` to 2.4 would fix this as well, given that `Emacs will always install the highest available version anyway` isn't true for me, for whatever reason

**Comment by purcell** [comment]
> given that Emacs will always install the highest available version anyway isn't true for me, for whatever reason

Do you have something in your `package-pinned-packages` variable?

**Comment by vemv** [comment]
Nope, I have it set to nil

**Comment by vemv** [comment]
Fixed with:

```diff
-(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
+(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
```

I wasn't aware of this distinction or that this part of my emacs setup was using a bad choice.

Cheers - Victor

**Comment by purcell** [comment]
> Fixed with:

That's a workaround rather than a fix, to be fair. It's still not clear why the problem was happening.
