### ISSUE TITLE
Magic imports

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#38]
When I type `(io/` I'd like clj-refactor to import `clojure.java.io` automatically. Maybe it should optionally prompt me first.

On the list are at least:
- `str` to `clojure.string`
- `io` to `clojure.java.io`
- `set` to `clojure.set`

Any other ideas?

**Comment by elmehalawi** [comment]
Can you guys explain how to use this for an emacs noob? What is "ar" and "mi"?

**Comment by vemv** [comment]
The abbreviations are listed in https://github.com/clojure-emacs/clj-refactor.el/wiki and are https://github.com/abo-abo/hydra shortcuts

**Comment by elmehalawi** [comment]
@vemv I see, thank you for that. I tried M-x and looking for functions called `clj-refactor-*`, and was confused when I didn't find any. Should have read those docs more carefully.

**Comment by vemv** [comment]
No issue! Many people like those Hydra shortcuts, but using e.g. `M-x cljr-add-missing-libspec` also works and might suite others' preferences.
