### ISSUE TITLE
cljr-remove-let gives error "unable to build as AST, no namespace: user found"

### ISSUE THREAD

**Issue by oskarkv** [clojure-emacs/clj-refactor.el#381]
I'm not sure if this is an error in cljr-refactor, or on my end. Nevertheless it's an issue for me and I don't understand the problem.

## Steps to reproduce the problem

I tried to use `cljr-remove-let` on the code below. I did a `cider-refresh` right before and it succeeded. My cursor was at the inner `outer-border`.
```
(defn border [poses]
  (let [outer-border (unsafe-outer-border poses)]
    (math/union (apply cross-neighbors outer-border) poses)))
```

## Expected behavior

The let disappears and the outer-border expression is inlined.

## Actual behavior

I got the error:

"refactor-nrepl is unable to build an AST for game.tile-sets. tools.analyzer encountered the following problem: No namespace: user found"

Note that the code was in `game.tile-sets`. A `user` namespace exits. `cider-refresh` succeeded.

### clj-refactor.el version information

clj-refactor 2.3.0-SNAPSHOT (package: 20170520.323), refactor-nrepl 2.3.0-SNAPSHOT

### CIDER version information

;; CIDER 0.15.0snapshot (package: 20170525.255), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_131

### Emacs version

25.2.2

**Comment by benedekfazekas** [comment]
any chance you can share the project you are experiencing this with?

**Comment by oskarkv** [comment]
No, sorry.

But today it works. I haven't changed much about the project, but I did restart Emacs (and everything else).

**Comment by benedekfazekas** [comment]
this is a close then. feel free to reopen if this reoccurs and you have more info on what causes it
