### ISSUE TITLE
FR: exclude some requires/imports from `cljr-clean-ns`

### ISSUE THREAD

**Issue by yatesco** [clojure-emacs/clj-refactor.el#382]
I couldn't see any 'prior art' for this so apologies if this is a duplicate.

I sometimes have some namespaces that need to be imported but aren't directly used. JDBC drivers, cljsjs packages etc. I also frequently use `cljr-clean-ns` which sees they are unused and removes them.

Would it be possible to teach `cljr-clean-ns` to ignore certain requires and imports? Maybe by attaching some meta-data to the specific require/import statements?

How do others solve this problem, and it seems like a common scenario?

Thanks!

**Comment by expez** [comment]
> I couldn't see any 'prior art' for this so apologies if this is a duplicate.

[Someone started working on this](https://github.com/clojure-emacs/refactor-nrepl/pull/189), by adding metadata like you suggested.

> How do others solve this problem, and it seems like a common scenario?

I've occasionally put an additional `(require 'whatever)` below the ns form, with a comment explaining that it's to avoid stupid tooling problems :p

**Comment by expez** [comment]
Please re-open if this still leaves you in the lurch!

**Comment by yatesco** [comment]
That's perfect @expez - thanks!
