### ISSUE TITLE
cljr-clean-ns: Wrong number of arguments: (0 . 0), 1

### ISSUE THREAD

**Issue by robert-stuttaford** [clojure-emacs/clj-refactor.el#386]
## Expected behavior

On invoking `M-x clean-ns`, the ns form is cleaned.

## Actual behavior

On invoking `M-x clean-ns`, the following error message is displayed in the minibuffer:

```
cljr-clean-ns: Wrong number of arguments: (0 . 0), 1
```

## Steps to reproduce the problem

Put this into a `scratch.clj` file in the root of your classpath, connect a REPL, and compile the buffer:

```
(ns scratch
  (:require [clojure.string :as str]))
```

Invoke `M-x clean-ns`.

### clj-refactor.el version information

clj-refactor 2.4.0-SNAPSHOT (package: 20170608.320), refactor-nrepl 2.3.1

### CIDER version information

CIDER 0.15.0snapshot (package: 20170719.1212), nREPL 0.2.12
Clojure 1.8.0, Java 1.8.0_121

### Leiningen or Boot version

Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-17

### Operating system

macOS Sierra 10.12.5 (16F73)

**Comment by expez** [comment]
This seems strange.  Where's the argument to `cljr-clean-ns` coming from?  You sure you didn't accidentally use a prefix argument, or that some other package adds one?

**Comment by malchmih** [comment]
Started happening to me recently too. Just using `cljr-clean-ns` as usual. Can it be somehow connected to https://github.com/clojure-emacs/refactor-nrepl/commit/d56b67694aba4d140260256cb7dee7656ebe37f6 (just a wild guess though)?

**Comment by robert-stuttaford** [comment]
Thanks folks. @expez how do get the right bits onto my machine? I've redownloaded Maven deps and emacs packages, to no avail. Or do I need to keep my eyes peeled for a new release, or a new SNAPSHOT release?

**Comment by benedekfazekas** [comment]
just guessing but you may have an `elc` file lurking around?!

**Comment by expez** [comment]
@robert-stuttaford you just need the last version of `clj-refactor` from melpa.

If you're already pinned to the latest (unstable release) then it might be an old `.elc` file like @benedekfazekas suggested.

Suppose we might cut a release soon, as this might hit more people as they upgrade.

**Comment by camdez** [comment]
👍  for a new MELPA Stable release; I'm also getting bitten by this one. Thanks, all.

**Comment by benedekfazekas** [comment]
@expez do you want to cut 2.3.2, or? i guess we could from current HEAD...

**Comment by benedekfazekas** [comment]
for the record duplicate of #clojure-emacs/refactor-nrepl#204

**Comment by MartinSoto** [comment]
I continue to see 2.3.1 in MELPA Stable. Did you guys release a new version?

**Comment by benedekfazekas** [comment]
no we have not I am afraid. `2.3.1` is still the latest stable. new version is available as latest snapshot only

**Comment by MartinSoto** [comment]
:-(

**Comment by skuro** [comment]
@benedekfazekas any chance you guys can cut a new release now? it has been some time that the fix is available in the MELPA unstable package.
