### ISSUE TITLE
Error message when loading clr-refactor

### ISSUE THREAD

**Issue by fvides** [clojure-emacs/clj-refactor.el#387]
## Expected behavior
Load without error messages

## Actual behavior
Whenever (require 'clj-refactor) there is an error:
Eager macro-expansion failure: (error "Unknown upattern `(quote nil)'")

Apparently everything works fine, but I report this anyway so the development team can evaluate if is a harmless manifestation of a deeper or potentially problematic bug.

## Steps to reproduce the problem
1. Start emacs
2. Eval (require 'clj-refactor)

## Environment & Version information

All emacs packages installed from melpa-stable and dependences are met.

### clj-refactor.el version information
2.3.1
The problem is also present in melpa package 20170720.712

### CIDER version information
```
;; Connected to nREPL server - nrepl://localhost:36567
;; CIDER 0.15.0 (London), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_111
```

### Leiningen or Boot version
Leiningen 2.7.1 on Java 1.8.0_111 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian

### Operating system
Ubuntu Linux 16.04 LTS

**Comment by benedekfazekas** [comment]
thanks! will have a look... guessing an unintended incompatibility with emacs 24...

**Comment by expez** [comment]
Is this still happening @fvides?  I can't reproduce in 25.1.1.  If you're still seeing this then i guess @benedekfazekas is right, and it's a regression in our emacs 24 compatibility.

**Comment by fvides** [comment]
@expez Is not happening anymore, I just checked. The only relevant change in dependencies is Cider 0.15.1 vs 0.15.0 and a minor update in java itself. Many thanks!
