### ISSUE TITLE
Feature request: cljr-ns-template

### ISSUE THREAD

**Issue by arrdem** [clojure-emacs/clj-refactor.el#390]
It'd be awesome if users could customize the template that gets inserted to blank files. For instance I'd like to be able to opt into a template along the lines of

```
(ns %s
  "FIXME: docstring goes here"
  {:author ["Reid McKenzie <me@arrdem.com>"]}
  (:require [clojure.core.match :as m]))
```

This does of course kinda beg the issue of using a real snippets library but here we are.

**Comment by expez** [comment]
> This does of course kinda beg the issue of using a real snippets library but here we are.

cljr already uses a real snippet library, `yasnippet`, under the hood so this shouldn't be that hard to do.

It would probably be a good idea to test this with `.dir-locals.el` to enable per-project customization of snippets too.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
PR welcome adding a defcustom for this string https://github.com/clojure-emacs/clj-refactor.el/blob/a06d33d26320967136656514d4c9d37d16727bab/clj-refactor.el#L1138

Other than that, this issue is too old to track atm
