### ISSUE TITLE
Can clj-refactor.el degrade cleanly outside a project context?

### ISSUE THREAD

**Issue by raxod502** [clojure-emacs/clj-refactor.el#391]
By default, when I enable `clj-refactor-mode` in all `clojure-mode` buffers as recommended, and I start a `M-x cider-jack-in`, I receive the following in the `*cider-repl*` buffer:

```
WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.4.0-SNAPSHOT and n/a, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.
```

And I receive the following in the `*nrepl-server*` buffer:

```
Warning: refactor-nrepl needs to run in the context of a project.
Warning: refactor-nrepl middleware won't be activated.
Warning: refactor-nrepl needs to run in the context of a project.
Warning: refactor-nrepl middleware won't be activated.
Warning: refactor-nrepl needs to run in the context of a project.
Warning: refactor-nrepl middleware won't be activated.
Warning: refactor-nrepl needs to run in the context of a project.
Warning: refactor-nrepl middleware won't be activated.
```

However, none of this is useful. Of course since I ran `M-x cider-jack-in` outside the context of a project, refactor-nrepl won't be available. I would like the option to suppress all warnings related to the situation, without also suppressing warnings from actual erroneous behavior.

The message in `*cider-repl*` suggests to customize `cljr-suppress-middleware-warnings`. However:

* that will suppress legitimate warnings about e.g. the wrong Clojure version being used, or refactor-nrepl can't be loaded when inside a project context
* it doesn't suppress the warnings in `*nrepl-server*`

The correct solution, in my opinion, is to _not inject refactor-nrepl at all_ unless the predicate `(cljr--project-dir)` returns non-nil. I have a [rather elaborate hack](https://github.com/raxod502/radian/blob/ee92ea6cb0473bf7d20c6d381753011312ef4a52/radian-emacs/radian-clojure.el#L339-L401) in my init-file to accomplish exactly this, but I think it'd be a better experience for all users if such behavior were the default.

**Comment by expez** [comment]
> However, none of this is useful.

It might not be useful for an expert like yourself, but it's super useful for beginners who otherwise can't understand why their refactoring tool isn't working. It's also very useful for @benedekfazekas and myself when we don't have to answer support questions.  When the tool doesn't work they show up on gitter and say "The refactorings aren't working" and then we have to go through a whole list of possible stuff that can be wrong :/

> The correct solution, in my opinion, is to not inject refactor-nrepl at all unless the predicate `(cljr--project-dir)` returns non-nil. 

This is what happens today.  `refactor-nrepl` isn't even on the classpath in these situations.

What is your use-case where this is causing you grief?  What clojure code are you writing a lot of without being in the context of a project?

I disagree strongly about changing the defaults, because I think this hits so few people and beginners especially are the ones that would be hurt by a change.  I'd be totally cool with having another setting/option to permanently suppress that one warning about not having a middleware, though.  

That being said, clj-refactor doesn't really add much value without the middleware running.  @benedekfazekas has done a fantastic job of moving the code that doesn't require the middleware to `clojure-mode` where it's more widely available.

**Comment by raxod502** [comment]
> This is what happens today.

Not really, though. `refactor-nrepl` is still injected; it is just not activated after connection. And this is why there are warnings. I'm looking at the following code:

```
;;;###autoload
(defun cljr--inject-jack-in-dependencies ()
  "Inject the REPL dependencies of clj-refactor at `cider-jack-in'.
If injecting the dependencies is not preferred set `cljr-inject-dependencies-at-jack-in' to nil."
  (when (and cljr-inject-dependencies-at-jack-in
             (boundp 'cider-jack-in-lein-plugins)
             (boundp 'cider-jack-in-nrepl-middlewares))
    (add-to-list 'cider-jack-in-lein-plugins `("refactor-nrepl" ,(cljr--version t)))
    (add-to-list 'cider-jack-in-nrepl-middlewares "refactor-nrepl.middleware/wrap-refactor")))

;;;###autoload
(eval-after-load 'cider
  '(cljr--inject-jack-in-dependencies))
```

The problem appears to me that `cljr-inject-dependencies-at-jack-in` is only a boolean, and can't capture behavior such as "only inject the dependencies if we are inside a project".

> What is your use-case where this is causing you grief? What clojure code are you writing a lot of without being in the context of a project?

I frequently will spin up a REPL to do some computation, much as people use Python as a calculator.

> I disagree strongly about changing the defaults

Fair enough. Can there be an option, though? The reason that the default behavior seems odd for me is that _every time_ you start a REPL outside a project, you get warning messages—which would imply there is something inherently wrong with your setup. But the issue is, that situation is produced by the default recommended configuration when starting a REPL outside a project, which is an explicitly supported mode of operation by CIDER.

> That being said, clj-refactor doesn't really add much value without the middleware running.

Well, I'd be fine with not enabling `clj-refactor` when we're outside a project, but I'm not sure there's a good way to do that. It's not like I can `(add-hook 'clojure-mode-when-inside-a-project-hook #'clj-refactor-mode)`, especially given that `clj-refactor` adds `refactor-nrepl` to the `cider-jack-in-lein-plugins` _globally_ in an _autoload_. Do you have any suggestions?

**Comment by expez** [comment]
> Can there be an option, though? 

Yes, but it might be a lot of work and/or make the code much more complex to the point where it wouldn't be worth upstreaming and maintaining that code forever.  

I suspect the path of least resistance is to just add a few lines of code to your .emacs:

```el
(defun maybe-activate-clj (oldfun &rest args)
  (if (cljr--project-dir)
      (funcall oldfun args)
    (let ((cider-jack-in-lein-plugins `(("cider/cider-nrepl" ,(upcase cider-version))))
          (cider-jack-in-nrepl-middlewares ("cider.nrepl/cider-middleware")))
      (funcall oldfun args))))

(advice-add 'cider-jack-in :around #'maybe-activate-cljr)
```

I didn't test this, and there are for sure cleaner ways to get the default middleware without hardcoding the list, but I think you get the general idea.

This will cause the middleware to not even run, so it won't emit the warning about being started in a context it doesn't like.

You should probably do a `setq-local` on `cljr-suppress-middleware-warnings` to selectively disable it in these buffers too to get rid of the last warnings you're indifferent to.

**Comment by raxod502** [comment]
> it might be a lot of work, and/or make the code much more complex to the point where it wouldn't be worth upstreaming and maintaining that code forever.

I created #392, which implements this feature request. I actually think it makes the code simpler, since no longer is `clj-refactor` changing variables globally within an autoload.

Note that the default user experience is unchanged, except that only one warning ("you're not inside a project, so refactor-nrepl won't work") is printed instead of five. It is now possible to suppress the remaining warning, as well. Furthermore, refactor-nrepl is no longer injected at all when outside a project context, which will improve REPL startup performance.
