### ISSUE TITLE
package-install fails - hydra-0.13.6.tar not found

### ISSUE THREAD

**Issue by skbach** [clojure-emacs/clj-refactor.el#393]
M-x package-install
clj-refactor

fails with message:

http://stable.melpa.org/packages/hydra-0.13.6.tar: Not found.

Using Emacs 24.4.1 on Debian.  Have added melpa and melpa-stable to 'package-archives.

**Comment by expez** [comment]
The latest stable is `0.14`, which is why that one is no longer available.

Can you see if you have any pinned packages?  

The emacs package version numbers are just minimum requirements, so you should just get `0.14` instead...
