### ISSUE TITLE
Possible to improve the user-facing performance of cljr-slash?

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-refactor.el#395]
Hi!

cljr-slash works great for me, however it can block Emacs for a few seconds resulting in a somewhat frustrating experience.

Consider what I have to do for getting `clojure.string` inserted, and `str/last-index-of` completed:

* Type `str/` `<TAB>`
* Wait ~5 seconds of Emacs freeze
* type `last-ind`
* type `<TAB>` for `ex-of` completion.

---

Wouldn't it be more effective to:

* Type `str/` `<TAB>`
* Have the `cljr-slash` run in background (not sure what's the status of async work in elisp. Doesn't cider/nrepl do this?)
* background work hasn't finished yet, but I especulatively type `last-ind`
* background work has finished, which I know because `[clojure.string :as str]` has been just inserted into the ns form
* I type `<TAB>` and have the fn name completed.

Hope it sounds possible / like a good idea!

Cheers - Victor

**Comment by vemv** [comment]
Another possibility, I guess, is that one could improve the performance of the completion backend so a synchronous request is quick enough.

One could especulatively build a cache in the JVM side?

* Traverse `cljr-magic-require-namespaces`
* For each entry, do the work and cache it for this nrepl

I don't know much the implementation details, just throwing ideas

**Comment by expez** [comment]
Hi

This doesn't sound good!

Could you give me some more details about your setup?

One of our clojure projects at work is 40k lines of code and I've never experienced `cljr-slash` taking more than a few milliseconds, on a laptop from last year.

What's your computer like?  SSD/HDD?  What's your project like?  Thousands of clj files?  Millions of files that that aren't clojure files in the same directory?  etc

**Comment by vemv** [comment]
I should have noted that my project is a Clojurescript one!

* 504 clojurescript files from the project itself, normal layout
* ~20 javascript dependencies in project.clj
* SSD, decent macbook air
* Emacs setup:

```
cider-20171001.112
clj-refactor-20170720.712
clojure-mode-20170819.2159
paredit-20170405.1149
```

**Comment by expez** [comment]
In the clj repl, opened in the project that's slow, could you do:

```clj
(do
 (in-ns 'refactor-nrepl.ns.libspecs)
 (dotimes [_ 2] 
    (time (namespace-aliases)))
 nil)
```
In the largest clj project at work (40 kloc) this gives me `"Elapsed time: 111.696427 msecs"`

The aliases are cached on per-file basis, based on the last modification time, so we're doing this twice to see the effect of cached vs uncached.

Might also be interesting to see where it spends the majority of its time:

```
(time (dorun (core/find-in-project (some-fn core/clj-file? core/cljc-file?))))
```

and 
```
(time (dorun (core/find-in-project (some-fn core/cljs-file? core/cljc-file?))))
```

**Comment by vemv** [comment]
Start up emacs from scratch, start up cider nrepl:

![image](https://user-images.githubusercontent.com/1162994/32271978-838c03d4-befc-11e7-9bd8-f36016034428.png)

In the same session:

![image](https://user-images.githubusercontent.com/1162994/32272032-addea77c-befc-11e7-9e71-b94c4ab77eae.png)

I tried out `cljr-slash` after running these and there's still freeze (2 seconds).

I did the following:

* Open x.cljs
* cljr-slash for `str/`, 2 seconds
* Close and reopen x.cljs
* cljr-slash for `str/` takes again 2 seconds

5 was worst-case scenario, 2 is the more usual one.

**Comment by expez** [comment]
Aight.  Thanks for timing this!  Few observations:

1. After the initial cache refactor-nrepl has the result after ~600ms.
2. Findling cljs files takes 5 times as long as finding clj files.
3. There are 1-4 seconds of work that is unaccounted for.

We can probably solve 2) and get the time to get the result down to between 100 and 200ms, but that still leaves 3), which is the biggest time waster of all.

Perhaps reading the data over on the emacs side is taking a long time?

How many are there?

```clj
(do
  (in-ns 'refactor-nrepl.ns.libspecs)
  (-> (namespace-aliases)
      (update :clj  (comp count seq))
      (update :cljs  (comp count seq))))
```

**Comment by vemv** [comment]
Thanks so much for the support!

These are the stats:

`{:clj 24, :cljs 542}`

**Comment by expez** [comment]
That's twice as many as I have in my largest clj project, but that still shouldn't cause a huge slowdown in terms of serialization, I don't think.

can you do `(setq nrepl-log-messages t)` and then keep an eye on the `*nrepl-log-messages*` buffer as you trigger a `cljr-slash`?  Is the majority of the delay really after the response from the middleware?  If so, it's work in Emacs that takes a long time.

To figure out what it's doing you can do <kbd> M-x toggle-debug-on-quit</kbd> and hit <kbd> C-g </kbd> while it's working to get a stacktrace.

**Comment by vemv** [comment]
After `(setq nrepl-log-messages t)` I can only see a new `*nrelp-messages cljs <project-name>*` buffer, is it this one?

![image](https://user-images.githubusercontent.com/1162994/32282203-428b253e-bf21-11e7-9382-b9c9edeb44d1.png)

Keeping an eye on this buffer, I see that the messages come at the same exact time than cljr-slash finishes.

In other words:

* I press /
* Emacs freezes, no new messages at all for a few seconds
* Messages come, at the same moment cljr-slash is done.

---

I tried the C-g trick. Output:

```
Debugger entered--Lisp error: (quit)
  accept-process-output(nil 0.01)
  nrepl-send-sync-request(("op" "namespace-aliases" "prefix-rewriting" "false" "debug" "false") #<buffer *cider-repl CLJS horizon*> nil)
  cider-nrepl-send-sync-request(("op" "namespace-aliases" "prefix-rewriting" "false" "debug" "false"))
  cljr--call-middleware-sync(("op" "namespace-aliases" "prefix-rewriting" "false" "debug" "false") "namespace-aliases")
  cljr--call-middleware-for-namespace-aliases()
  cljr--get-aliases-from-middleware()
  cljr--magic-requires-lookup-alias()
  cljr-slash()
  funcall-interactively(cljr-slash)
  call-interactively(cljr-slash nil nil)
  command-execute(cljr-slash)
```

Hope it helps!

**Comment by expez** [comment]
So the middleware works for around 1 second, there's a delay of a few seconds, and then emacs completes its job instantly. 

Unless you're connected to a remote repl over a dialup connection or a remote repl on a secret lunar base I'm not sure what else this could be.

**Comment by vemv** [comment]
I'll try creating a couple artificial projects with less cljs files, curious to see how perf varies

**Comment by vemv** [comment]
I used this ruby code to bloat any given cljs project:

```ruby
def code name
  %|
  (ns assign.#{name})
  (defn foo [] \"#{name}\")
  (defn bar [] \"#{name}\")
  (defn foo1 [] \"#{name}\")
  (defn foo2 [] \"#{name}\")
  (defn foo3 [] \"#{name}\")
  (defn foo4 [] \"#{name}\")
  (defn foo5 [] \"#{name}\")
  (defn foo6 [] \"#{name}\")
  |
end

i = 0

('a'..'z').each do |a|
  ('a'..'z').each do |b|
    ('a'..'z').each do |c|
      i += 1
      break if i > 1000
      name = "#{a}#{b}#{c}"
      File.write("#{name}.cljs", code(name))
      puts "[assign.#{a}#{b}#{c}]" # print something you can :require later
    end
  end
end;1
```

With this, cljr-slash perf will decrease by a 1.5 seconds (measured with a macro).

In the end, cljr is using the sync api. As long at it gave you no problems I can understand this, however, when CIDER already offers an async api and problems in cljs do exist, it becomes reasonable to make the command async (or offer opt-in `cljr-slash-async`)

Hope you could give it a shot!

Eventually I can try it myself.

Cheers - Victor

**Comment by expez** [comment]
Yes, but this is all cached, so after the first `/` performance should be back to nearly instant.  This is what I'm seeing in my daily use.

I'd rather fix performance issues than move from sync to async, because you're losing a lot of context and predictability if the require prompt appears randomly later.  Presumably that'll interrupt you while you're typing the variable name and you'll lose time having to erase the text that get mistakenly entered into the 'select require prompt' and then re-type it back in to the file.

I still don't know where the missing time is spend.  We've established that the cljs code path of the analysis is slower than the clj part, but we could only get that to take up around 1s.  If you're seeing up to 5 seconds that means the majority of the work is still unaccounted for.

Thanks for investing time in this, it's very much appreciated.  It's so frustrating when users are suffering and we've no idea why!

**Comment by magnars** [comment]
Could the time be spent parsing the large dataset?

**Comment by benedekfazekas** [comment]
I see similarly slowness/freeze on my work machine (windows, additional security checks on every file operation -- don't ask...) which known to be horribly slow with file system ops. magit is just unusable for example.

amazing work here btw expez, vemv!

**Comment by expez** [comment]
> Could the time be spent parsing the large dataset?

When @vemv tested, the message was received in the nrepl message buffer and then the result appeared instantly.  The message in this buffer is the raw thing, before it's handed off to `edn.el` and eventually `clj-refactor`.  Unless I'm wrong about the order of things here, then I don't think it's the parsing that's taking forever.

> I see similarly slowness/freeze on my work machine (windows, additional security checks on every file operation -- don't ask...) which known to be horribly slow with file system ops. magit is just unusable for example.

I have similar experiences with windows :/

**Comment by magnars** [comment]
Since it is sync, maybe both visible results - nrepl message buffer update
and the resulting prompt - both happen after all computation is complete,
and not when they are performed in the code?

**Comment by vemv** [comment]
Thanks all for the research!

When I have the chance I'll try to send equivalent messages to `nrepl-send-sync-request` isolatedly and see what the response time is. If it's constantly e.g. 1.5 seconds there's not much to do, right?

**Comment by vemv** [comment]
> I'd rather fix performance issues than move from sync to async, because you're losing a lot of context and predictability if the require prompt appears randomly later. Presumably that'll interrupt you while you're typing the variable name and you'll lose time having to erase the text that get mistakenly entered into the 'select require prompt' and then re-type it back in to the file.

I see. However 95% of times I don't expect cljr-slash to prompt me for a namespace, but rather infer it. In that case there would be no interruptions.

Hypothetically one could make an async command that only has an effect if the ns can be inferred. That might be far-fetched though, more of a thing for me to implement if really wanted!

**Comment by expez** [comment]
> When I have the chance I'll try to send equivalent messages to `nrepl-send-sync-request` isolatedly and see what the response time is.

:+1: 

>  If it's constantly e.g. 1.5 seconds there's not much to do, right?

It was more of a 'first things first'.  I don't think 1.5 seconds is acceptable.  We had some issues in the past where configuration files were included for analysis so when we look for files in the project we also check for an ns form (instead of just file extensions).  That seems to work fine for clj, but for some reason doing that on the cljs files takes 5 times longer.  Fixing that will probably be part of the answer to your problem, but until we can account for the remaining seconds it won't really improve the situation much :(

**Comment by vemv** [comment]
> When I have the chance I'll try to send equivalent messages to nrepl-send-sync-request isolatedly and see what the response time is.

Will do this as soon as I have the chance, been a bit busy for this kind of thing sorry!

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
cljr-slash is pretty fast these days :)
