### ISSUE TITLE
Destructure keys (dk): handle two arguments with identical keys

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-refactor.el#398]
Hi there!

Given the following form:

```
(defn foo [a b]
  [(:quux a) (:quux b)])
```

If I `dk` with the cursor over `a` in the arg vector, it will result in

```
(defn foo [{:keys [quux]} b]
  [quux (:quux b)])
```

That seems kinda correct but also error-prone to me. If now I repeated the process while having the cursor placed over `b` in the arg vector, it'd result in:

```
(defn foo [{:keys [quux]} {:keys [quux]}]
  [quux quux])
```

Which is ambiguous.

---

I'd propose that if it is detected that if a given :keyword is used over more than one argument, then the resulting destructuring uses the argument name as a prefix.

Example:

```
(defn foo [a b]
  [(:quux a) (:quux b)])
```

Would result in

```
(defn foo [{a-quux :quux} b]
  [a-quux (:quux b)])
```

, which then could be `dk`'d again into

```
(defn foo [{a-quux :quux} {b-quux :quux}]
  [a-quux b-quux])
```

WDYT?

Cheers - Victor

**Comment by expez** [comment]
Why not?

I can't say that this is a big pain-point for me, but the proposed behavior seems better to me.

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
I'm not super interested in this feature anymore.

Probably these days I would write the code like this (by hand) instead:

```clj
(defn foo [{a-q :quux} {b-q :quux}]
  [a-q b-q])
```
