### ISSUE TITLE
cljr-rename-symbol: Doesn't work with Java 9

### ISSUE THREAD

**Issue by em7** [clojure-emacs/clj-refactor.el#399]
Hello, I saw similar issue here but the solution "make sure you are running the latest versions" unfortunately did not help. I have a clean install of Emacs and all packages are freshly downloaded from melpa. Nonetheless I get this error.

**This happens only when run on Java 9. I've tried with Java8_144 and it worked OK.**

BTW Guys, thank you! You're doing a great job developing this project!

## Expected behavior

When running cljr-rename-symbol command with cursor on a function name (both in a form calling a function or in a defn) I want the function to be renamed and all the calling code updated, assuming I have cider connected/jacked in.

## Actual behavior

After I run the command with cursor on a function name, this is displayed in a minibuffer:

```
To perform this op the project needs to be evaluated.
Analyzing a large project might take a while: hit C-g to abort.
(Set cljr-warn-on-eval to nil to analyze the project without warning)
Do you want to proceed? (y or n) y
Fetching symbol occurrences...
cljr-rename-symbol: Wrong type argument: char-or-string-p, nil
```

### clj-refactor.el version information

`clj-refactor 2.4.0-SNAPSHOT (package: 20171117.317), refactor-nrepl 2.4.0-SNAPSHOT`

### CIDER version information

```
;; CIDER 0.16.0snapshot (package: 20171126.150), nREPL 0.2.12
;; Clojure 1.9.0-RC2, Java 9
```

### Leiningen or Boot version

Leiningen 2.8.1 on Java 9 Java HotSpot(TM) 64-Bit Server VM

### Emacs version

GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-26

### Operating system

Windows 7, 64 bit

**Comment by expez** [comment]
https://github.com/clojure-emacs/refactor-nrepl/issues/206

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by vemv** [comment]
refactor-nrepl >= 3.x.x is certainly support all JDKs.
