### ISSUE TITLE
Support for SPIRAL

### ISSUE THREAD

**Issue by ccann** [clojure-emacs/clj-refactor.el#405]
It would be great to have support for [SPIRAL](https://github.com/Unrepl/spiral) in addition to CIDER as the backend that enables some of the refactoring functionality.

**Comment by bbatsov** [comment]
See also https://github.com/Unrepl/spiral/issues/5

I think down the road a library like orchard is the way to go, and I also think that sooner or later `unrepl` support will land in CIDER itself. 

The Clojure Emacs community is small and fragmenting our efforts won't get us far IMO. Collaboration is the key to long-term success.

**Comment by benedekfazekas** [comment]
was not aware of unrepl/spiral#5 thanks for the link
