### ISSUE TITLE
cycle-privacy does not remove `^:private` for `def` forms, instead adds another

### ISSUE THREAD

**Issue by blak3mill3r** [clojure-emacs/clj-refactor.el#409]
## Expected behavior

the `cycle-privacy` refactoring cycles for `def` forms cycles privacy

## Actual behavior

adding `^:private` again, rather than removing it if it's already there

## Steps to reproduce the problem

put cursor on a public `def` form and do `cycle-privacy` twice

### clj-refactor.el version information

`2.4.0-SNAPSHOT`
`master` of this repository at the time of writing (double checked)

### CIDER version information

```
;; CIDER 0.17.0snapshot, nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_131
```

### Leiningen or Boot version

`Leiningen 2.6.1 on Java 1.8.0_131 OpenJDK 64-Bit Server VM`

### Emacs version

`GNU Emacs 27.0.50`

### Operating system

```
Linux magnathorax 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
```

**Comment by benedekfazekas** [comment]
the implementation of this feature got moved to `clojure-mode` so this could be a regression there?! that said I am on latest `clojure-mode` and can't reproduce the problem

**Comment by blak3mill3r** [comment]
I will try different versions of `clojure-mode` and see what I can uncover.

**Comment by blak3mill3r** [comment]
It works for me, with cider `0.16.0` and the latest `clj-refactor.el`. I can't seem to reproduce the issue, now I am not sure what was happening before.

**Comment by blak3mill3r** [comment]
I was running the latest `clojure-mode` throughout.
