### ISSUE TITLE
Remove dependency on cider

### ISSUE THREAD

**Issue by priyatam** [clojure-emacs/clj-refactor.el#412]
clj-refactor depends on cider, a fullblown IDE, starting with [this](https://github.com/clojure-emacs/clj-refactor.el/commit/786b3df8bef0426999a0e74d05ef62523c0cc05c#diff-64ba2c4df6c907da3a5f3860e9f6913e) commit since mid 2014. While I do not understand the full impact of this dependency today, it would be unfortunate to lose this package's excellent clojure refactoring facilities from developers solely relying on *inf-clojure*.

I have used cider and clj-refactor for over three years myself, and would be disappointed to lose it with my current inf-clojure setup. 

What is the effort required to exclude this dependency, fork it, in order to streamline this library's scope?

### clj-refactor.el version information

latest

### CIDER version information
0.16

### Leiningen or Boot version

Lein - 2.8.1

### Emacs version

24.5

### Operating system

Ubuntu 17.10

**Comment by expez** [comment]
You don't have to actually use CIDER to make its utility functions available to clj-refactor.  Elpa will install it in the background and you won't even notice it's there. 

The same goes for the middleware part of the solution.  refactor-nrepl uses utility functions from cider-nrepl, but that's just another dependency like any other.

We're automagically injecting dependencies these days, so you might have to go old-scool and add them to the plugins part of `profiles.clj` to get it working.

If you're simplifying to the point where you're not going to be running any middleware either, then you don't even need clj-refactor.  @benedekfazekas did a fantastic job in moving all refactorings that don't depend on our own middleware into `clojure-mode`, so they could be available to everyone.

Hope that answers your question.

**Comment by benedekfazekas** [comment]
As @expez said essentially. Some thought that migrating [those features](https://github.com/clojure-emacs/clojure-mode#refactoring-support) to `clojure-mode` were a bit of waste it could pay off for your case tho. So let us know which features you are particularly after when you are using `cljr`

**Comment by priyatam** [comment]
Thanks for your comments and pointing out refactoring options in clojure-mode. I'd have to use it for a while before reconsidering clj-refactor,el.
