### ISSUE TITLE
Failed to launched Emacs25 with clj-refactor, Symbol's value as variable is void: seq-random-elt

### ISSUE THREAD

**Issue by qianyan** [clojure-emacs/clj-refactor.el#414]
## Expected behavior
Emacs25 launched with clj-refactor successfully

## Actual behavior
Lisp error: (void-variable seq-random-elt)
Symbol's value as variable is void: seq-random-elt
## Steps to reproduce the problem
```
$ open Emacs.app --args --debug-init 

Debugger entered--Lisp error: (void-variable seq-random-elt)
...
[seq-random-elt sequence put seq--when-emacs-25-p 
lisp-indent-function (lambda (&rest x) 0) edebug-form-spec t cl-defgeneric 
"Return a random element from SEQUENCE.\nSignal an error if SEQUENCE is empty." 
seq-empty-p error "Sequence cannot be empty" seq-elt random seq-length provide seq-25] 9)
```

### clj-refactor.el version information
clj-refactor-2.3.1
clj-refactor-20180330.213

### CIDER version information
cider-20180402.2126

### Emacs version
25.3.1

### Operating system
macOS High Sierra 10.13.3

**Comment by expez** [comment]
Hi

this is the emacs version I'm running on this computer and everything is honky dory.

Try blasting away the directory in `.emacs.d/elpa` to get rid of old bytecompiled files.

Best of luck!

**Comment by Kejia** [comment]
i encountered the same issue on both debian and macos. my emacs-version: 25.1.1. it's definitely a bug existing in clj-refactor. now i have to shadow it out; otherwise all my customization keybindings are broken.

**Comment by benedekfazekas** [comment]
there are newer versions of cider and clj-refactor than the ones quoted above. please install latest stable releases of both, clean all possible old `elc` files and retest. Thanks
