### ISSUE TITLE
not compatible with cider  0.17.0

### ISSUE THREAD

**Issue by maruks** [clojure-emacs/clj-refactor.el#419]
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor

### clj-refactor.el version information
2.3.1

### CIDER version information

0.17.0

**Comment by benedekfazekas** [comment]
Use latest snapshot 9f cljr please. That should work ok

**Comment by jiacai2050** [comment]
@benedekfazekas  

Cider jack in with `2.4.0-SNAPSHOT` still don't work with cider 0.17

Starting nREPL server via lein update-in :dependencies conj \[org.clojure/tools.nrepl\ \"0.2.13\"\ \:exclusions\ \[org.clojure/clojure\]\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0-SNAPSHOT\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.4.0-SNAPSHOT\"\] -- update-in :plugins conj \[refactor-nrepl\ \"2.3.1\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.17.0\"\] -- repl :headless :host ::...
nREPL server started on 52775
[nREPL] Establishing direct connection to localhost:52775 ...
[nREPL] Direct connection to localhost:52775 established
error in process filter: queue-enqueue: Wrong type argument: queue, [cl-struct-queue nil nil]
error in process filter: Wrong type argument: queue, [cl-struct-queue nil nil]
error in process filter: nrepl-send-sync-request: Sync nREPL request timed out (op clone id 1)
error in process filter: Sync nREPL request timed out (op clone id 1)

**Comment by jiacai2050** [comment]
Sorry, 2.4.0-SNAPSHOT did work with cider 0.17. 
The error above arose when upgrade Emacs from 25 to 26, which require re-install all packages according to https://stackoverflow.com/a/24735377
