### ISSUE TITLE
Error using am (Add missing libspec): `info-clj` does not exist

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-refactor.el#420]
## Stack

Emacs:

```
cider-20180526.8
clj-refactor-20180420.223
clojure-mode-20180516.640
```

JVM:

refactor-nrepl-2.4.0-20180410.152833-6.jar

## The problem

* Type `trim`
* Execute `am` command, in hope I'll get a libspec inserted
* Instead the following error pops up: https://gist.githubusercontent.com/vemv/0076ba93c9aae6ff8b449fbd070c9a70/raw/d884229e27d02f2c3143af69f649aca1f00a732c/gistfile1.txt

Worth adding that other commands (particularly those requiring the middleware) work, e.g. `cn`.

Thanks - Victor

**Comment by expez** [comment]
cider-nrepl no longer has this function.  It has been moved to the new orchard project.

**Comment by expez** [comment]
> So what is the fix?

We have to upgrade the middleware to use orchard instead of cider-nrepl and publish a new snapshot.

**Comment by expez** [comment]
Unfortunately it doesn't look like it's as easy as that.  We're going to have to depend on both cider-nrepl and orchard.

Maybe we should just mranderson the old version of cider-nrepl for now, @benedekfazekas?

**Comment by benedekfazekas** [comment]
ok obviously i am mixing up add project dependency with add missing libspec. sorry.

so please ignore 3rd paragraph ;)

**Comment by bbatsov** [comment]
> Unfortunately it doesn't look like it's as easy as that. We're going to have to depend on both cider-nrepl and orchard because only some of the stuff we use has been moved.

Well, that shouldn't really a be a problem. There will always be some nREPL-specific stuff that will only be in `cider-nrepl` (e.g. the lazy middleware loading, which `refactor-nrepl` users are certainly going to love). 

In this particular case the fix is trivial - the API is more or less the same, it's just organized better now.

> tbh cider snapshot is in loads of flux atm with multiple rewrites and orchard going on.

Multiple rewrites? :) That's news to me. I really hope that @vspinu is working on the connection handling rewrite, but I'm not doing anything else to mess up with his work.

**Comment by vspinu** [comment]
>  I really hope that @vspinu is working on the connection handling

I do. In all confidence it will be finished by the end of the next week.

**Comment by bbatsov** [comment]
@vspinu Great news! I've intentionally avoided touching any of the Elisp, so you'd be able to work easily on this. I'll keep touching nothing material there until you finish.

**Comment by bbatsov** [comment]
Btw, I recently fixed this. See https://github.com/clojure-emacs/refactor-nrepl/commit/c8856230dffaf25db2db1ae560fae7211fb1515f
