### ISSUE TITLE
install failed!

### ISSUE THREAD

**Issue by damon-kwok** [clojure-emacs/clj-refactor.el#421]
OS:archlinux
Emacs:26.1

````shell
package-install clj-refactor
````
output:
Compiling file /home/damon/.emacs.d/elpa/clj-refactor-20180526.803/clj-refactor.el at Sat Jun  9 23:03:08 2018
clj-refactor.el:44:1:Error: Wrong type argument: stringp, package-desc

**Comment by benedekfazekas** [comment]
This happens sometimes when you have an old `elc` file in your elpa directory. Try to nuke the cljr package (uninstall and/or delete) and install clean. The error should go away.

**Comment by damon-kwok** [comment]
thanks
