### ISSUE TITLE
cljr-find-usages: Symbol’s function definition is void: cider-current-repl-buffer

### ISSUE THREAD

**Issue by SamirHafez** [clojure-emacs/clj-refactor.el#423]
## Expected behavior
1. Hover over a symbol (like a function parameter)
2. Execute `cljr-find-usages`
3. Display list of usages in current and other files

## Actual behavior
1. Hover over a symbol (like a function parameter)
2. Execute `cljr-find-usages`
3. Hover over a symbol (like a function parameter)
2. `cljr--find-symbol: Symbol’s function definition is void: cider-current-repl-buffer Invalid face reference: t`

nrepl logged messages:
```
(-->
  id         "45"
  op         "info"
  session    "3ce307bb-5a14-4eb6-8c13-0b5d2b419141"
  time-stamp "2018-06-27 17:36:21.209843000"
  ns         "loma.core.domain.actions"
  symbol     "event"
)
(<--
  id         "45"
  session    "3ce307bb-5a14-4eb6-8c13-0b5d2b419141"
  time-stamp "2018-06-27 17:36:21.214914000"
  status     ("done" "no-info")
)

```

## Steps to reproduce the problem
Start a new lein project and add a function with a parameter for usage finding.

## Environment & Version information
- Clojure 1.9.0
- Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

### clj-refactor.el version information
- clj-refactor 2.4.0-SNAPSHOT (package: 20180526.803), refactor-nrepl 2.4.0-SNAPSHOT

### CIDER version information
- CIDER 0.18.0snapshot (package: 20180624.2344), nREPL 0.2.13
- Clojure 1.9.0, Java 1.8.0_172

### Leiningen or Boot version
- Leiningen 2.8.1 on Java 1.8.0_172 Java HotSpot(TM) 64-Bit Server VM

### Emacs version
25.3.1

### Operating system
OSX 10.13.4 "High Sierra"

**Comment by bbatsov** [comment]
That's a result of some API changes that recently happened in CIDER. I'll add some compatibility alias there.

**Comment by benedekfazekas** [comment]
thanks @bbatsov
