### ISSUE TITLE
clj-refactor.el Unavailable through Melpa

### ISSUE THREAD

**Issue by achesnais** [clojure-emacs/clj-refactor.el#428]
Hi all,

It appears the latest clj-refactor build is giving a 404 on Melpa: https://melpa.org/packages/clj-refactor-20180708.57.tar

As a result it's not possible to install it via `package-install`.

Other packages are served fine by Melpa, so could this be due to a bug in the build itself?

**Comment by expez** [comment]
Thanks for report!

I'm not sure why this is so.  I've opened an issue over at the melpa repo to get some help from the experts :)

**Comment by bbatsov** [comment]
Seems this is fixed now.
