### ISSUE TITLE
cljr-slash stopped working - fixed by installing older peg package 

### ISSUE THREAD

**Issue by FreekPaans** [clojure-emacs/clj-refactor.el#441]
Hi all,

Sorry, I don't really know where else to put this, so feel free to close this is issue if it's not relevant. Also I'm a complete Emacs noob, so please excuse my ignorance.

Nevertheless, I recently updates some of my emacs packages, and as a result `cljr-slash` stopped providing me "magic requires" for my custom namespaces. It still worked for stuff like `str` or `io`. I spent some time debugging, and it turned out that somewhere in elisp, an EDN nrepl-response message failed to parse. The stack trace looked a bit like this:

```elisp
 (wrong-type-argument number-or-marker-p nil)
  peg-record-failure((set nil (9 32 10 44) nil))
  #f(compiled-function () #<bytecode 0x46c7c345>)()
  #f(compiled-function () #<bytecode 0x46c7c299>)()
  #f(compiled-function () #<bytecode 0x46c65a41>)()
  edn--read()
  edn--read-from-string("{:clj {
  edn-read("{:clj {...
  cljr--call-middleware-for-namespace-aliases()
  cljr--get-aliases-from-middleware()
  eval((cljr--get-aliases-from-middleware) nil)
  eval-expression((cljr--get-aliases-from-middleware) nil nil 127)
  funcall-interactively(eval-expression (cljr--get-aliases-from-middleware) nil nil 127)
  #<subr call-interactively>(eval-expression nil nil)
  apply(#<subr call-interactively> eval-expression (nil nil))
 ...
```
I tried parsing some EDN manually, and that also failed. So I suspected an issue with the EDN parser itself. And then I just tried something -> tried to revert the upstream `peg` dependency (required by the `edn` package), from `1.0` back to a previous version (`0.6`). Reverting didn't seem possible, so I just installed it as an extra (I think). Either way, this solved my problem.

Hope it helps for other people.

**Comment by expez** [comment]
I'll close this here and continue the discussion over in  the other repo.  Thanks for this report, though, it might indeed help someone else!
