### ISSUE TITLE
cljr-clean-ns easy fix

### ISSUE THREAD

**Issue by boymaas** [clojure-emacs/clj-refactor.el#442]
Excuses no time to fill in the complete form. Just a quick pointer, got the following error `string-prefix-p: Wrong type argument: stringp, nil` when trying to use `cljr-clean-ns`. A quick debug shows a very quick fix.

https://github.com/clojure-emacs/clj-refactor.el/blob/9f508bbf7bf8dd439a78066a9d6fa47f4bc8f64f/clj-refactor.el#L2738-L2740

It uses a `let` which I believe should be a `let*`. Wondering why this was not noticed before.

Thanks for a great library!!

**Comment by expez** [comment]
Thanks for the report!

> Wondering why this was not noticed before.

This code path was added about a month ago and is used only in some situations.

**Comment by expez** [comment]
[solved](https://github.com/clojure-emacs/clj-refactor.el/pull/474)
