### ISSUE TITLE
Error in `cljr-clean-ns` when js literal is present

### ISSUE THREAD

**Issue by Frozenlock** [clojure-emacs/clj-refactor.el#443]
## Expected behavior
Cleaning the namespace with `cljr-clean-ns`.

## Actual behavior
Error when encountering `#js`.
```
cljr--maybe-rethrow-error: clojure.lang.ExceptionInfo: [line 10, col 4] No reader function for tag js. {:type :reader-exception, :ex-kind :reader-error, :file "<my-file>", :line 10, :col 4}
```
No error with other tag literal such as `#inst "1985-04-12"`.

## Steps to reproduce the problem

Create a clojurescript file with a js literal such as `#js {:a 1}`.
Try to run `cljr-clean-ns`.

### clj-refactor.el version information

clj-refactor 2.4.0, refactor-nrepl 2.4.0

### CIDER version information

CIDER 0.21.0 (New York), nREPL 0.6.0
Clojure 1.10.0, Java 1.8.0_212

### Leiningen or Boot version

Leiningen 2.9.1 on Java 1.8.0_212 OpenJDK 64-Bit Server VM

### Emacs version

Emacs 26.2

### Operating system

Ubuntu 18.04.2 LTS

**Comment by aiba** [comment]
My personal workaround for this is to use the `j/lit` macro from the [appliedsciencestudio/js-interop](https://github.com/appliedsciencestudio/js-interop) library, but it would be great if this was fixed in clj-refactor.

**Comment by Frozenlock** [comment]
I found 2 fixes for, but I'm not familiar enough with the rest of the code to know if it's acceptable.
Both fixes apply to [find/symbols-in-file](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/find/symbols_in_file.clj#L58).


### 1
Similarly to how it's done [here](https://github.com/clojure/clojurescript/blob/42433848bafc973e018f926226d76016aab9a857/src/main/clojure/cljs/core/server.clj#L94), the reader could be augmented with the built-in cljs tag literals.

However I'm not sure it's okay to impose a Clojurescript requirement in this namespace.


### 2
Alternatively, we could add a default data reader that would simply drop the tag and return the form. If it's anything else than valid Clojure it could throw an error, but without a default reader we're already throwing anyway.

```clj
[*ns* file-ns
 reader/*data-readers* *data-readers*
 reader/*default-data-reader-fn* (fn [_tag form] form) ;; <---- added
 mranderson048.toolsreader.v1v1v1.clojure.tools.reader/*alias-map* ns-aliases]
```

Should I open an issue in [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) instead?

**Comment by expez** [comment]
I like alternative 2) here.  You're right that the discussion belongs to the refactor-nrepl so feel free to open a PR over there.  

Thanks for investigating, @Frozenlock!

**Comment by Frozenlock** [comment]
PR submitted https://github.com/clojure-emacs/refactor-nrepl/pull/280.
