### ISSUE TITLE
`cljr-favor-prefix-notation` not respected for cljs

### ISSUE THREAD

**Issue by lins05** [clojure-emacs/clj-refactor.el#452]
## Expected behavior

When `cljr-favor-prefix-notation` is t and I call `cljr-clean-ns` on a cljs file, it shall give me the proper arranged ns form in prefix notation.

## Actual behavior

This variable doesn't have any effect for cljs files. (Works for clj files, though).

## Steps to reproduce the problem

```clojure
(ns foo
  (:require [clojure.string :refer [blank?]]
            [clojure.walk :refer [postwalk]]))
```

`cljr-clean-ns` has no effect even with `cljr-favor-prefix-notation` set to t.

### clj-refactor.el version information

```
clj-refactor 2.5.0-SNAPSHOT (package: 20190618.716), refactor-nrepl 2.5.0-SNAPSHOT
```
### CIDER version information

```
;; CIDER 0.24.0snapshot (package: 20191019.1042), nREPL 0.6.0
;; Clojure 1.10.1, Java 1.8.0_222
```

### Leiningen or Boot version

Shadow-cljs 2.8.71

### Emacs version

26.1

### Operating system

OSX 10.14

**Comment by expez** [comment]
Clojurescript [doesn't support](https://clojurescript.org/about/differences#_namespaces) prefix notation, which is why that setting is ignored in that language context.
