### ISSUE TITLE
`cljr-clean-ns` keep quotes around NPM requires?

### ISSUE THREAD

**Issue by aiba** [clojure-emacs/clj-refactor.el#453]
Currently, `cljr-clean-ns` tries to remove quotes from NPM requires.  For example:

```
(ns foo
  (:require ["react" :refer [createElement]]))
```

gets cleaned into:

```
(ns foo
  (:require [react :refer [createElement]]))
```

Personally, I like having the quotes around "react" to remind myself that it's an NPM package, not really a clojure namespace.  And it usueally comes with other NPM packages, for example:

```
(ns foo
  (:require ["react" :refer [createElement]]
            ["react-dom/server" :as ReactDOMServer]))
```

It's nice having quotes around both package names.

Perhaps we could have an option to not remove the quotes?

## Environment & Version information

```
clj-refactor 2.5.0-SNAPSHOT (package: 20190618.716)
CIDER 0.24.0snapshot (package: 20191103.1528)
GNU Emacs 26.3
```

**Comment by expez** [comment]
> Perhaps we could have an option to not remove the quotes?

Using strings in the ns form wasn't really a thing back when clean ns was written.  The current behavior is a bug, more so than it is a feature, in the sense that no thought was given to this situation at all.
