### ISSUE TITLE
Use styleguide formatting for cljr-add-missing-libspec

### ISSUE THREAD

**Issue by kwrooijen** [clojure-emacs/clj-refactor.el#459]
Currently when using `cljr-add-missing-libspec`, the namespaces are inline with the `:require` keyword. 

It is formatted as the `good` example of the [community styleguide](https://github.com/bbatsov/clojure-style-guide#line-breaks-in-ns) instead of the `better` example.

Wouldn't it make sense to have it format to the `better` example?
Or is the documentation maybe outdated and should `better` / `good` be swapped?

**Comment by expez** [comment]
Sure, a PR that fixes this would be welcome.

This would require work in our sister repo, refactor-nrepl, as it's the middleware that takes care of making the ns tidy (with the clean-ns operation).  Most likely the edit is needed in our homemade pretty-printing code 

Not a bad first issue to take on, if you want to get familiar with the code base.

**Comment by kwrooijen** [comment]
Thanks for the info, I'll see if I can take a look.
