### ISSUE TITLE
Doesn't work with CIDER 24

### ISSUE THREAD

**Issue by maruks** [clojure-emacs/clj-refactor.el#464]
cider              0.24.0
clj-refactor       20200219.1038

Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "edn")
  require(edn)
  eval-buffer(#<buffer  *load*-214271> nil "/Users/maris/.emacs.d/elpa/clj-refactor-20200219.1038/clj-refactor.el" nil t)  ; Reading at buffer position 1902
  load-with-code-conversion("/Users/maris/.emacs.d/elpa/clj-refactor-20200219.1038/clj-refactor.el" "/Users/maris/.emacs.d/elpa/clj-refactor-20200219.1038/clj-refactor.el" nil t)
  (cljr--inject-jack-in-dependencies)
  (lambda nil (cljr--inject-jack-in-dependencies))()
  eval-after-load-helper("/Users/maris/.emacs.d/elpa/cider-0.24.0/cider.elc")

**Comment by bbatsov** [comment]
Fixed by #463. I had forgotten to update one require.
