### ISSUE TITLE
Hotload Dependencies

### ISSUE THREAD

**Issue by credmp** [clojure-emacs/clj-refactor.el#466]
As there is not current issue tracking this development I am making one. I really miss this functionality and would like to see it added back. I would like to know what needs to be done to achieve this, perhaps it is within my scope to build it?

##  Expected behavior

Add a dependency to the project and have it automatically loaded in the running repl.

## Actual behavior

Temporarily disabled due to make the middleware run with Java 10.

```
(defun cljr-hotload-dependency ()
  "Download a dependency (if needed) and hotload it into the current repl session.
Defaults to the dependency vector at point, but prompts if none is found.
See: https://github.com/clojure-emacs/clj-refactor.el/wiki/cljr-hotload-dependency"
  (interactive)
  (user-error "Temporarily disabled due to make the middleware run with Java 10."))
```

## Steps to reproduce the problem

Simply invoke the function.

### clj-refactor.el version information

2.5.0

**Comment by mitchell-horning** [comment]
[refactor-nrepl/206](https://github.com/clojure-emacs/refactor-nrepl/issues/206) has some further discussion on the topic. It looks like there is a workaround that uses `tools.deps` or `pomegranate`.

**Comment by bbatsov** [comment]
Yeah, nREPL now makes it much easier to leverage one of those 2 tools directly https://nrepl.org/nrepl/usage/misc.html#_hot_loading_dependencies

**Comment by viebel** [comment]
@bbatsov  could you elaborate on what in latest nREPL makes it easier to hot load dependencies?

**Comment by divs1210** [comment]
A blogpost on achieving this with pomegranate:
https://www.eigenbahn.com/2020/05/06/fast-clojure-deps-auto-reload

**Comment by bbatsov** [comment]
> @bbatsov could you elaborate on what in latest nREPL makes it easier to hot load dependencies?

@viebel Its classloader was modified to support hot-loading during ordinary evaluation - this makes possible the solution outlined in the blog post.

**Comment by magnars** [comment]
With the solution so readily at hand, is there a reason why the support has not been turned on again in clj-refactor? In particular with the `cljr-add-project-dependency` command? Or is this issue just waiting for someone to do it?

**Comment by bbatsov** [comment]
@magnars Because someone has to implement this first (e.g. by updating `refactor-nrepl`). :-)

**Comment by magnars** [comment]
That's fair :-) I've added a "help wanted" label if anyone wants to tackle this.

**Comment by vemv** [comment]
Hot-loading dependencies might arrive at some point ([clojure-emacs/refactor-nrepl#301](https://github.com/clojure-emacs/refactor-nrepl/pull/301) or delivered in an arbitrary 3rd-party dep), other than that, tracking this issue doesn't happen to help - it's a task that's been tried a bunch of times, by different people, in different projects etc.

tools.deps' add-lib branch seems to work reasonably well, and I think @plexus had interesting WIP.

**Comment by plexus** [comment]
We've had good success with [lambdaisland/classpath](https://github.com/lambdaisland/classpath), but it's the sort of thing where no perfect solution exists.
