### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by drdebit** [clojure-emacs/clj-refactor.el#472]
## Expected behavior

Loading clj-refactor using (require 'clj-refactor) in my init.el file throws no errors.

## Actual behavior

I receive this stacktrace when running emacs with the --debug-init option:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  (defvar cider-sideloader-dir (file-name-directory buffer-file-name))
  require(cider-eval)
  eval-buffer(#<buffer  *load*-760068> nil "/home/matt/.emacs.d/elpa/cider-20200625.658/cider-mode.el" nil t)  ; Reading at buffer position 1316
  load-with-code-conversion("/home/matt/.emacs.d/elpa/cider-20200625.658/cider-mode.el" "/home/matt/.emacs.d/elpa/cider-20200625.658/cider-mode.el" nil t)
  require(cider-mode)
  eval-buffer(#<buffer  *load*-447748> nil "/home/matt/.emacs.d/elpa/cider-20200625.658/cider.el" nil t)  ; Reading at buffer position 2711
  load-with-code-conversion("/home/matt/.emacs.d/elpa/cider-20200625.658/cider.el" "/home/matt/.emacs.d/elpa/cider-20200625.658/cider.el" nil t)
  require(cider)
  eval-buffer(#<buffer  *load*-234873> nil "/home/matt/.emacs.d/elpa/clj-refactor-20200405.1419/clj-refactor.el" nil t)  ; Reading at buffer position 1876
  load-with-code-conversion("/home/matt/.emacs.d/elpa/clj-refactor-20200405.1419/clj-refactor.el" "/home/matt/.emacs.d/elpa/clj-refactor-20200405.1419/clj-refactor.el" nil t)
  require(clj-refactor)
  eval-buffer(#<buffer  *load*> nil "/home/matt/.emacs.d/init.el" nil t)  ; Reading at buffer position 11662
  load-with-code-conversion("/home/matt/.emacs.d/init.el" "/home/matt/.emacs.d/init.el" t t)
  load("/home/matt/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x25e919>)()
  command-line()
  normal-top-level()

## Steps to reproduce the problem

On my system, trying to load the library is sufficient to get the error.

### clj-refactor.el version information

cljr-version doesn't work correctly at the moment, but my elpa folder contains clj-refactor-20200405.1419

### CIDER version information

;; CIDER 0.26.0snapshot (package: 20200625.658), nREPL 0.8.0-alpha3
;; Clojure 1.10.0, Java 1.8.0_252

### Leiningen or Boot version

Leiningen 2.9.1 on Java 1.8.0_252 OpenJDK 64-Bit Server VM

### Emacs version

26.3

### Operating system

Ubuntu 18.04.4

**Comment by bbatsov** [comment]
I had made a silly mistake in CIDER that I just fixed. Sorry about that! You'll need to update CIDER after the MELPA package gets rebuilt.

**Comment by drdebit** [comment]
No worries, thank you!
