### ISSUE TITLE
cljr-slash documentation seems out of date

### ISSUE THREAD

**Issue by lverns** [clojure-emacs/clj-refactor.el#481]
## Expected behavior

Docstring for `cljr-slash` correctly describes behavior of the function

## Actual behavior

Docstring says 
```
If ‘cljr-magic-require-namespaces’ is non-nil, typing one of the
short aliases listed in ‘cljr-magic-requires’ followed by this
command will add the corresponding require statement to the ns
form.
```

However, having done no customization:
- cljr-magic-requires is `t`
- cljr-magic-require-namespaces is 
```
(("io" . "clojure.java.io")
 ("set" . "clojure.set")
 ("str" . "clojure.string")
 ("walk" . "clojure.walk")
 ("zip" . "clojure.zip"))
```

So it seems the docstring has confused which var is the list and which is the toggle. 

Also, cljr-magic-require-namespaces is a very short list, but cljr-slash works for many other aliases that I use in my project, so the claim that cljr-slash just pulls from a list does not seem true either.

### clj-refactor.el version information

clj-refactor 2.5.1, refactor-nrepl 2.5.0

### CIDER version information

CIDER 1.0.0 (package: 20210125.1630) (Sofia), nREPL 0.8.0
Clojure 1.10.1, Java 11.0.8

### Emacs version

GNU Emacs 27.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0) of 2020-08-20

### Operating system

Fedora release 32 (Thirty Two)

**Comment by lverns** [comment]
Looks like more up to date docs are in https://github.com/clojure-emacs/clj-refactor.el/pull/219, but we'll need to confirm if anything significant has changed since 2015

**Comment by expez** [comment]
> So it seems the docstring has confused which var is the list and which is the toggle.

That seems to be the case!

> Also, cljr-magic-require-namespaces is a very short list, but cljr-slash works for many other aliases that I use in my project, so the claim that cljr-slash just pulls from a list does not seem true either.

Yes, the list is just a seed.  This function was later enhanced to also use the middleware to find all the aliases that are in use in the project.  That way, if you use consistent aliases, you can just bring everything in after using it the first time :)

If you want to get your hands dirty, a PR for an updated docstring would be most welcome.
