### ISSUE TITLE
clj-refactor customize support is missing a defgroup form

### ISSUE THREAD

**Issue by pierre-rouleau** [clojure-emacs/clj-refactor.el#482]
## Expected behavior
When using M-x customize-group cljr, you should be able to see the group's parent.

## Actual behavior
The cljr customize buffer shows: "Group definition missing." instead.

## Steps to reproduce the problem
- ``M-x customize-group cljr``
-  Read line 9 where the message shows.

## Environment & Version information
Not relevant here, but tested on Emacs 26.3 on macOS Mojave.

### clj-refactor.el version information
clj-refactor 2.5.1 (package: 20210216.928)

### CIDER version information

N/A.

### Leiningen or Boot version

N/A.

### Emacs version

Emacs 26.3

### Operating system

macOS Mojave

## Extra Notes
I can submit a pull-request with the fix.

**Comment by bbatsov** [comment]
Looks good. Guess we overlooked this.

**Comment by pierre-rouleau** [comment]
I'll submit later today after I have time to setup an environment with Emacs 27 and cask to be able to run your tests

**Comment by bbatsov** [comment]
For such a simple change that's not really needed. I'm sure it won't break anything.

**Comment by pierre-rouleau** [comment]
I thought so too, but since I never submitted anything here, I was going to play nice. So OK, I'll go ahead and submit.  There's so little time and soooo many things to do...  
BTW. Thanks for all of these Clojure projects!

**Comment by bbatsov** [comment]
> I thought so too, but since I never submitted anything here, I was going to play nice. So OK, I'll go ahead and submit. There's so little time and soooo many things to do...

I know what you mean. 😄 

> BTW. Thanks for all of these Clojure projects!

You're welcome! Btw, you finally pushed me to update the CI build of the project, so at least people can get some feedback on their PRs without having to setup the test developments locally.
