### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#491]
Looks like two things are going on:

1. One actual test failure for emacs versions 26 and 27.
2. Test check validating grammar etc

Can we turn off test check?  I'd rather have a green build badge giving an indication that this lib is alive and kicking.
Furthermore, with limited time available I'd much rather fix actual bugs than go over 3k lines of code to make sure e.g. error messages don't end in a period.

**Comment by bbatsov** [comment]
I'd disable the offending test as the quickest solution. I'm also fine with disabling `checkdoc`, although it's not grammar check. Still, it's not something particularly important.

**Comment by bbatsov** [comment]
Btw, when I checked the CI I saw that only the one test if failing.

**Comment by vemv** [comment]
> I'd disable the offending test as the quickest solution. 

(We did so)
