### ISSUE TITLE
Ability to opt out of overlays 

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-refactor.el#506]
@yuhan0 wrote:

> clj-refactor's use of multiple-cursors and interactive overlays often interact in unpredictable ways with Evil and/or undo-fu, corrupting the undo history.

There's a defcustom for multiple-cursors, however not for overlays which don't seem crucial for the provided features.

Looks like it can go through a defcustom? (default: enabled)

**Comment by magnars** [comment]
What overlays are these?

**Comment by vemv** [comment]
From what I checked out, all of them are related to `cljr--highlight`

**Comment by magnars** [comment]
Yes, seems like it's just meant to be a helpful indicator. A defcustom seems like a good idea. 👍

**Comment by bbatsov** [comment]
Can someone share some screenshots? That would make it clearer what we're trying to solve here.

**Comment by vemv** [comment]
@yuhan0: yes, yasnippet is used in various other functionality. Personally I never use those features.

Instead my usage in this area boils down to:

* `cljr-slash`, which doesn't use snippets or overlays
  * e.g. `a/` -> a `core.async` require is inserted
* `cljr-add-missing-libspec`, which also doesn't use snippets or overlays
  * adds a :refer or :import.

Because it's more than possible to have productive workflow without using the more 'invasive' libs, this issue seems good to close.

Feel free to reopen in some other shape!

**Comment by vemv** [comment]
btw as you might have heard, the mentioned ops are much faster starting with the 3.x series of the middleware
