### ISSUE TITLE
cljr-slash: Wrong type argument: listp

### ISSUE THREAD

**Issue by rrudakov** [clojure-emacs/clj-refactor.el#514]
## Expected behavior

namespace is added to `ns` declaration

## Actual behavior

The following error:
```
Debugger entered--Lisp error: (wrong-type-argument listp [clojure\.string])
  cljr--prompt-user-for("Require " [clojure\.string])
  cljr-slash()
  funcall-interactively(cljr-slash)
  command-execute(cljr-slash)
```

## Steps to reproduce the problem

Open any namespace and type `(str/|)`

### clj-refactor.el version information

clj-refactor 3.4.1 (package: 20220307.1857), refactor-nrepl 3.4.0

### CIDER version information

```
;; CIDER 1.3.0 (Ukraine), nREPL 0.9.0
;; Clojure 1.10.3, Java 17.0.3

```

### Emacs version

GNU Emacs 28.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.31, cairo version 1.17.4) of 2022-02-16

### Operating system

Arch Linux

**Comment by vemv** [comment]
Thanks! Will take a look right now.

**Comment by vemv** [comment]
https://github.com/clojure-emacs/clj-refactor.el/blob/v3.4.2/CHANGELOG.md#342

It takes 1-2 hours for Melpa to build a release + snapshot out of it.

The postmortem is that in the JVM middleware, something had changed from list to vector, which seemed innocuous at the time. It was one of those bugs waiting to happen, grrr.

This should get it fixed, if you experience anything else please let us know.

**Comment by rrudakov** [comment]
It works now. Thanks for the quick fix @vemv!

**Comment by vemv** [comment]
Thanks for the confirmation 🍻
