### ISSUE TITLE
cljr-slash breaks whenever there's a Unicode character used as an alias in a codebase

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/clj-refactor.el#540]
If anywhere in a given codebase there's an alias like `[com.brunobonacci.mulog :as μ]`, cljr-slash will stop working in general, silently.

**Comment by dgtized** [comment]
Is that with `cljr-slash-uses-suggest-libspec` enabled or the current default system? It's working locally for me but I'm using `cljr-slash-uses-suggest-libspec`.

I tried adding `[foo.bar as 𝛌]` to one namespace and then typed `𝛌/bar` in another and it imported it just fine. Could you give a more reproducible example of the problem?
