### ISSUE TITLE
Add support for updating :sha in :git/url dependencies

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#553]
I have a feeling this might be too loosey goosey for inclusion here, but just in case:

I added support for fetching the newest `:sha` from a github repo when using `:git/url` dependencies with deps.edn. The code can be found here: https://github.com/magnars/emacsd-reboot/commit/0707f0e2062017516fe875a6ba5304641eeea677

Let me know if it is of any interest, and if so, what changes is necessary for inclusion.

Cheers!
- Magnar

**Comment by vemv** [comment]
Nice one!

I sense that it would be more consistent with what we have to add a 'backend' in `refactor-nrepl.artifacts`.

With that we also would win support for gitlab, maybe private repos (honoring any api token that may be around), etc. Also handling git tags would be a desirable feature (often one wants to pin to commit _and_ tag).

In general, I try for the Elisp clients to be thinner - it's easier to test/maintain/CI clojure code.

I would totally get if that felt a bit burdensome, but we plan to merge clj-refactor.el into CIDER (for CIDER 2.0), so empasizing some patterns would only help.

Cheers - V

**Comment by magnars** [comment]
Makes perfect sense, thank you. :)

**Comment by vemv** [comment]
🤝
